/**
 * `psychometric-lab` — research-only estimators, selection criteria, and
 * engagement detectors for the sweep in `docs/PSYCHOMETRIC_SWEEP_2026-07-28.md`.
 *
 * DELIBERATELY NOT RE-EXPORTED FROM `../index.ts`. The engine's public surface is
 * the approved scoring + replay payload (D-019), and `../index.ts` states that the
 * engine does not route or select items. Nothing in this folder is approved for
 * production scoring: it exists so a sweep can ask what a better lambda estimator,
 * an adaptive selection rule, or a richer engagement signal WOULD buy, with the
 * answer under test rather than assumed.
 *
 * CLAIM BOUNDARY: everything here is exercised against born-synthetic personas
 * generated by the same 3PL that scores them (`synthetic_only: true`,
 * `validated: false`; D-006, R9). Recovery is CIRCULAR — it establishes method,
 * correctness, and statistical power only. It is never evidence that a metric
 * measures real ability, never convergent or predictive validity, and never
 * program impact (R10).
 */

export * from './learning-curve';
export * from './selection';
export * from './engagement-detectors';
export * from './telemetry';
