import { itemInformation, probabilityCorrect } from '../irt';
import type { IrtParameters } from '../types';

/**
 * Candidate within-block learning-rate (lambda) estimators for the psychometric
 * sweep.
 *
 * WHY THIS EXISTS: the representative run in `docs/PERSONA_SIM_RESULTS.md` reported
 * a POWER null for M-LEARNRATE using an OLS slope of the 0/1 score over trial
 * order. An OLS slope on a short binary sequence throws away almost everything the
 * response model knows — it ignores each item's difficulty, discrimination, and
 * guessing floor, and it treats a Bernoulli outcome as if it had constant variance.
 * If lambda is recoverable at all, the estimator that has the best chance is the
 * one that inverts the SAME generative curve `theta(t) = theta0 + lambda * t`
 * through the 3PL. These functions supply that estimator plus the cheap
 * alternatives (trials-to-criterion, block-half contrast) the sweep compares it
 * against, so "the estimator is weak" and "the effect is too small to see" can be
 * separated.
 *
 * CLAIM BOUNDARY: recovering lambda from responses generated by this same curve is
 * CIRCULAR. A high correlation here establishes statistical power and estimator
 * correctness under known truth; it is never evidence that a within-session
 * learning rate measures real learning, real acceleration, or program impact
 * (R10). M-LEARNRATE remains a labelled hypothesis (H-series).
 *
 * SCOPE: deliberately NOT exported from `../index.ts`. The engine's public surface
 * is the approved scoring/replay payload; nothing here is approved for production
 * scoring, and adding it to the payload would imply otherwise.
 *
 * Pure and dependency-free: no I/O, no framework, no node-only APIs.
 */

/** One trial inside a novel block, with the trial index the climb is indexed by. */
export interface LearningTrial {
  irt: IrtParameters;
  correct: boolean;
  /** 0-based index inside the block; the climb is `theta0 + lambda * trialIndex`. */
  trialIndex: number;
}

export interface LearningCurveOptions {
  /** Prior mean for the block's starting ability. Default 0. */
  priorTheta0Mean?: number;
  /** Prior SD for the starting ability. Default 1. */
  priorTheta0Sd?: number;
  /** Prior mean for lambda. Default 0 — a null climb is the honest prior. */
  priorLambdaMean?: number;
  /**
   * Prior SD for lambda in theta units per trial. Default 0.15: wide relative to
   * the simulator's injected scale (SD 0.03) so the prior regularizes a short
   * block without dictating the answer. A tighter prior would manufacture
   * agreement with the injected mean rather than measure it.
   */
  priorLambdaSd?: number;
  maxIterations?: number;
  tolerance?: number;
}

export interface LearningCurveEstimate {
  /** Posterior-mode starting ability. */
  theta0: number;
  /** Posterior-mode climb in theta units per trial. */
  lambda: number;
  theta0Se: number;
  lambdaSe: number;
  iterations: number;
  converged: boolean;
}

const THETA0_BOUND = 6;
const LAMBDA_BOUND = 1;

/**
 * Joint MAP estimate of `(theta0, lambda)` under `theta(t) = theta0 + lambda * t`
 * with a 3PL response model, by Fisher scoring with a normal prior on both
 * parameters.
 *
 * Fisher scoring rather than a grid because the profile likelihood over a short
 * block is flat and a grid coarse enough to be affordable inside a 54-cell sweep
 * would quantize lambda at the scale of the effect being measured. The prior is
 * required, not cosmetic: on a 6-trial block the unpenalized likelihood is
 * frequently monotone in lambda and the ML estimate runs to the boundary.
 */
export function estimateLearningCurve(
  trials: readonly LearningTrial[],
  options: LearningCurveOptions = {},
): LearningCurveEstimate {
  const {
    priorTheta0Mean = 0,
    priorTheta0Sd = 1,
    priorLambdaMean = 0,
    priorLambdaSd = 0.15,
    maxIterations = 60,
    tolerance = 1e-7,
  } = options;

  const theta0Precision = 1 / (priorTheta0Sd * priorTheta0Sd);
  const lambdaPrecision = 1 / (priorLambdaSd * priorLambdaSd);

  let theta0 = priorTheta0Mean;
  let lambda = priorLambdaMean;
  let iterations = 0;
  let converged = false;

  let h00 = theta0Precision;
  let h01 = 0;
  let h11 = lambdaPrecision;

  for (let iter = 0; iter < maxIterations; iter++) {
    iterations = iter + 1;
    let g0 = (priorTheta0Mean - theta0) * theta0Precision;
    let g1 = (priorLambdaMean - lambda) * lambdaPrecision;
    h00 = theta0Precision;
    h01 = 0;
    h11 = lambdaPrecision;

    for (const trial of trials) {
      const t = trial.trialIndex;
      const theta = theta0 + lambda * t;
      const { a, c } = trial.irt;
      const p = probabilityCorrect(theta, trial.irt);
      if (p <= 0 || p >= 1) continue;
      const u = trial.correct ? 1 : 0;
      // 3PL score contribution, identical to the MLE in `../theta.ts`.
      const s = (a * (p - c) * (u - p)) / (p * (1 - c));
      const info = itemInformation(theta, trial.irt);
      g0 += s;
      g1 += t * s;
      h00 += info;
      h01 += t * info;
      h11 += t * t * info;
    }

    const det = h00 * h11 - h01 * h01;
    if (!Number.isFinite(det) || det <= 0) break;
    const step0 = (h11 * g0 - h01 * g1) / det;
    const step1 = (h00 * g1 - h01 * g0) / det;

    // Damp the first moves: an all-correct or all-incorrect block produces a
    // gradient that overshoots straight to the bound and then oscillates.
    const damp = Math.min(1, 2 / (1 + Math.max(Math.abs(step0), 10 * Math.abs(step1))));
    theta0 = clamp(theta0 + damp * step0, -THETA0_BOUND, THETA0_BOUND);
    lambda = clamp(lambda + damp * step1, -LAMBDA_BOUND, LAMBDA_BOUND);

    if (Math.abs(damp * step0) < tolerance && Math.abs(damp * step1) < tolerance) {
      converged = true;
      break;
    }
  }

  const det = h00 * h11 - h01 * h01;
  const theta0Se = det > 0 ? Math.sqrt(h11 / det) : priorTheta0Sd;
  const lambdaSe = det > 0 ? Math.sqrt(h00 / det) : priorLambdaSd;

  return { theta0, lambda, theta0Se, lambdaSe, iterations, converged };
}

function clamp(x: number, lo: number, hi: number): number {
  return Math.max(lo, Math.min(hi, x));
}

/**
 * 3PL residuals `observed - expected` at a FIXED working ability, in block order.
 * Subtracting the model expectation removes the difficulty ramp that makes a raw
 * score slope negative under an ascending block.
 */
export function threePlResiduals(trials: readonly LearningTrial[], workingTheta: number): number[] {
  return trials.map(
    (trial) => (trial.correct ? 1 : 0) - probabilityCorrect(workingTheta, trial.irt),
  );
}

/**
 * Trials-to-criterion: the 1-based trial index at which `runLength` consecutive
 * correct responses first complete, or `null` when the criterion is never met.
 *
 * A count statistic rather than a slope. On a short block a slope spends its
 * degrees of freedom estimating an intercept it does not need, whereas "when did
 * this child start getting them right" uses the ORDER of the successes directly.
 * Callers must decide how to treat the censored (`null`) case; the sweep scores it
 * at `blockLength + 1`, which is the conservative reading.
 */
export function trialsToCriterion(correct: readonly boolean[], runLength = 3): number | null {
  if (runLength < 1) throw new Error('trialsToCriterion: runLength must be at least 1');
  let run = 0;
  for (let i = 0; i < correct.length; i++) {
    run = correct[i] ? run + 1 : 0;
    if (run >= runLength) return i + 1;
  }
  return null;
}

/**
 * Second-half mean minus first-half mean. The lowest-variance contrast that can
 * detect a monotone climb: it is the slope statistic with every within-half
 * ordering discarded, which on a short binary block costs little signal and
 * removes a large amount of estimator noise. An odd-length block drops its
 * middle trial so the two halves stay symmetric.
 */
export function blockHalfContrast(values: readonly number[]): number | null {
  if (values.length < 2) return null;
  const half = Math.floor(values.length / 2);
  let first = 0;
  let second = 0;
  for (let i = 0; i < half; i++) first += values[i]!;
  for (let i = values.length - half; i < values.length; i++) second += values[i]!;
  return (second - first) / half;
}
