import { existsSync, statSync } from 'node:fs';
import { readFile } from 'node:fs/promises';
import path from 'node:path';

import type { ServedItem } from '@gt-selection/exam-engine';

import { EXAM_TYPE_CODES } from './registry.generated';

/**
 * SERVER-ONLY bank loader (BUILD_PLAN §2/§6). Reads every wired structured bank
 * from `research/exam-question-types/banks/*.jsonl`, caches them in-process, and
 * exposes:
 *
 *  - {@link getServedItems} — items with `answer`/`scoring`/`provenance` STRIPPED
 *    (a `ServedItem` is all the browser may ever see); supports a `typeCode` +
 *    nearest-`difficulty` filter.
 *  - {@link findBankItem} — the FULL item incl. the server-only answer key, for
 *    server-authoritative verification in `/api/exam-submit`.
 *
 * The answer key, scoring mode, and provenance NEVER leave this module toward the
 * browser. Only route handlers (server) import this file. Born-synthetic only
 * (`syntheticOnly=true`, `validated=false`).
 */

/**
 * Every type code with a structured bank AND a protocol-compliant renderer.
 * Generated by `scripts/sync-exam-demos.mjs` — the served pool and the
 * `/api/exam-submit` verifier both widen automatically when a bank is added.
 */
export const BANK_TYPE_CODES: readonly string[] = EXAM_TYPE_CODES;
export type BankTypeCode = string;

/**
 * A full bank item as stored on disk. `answer` / `scoring` / `provenance` are
 * SERVER-ONLY. `correctKey` is a string option key (e.g. `"B"`) for keyed types
 * or a numeric option index for index-keyed types (e.g. VER-RELPAIR).
 */
export interface RawBankItem {
  itemId: string;
  typeCode: string;
  domain: ServedItem['domain'];
  difficulty: number;
  ageBands: ServedItem['ageBands'];
  content: Record<string, unknown>;
  /**
   * SERVER-ONLY. `correctKey` is a string option key (e.g. `"B"`) or a numeric
   * option index. Non-multiple-choice types carry the extra reference the
   * matching verifier needs (`targetRatio`/`tolerance`, `optimalValue`, …).
   */
  answer: {
    correctKey: string | number;
    distractorRationales?: unknown;
    [field: string]: unknown;
  };
  /** SERVER-ONLY. `rule` selects the verifier in `/api/exam-submit`. */
  scoring?: { mode?: string; rule?: string; [field: string]: unknown };
  provenance?: Record<string, unknown>;
  syntheticOnly: true;
  validated: false;
  /** On-disk relative demo path — NOT served (the runner derives it from typeCode). */
  demoPath?: string;
}

let cache: RawBankItem[] | null = null;

/**
 * The two places the banks can be, spelled out as literal path segments.
 *
 * WHY LITERALS AND WHY MODULE SCOPE. Next's build tracer statically evaluates the argument of
 * every `fs` call it can see, and when it cannot resolve one it falls back to globbing the
 * nearest directory it *did* resolve. This module used to assemble its candidates inside the
 * resolver — `path.join(process.cwd(), '..', '..', ...BANKS_RELATIVE)` — where the spread left
 * the tail unresolvable with `<repo root>` as the resolved prefix, so the tracer globbed the
 * whole repository into the standalone bundle: `docs/`, `infra/`, `brainlifting/`, `supabase/`.
 * Nothing was wrong at runtime, which is exactly why it went unnoticed for so long.
 *
 * Keeping the segments literal, and at module scope where the tracer can fold them once, bounds
 * that glob to the banks directory — measured at 91 MB down to 61 MB. `pnpm bundle:check` fails
 * the build if it comes back. A side effect worth knowing: because the tracer can now resolve
 * these paths, it discovers the banks by itself, so `outputFileTracingIncludes` in
 * `next.config.ts` is no longer the only thing putting them in the image. It is kept as the
 * guarantee for whatever this module looks like after the next refactor.
 *
 * They are ALTERNATIVES, not a search path: cwd is the repo root under the workspace scripts and
 * the vitest suites, and `apps/web` under `next dev`, `next start` and the standalone server
 * (`server.js` chdirs to its own directory, which is why `../..` lands on `/app/research`).
 */
const BANKS_DIR_FROM_REPO_ROOT = path.join(
  process.cwd(),
  'research',
  'exam-question-types',
  'banks',
);
const BANKS_DIR_FROM_APP = path.join(
  process.cwd(),
  '..',
  '..',
  'research',
  'exam-question-types',
  'banks',
);
const BANKS_DIR = existsSync(BANKS_DIR_FROM_REPO_ROOT)
  ? BANKS_DIR_FROM_REPO_ROOT
  : BANKS_DIR_FROM_APP;

/**
 * The bank could not be read, so there is no item pool.
 *
 * This used to be swallowed — a missing file `continue`d, a malformed line was skipped — on the
 * reasoning that one bad bank should not take down the whole battery. In a container that
 * reasoning inverts: the banks live under `research/`, which is not application source, so the
 * failure mode was not "47 of 48 types" but "no types at all", presented to a child as an exam
 * that never starts and to an operator as a healthy deploy. Silence is the wrong default on the
 * path that serves questions to children, so every read failure is now fatal and named.
 */
export class ExamBankUnavailableError extends Error {
  constructor(message: string, options?: ErrorOptions) {
    super(message, options);
    this.name = 'ExamBankUnavailableError';
  }
}

const SHIPPING_HINT =
  'The banks reach a built app through `outputFileTracingIncludes` in apps/web/next.config.ts ' +
  '(they are deliberately NOT published under public/, which would expose every answer key). ' +
  'A build that drops them serves an exam with no items.';

/**
 * Throws unless the resolved banks directory is really on disk, whether cwd is the app, the repo
 * root, or a standalone bundle.
 *
 * Deliberately returns nothing. Every bank path in this module comes from {@link bankFile} so that
 * `BANKS_DIR` is the single expression the build tracer has to fold; handing the directory back
 * here would invite a caller to `path.join` an opaque local instead and quietly un-bound the glob
 * again.
 */
function requireBanksDir(): void {
  if (existsSync(BANKS_DIR)) return;
  throw new ExamBankUnavailableError(
    `No exam item bank directory found from cwd ${process.cwd()}. Looked in:\n` +
      [BANKS_DIR_FROM_REPO_ROOT, BANKS_DIR_FROM_APP].map((dir) => `  - ${dir}`).join('\n') +
      `\n${SHIPPING_HINT}`,
  );
}

/** The only place a bank file path is built. */
function bankFile(code: string): string {
  return path.join(BANKS_DIR, `${code}.jsonl`);
}

/**
 * The only `systemPersistence` arm a live session may serve.
 *
 * A Stage 2 learning-block type is generated in two equated arms
 * (STAGE2_QUESTION_DESIGN §4.1.1): `consistent` holds one hidden system for the whole bank and is
 * the arm the block measures with, while a control arm re-draws the system every item so that
 * NOTHING is learnable in it — that is what makes it a contamination-floor control and what makes
 * it unfit to administer to a child.
 *
 * Three things keep a control arm out of a session, and this is the last of them. The control banks
 * are written outside `banks/` so no path built here can name one; `scripts/sync-exam-demos.mjs`
 * refuses to wire a bank that declares a control arm; and this check fails the whole pool if one
 * reaches the loader anyway. Fatal rather than filtered, for the reason
 * {@link ExamBankUnavailableError} already gives: on the path that serves questions to children,
 * silently continuing with a quietly different pool is the wrong default.
 */
const LIVE_SYSTEM_PERSISTENCE = 'consistent';

/** The arm an item declares, or null when its type is not a dual-arm type. */
function declaredPersistence(item: RawBankItem): string | null {
  const levers = (item.provenance as { levers?: unknown } | undefined)?.levers;
  if (typeof levers !== 'object' || levers === null) return null;
  const mode = (levers as { systemPersistence?: unknown }).systemPersistence;
  return typeof mode === 'string' ? mode : null;
}

async function loadAll(): Promise<RawBankItem[]> {
  if (cache) return cache;
  requireBanksDir();
  const items: RawBankItem[] = [];
  for (const code of BANK_TYPE_CODES) {
    const file = bankFile(code);
    let text: string;
    try {
      text = await readFile(file, 'utf8');
    } catch (cause) {
      throw new ExamBankUnavailableError(
        `${code} is a wired question type but its bank could not be read: ${file}. ` +
          SHIPPING_HINT,
        { cause },
      );
    }

    let parsed = 0;
    const lines = text.split('\n');
    for (let i = 0; i < lines.length; i += 1) {
      const trimmed = lines[i]!.trim();
      if (!trimmed) continue;
      let item: RawBankItem;
      try {
        item = JSON.parse(trimmed) as RawBankItem;
      } catch (cause) {
        throw new ExamBankUnavailableError(
          `${file}:${i + 1} is not valid JSON. A corrupt line silently shrinks the pool the ` +
            'adaptive engine draws from, so it is fatal rather than skipped.',
          { cause },
        );
      }
      const arm = declaredPersistence(item);
      if (arm !== null && arm !== LIVE_SYSTEM_PERSISTENCE) {
        throw new ExamBankUnavailableError(
          `${file}:${i + 1} declares systemPersistence="${arm}". That is a scrambled-system ` +
            'control arm, in which nothing is learnable by construction, and it must never be ' +
            'administered to a child. Control arms belong in ' +
            'research/exam-question-types/control-banks/, which nothing here reads.',
        );
      }
      items.push(item);
      parsed += 1;
    }
    if (parsed === 0) {
      throw new ExamBankUnavailableError(
        `${code} is a wired question type but its bank is empty: ${file}.`,
      );
    }
  }

  if (items.length === 0) {
    throw new ExamBankUnavailableError(
      `The item pool is empty after reading ${String(BANK_TYPE_CODES.length)} banks from ` +
        `${BANKS_DIR}.`,
    );
  }

  cache = items;
  return items;
}

/**
 * Whether a deployed instance can actually serve items, without loading the whole pool.
 *
 * `/api/health` reports this so a container that shipped without its banks fails its healthcheck
 * at deploy time, rather than at the moment a child opens the first question.
 */
export function examBankHealth(): { ready: boolean; detail: string } {
  try {
    requireBanksDir();
  } catch (error) {
    return { ready: false, detail: error instanceof Error ? error.message : String(error) };
  }

  const missing: string[] = [];
  for (const code of BANK_TYPE_CODES) {
    const file = bankFile(code);
    if (!existsSync(file) || statSync(file).size === 0) missing.push(code);
  }
  if (missing.length > 0) {
    return {
      ready: false,
      detail:
        `${String(missing.length)} of ${String(BANK_TYPE_CODES.length)} wired banks are missing ` +
        `or empty under ${BANKS_DIR}: ${missing.join(', ')}. ${SHIPPING_HINT}`,
    };
  }
  return {
    ready: true,
    detail: `${String(BANK_TYPE_CODES.length)} banks present under ${BANKS_DIR}`,
  };
}

/** Strip every server-only field (answer/scoring/provenance) + the on-disk demoPath. */
export function toServedItem(item: RawBankItem): ServedItem {
  return {
    itemId: item.itemId,
    typeCode: item.typeCode,
    domain: item.domain,
    difficulty: item.difficulty,
    ageBands: item.ageBands,
    content: item.content,
    syntheticOnly: true,
    validated: false,
  };
}

/**
 * A served item WITHOUT its `content` — everything the adaptive engine needs to
 * choose the next item (type, domain, difficulty, age bands) and nothing else.
 *
 * The full pool is ~3k items / ~5 MB of stimulus JSON across the wired banks and
 * grows with every new type, so the browser gets this index once per session and
 * then fetches only the single item it is about to render. `content` is kept as
 * an empty object so an index entry is structurally a `ServedItem` for the
 * engine's selection code.
 */
export type ServedItemIndex = Omit<ServedItem, 'content'> & {
  content: { optionCount?: number };
};

/**
 * How many options an item offers, when it offers a bounded choice at all.
 *
 * This is the ONE piece of stimulus shape the index carries, because the engine's burst policy has
 * to know whether a type is a single-tap choice BEFORE it selects an item, and by then the item's
 * content has not been fetched. A count is not an answer key and does not say which option is
 * correct, so it leaks nothing: the browser already receives the full option list for the one item
 * it is rendering.
 */
function indexOptionCount(item: RawBankItem): number | undefined {
  const options = (item.content as { options?: unknown } | undefined)?.options;
  return Array.isArray(options) && options.length > 0 ? options.length : undefined;
}

export function toIndexEntry(item: RawBankItem): ServedItemIndex {
  const optionCount = indexOptionCount(item);
  return {
    itemId: item.itemId,
    typeCode: item.typeCode,
    domain: item.domain,
    difficulty: item.difficulty,
    ageBands: item.ageBands,
    content: optionCount === undefined ? {} : { optionCount },
    syntheticOnly: true,
    validated: false,
  };
}

export interface ServedQuery {
  typeCode?: string | null;
  /** Target difficulty (1..20). When set, results are sorted nearest-first. */
  difficulty?: number | null;
  /** Item ids already served this session (never re-serve them). */
  exclude?: ReadonlySet<string> | undefined;
  limit?: number | null;
}

/**
 * Served items only (NO answer key). Optionally filtered by `typeCode` and sorted
 * by nearest `difficulty`, excluding already-seen ids.
 */
export async function getServedItems(query: ServedQuery = {}): Promise<ServedItem[]> {
  const all = await loadAll();
  let pool = all;
  if (query.typeCode) pool = pool.filter((i) => i.typeCode === query.typeCode);
  if (query.exclude && query.exclude.size > 0) {
    pool = pool.filter((i) => !query.exclude!.has(i.itemId));
  }

  let served = pool.map(toServedItem);
  if (typeof query.difficulty === 'number' && Number.isFinite(query.difficulty)) {
    const target = query.difficulty;
    served = [...served].sort(
      (a, b) =>
        Math.abs(a.difficulty - target) - Math.abs(b.difficulty - target) ||
        a.itemId.localeCompare(b.itemId),
    );
  }
  if (typeof query.limit === 'number' && query.limit > 0) served = served.slice(0, query.limit);
  return served;
}

/**
 * The whole selection index (no `content`, no answer key) — the pool the
 * adaptive engine runs `nextType`/`nextItem` over, fetched once per session.
 */
export async function getServedIndex(): Promise<ServedItemIndex[]> {
  const all = await loadAll();
  return all.map(toIndexEntry);
}

/** One served item WITH its stimulus content, still key-free. */
export async function getServedItem(itemId: string): Promise<ServedItem | null> {
  const all = await loadAll();
  const found = all.find((i) => i.itemId === itemId);
  return found ? toServedItem(found) : null;
}

/** Look up the FULL bank item (incl. the server-only answer key) by id. */
export async function findBankItem(itemId: string): Promise<RawBankItem | null> {
  const all = await loadAll();
  return all.find((i) => i.itemId === itemId) ?? null;
}
