import { existsSync } from 'node:fs';
import { readFile } from 'node:fs/promises';
import path from 'node:path';

import type { ServedItem } from '@gt-selection/exam-engine';

import { EXAM_TYPE_CODES } from './registry.generated';

/**
 * SERVER-ONLY bank loader (BUILD_PLAN §2/§6). Reads every wired structured bank
 * from `research/exam-question-types/banks/*.jsonl`, caches them in-process, and
 * exposes:
 *
 *  - {@link getServedItems} — items with `answer`/`scoring`/`provenance` STRIPPED
 *    (a `ServedItem` is all the browser may ever see); supports a `typeCode` +
 *    nearest-`difficulty` filter.
 *  - {@link findBankItem} — the FULL item incl. the server-only answer key, for
 *    server-authoritative verification in `/api/exam-submit`.
 *
 * The answer key, scoring mode, and provenance NEVER leave this module toward the
 * browser. Only route handlers (server) import this file. Born-synthetic only
 * (`syntheticOnly=true`, `validated=false`).
 */

/**
 * Every type code with a structured bank AND a protocol-compliant renderer.
 * Generated by `scripts/sync-exam-demos.mjs` — the served pool and the
 * `/api/exam-submit` verifier both widen automatically when a bank is added.
 */
export const BANK_TYPE_CODES: readonly string[] = EXAM_TYPE_CODES;
export type BankTypeCode = string;

/**
 * A full bank item as stored on disk. `answer` / `scoring` / `provenance` are
 * SERVER-ONLY. `correctKey` is a string option key (e.g. `"B"`) for keyed types
 * or a numeric option index for index-keyed types (e.g. VER-RELPAIR).
 */
export interface RawBankItem {
  itemId: string;
  typeCode: string;
  domain: ServedItem['domain'];
  difficulty: number;
  ageBands: ServedItem['ageBands'];
  content: Record<string, unknown>;
  /**
   * SERVER-ONLY. `correctKey` is a string option key (e.g. `"B"`) or a numeric
   * option index. Non-multiple-choice types carry the extra reference the
   * matching verifier needs (`targetRatio`/`tolerance`, `optimalValue`, …).
   */
  answer: {
    correctKey: string | number;
    distractorRationales?: unknown;
    [field: string]: unknown;
  };
  /** SERVER-ONLY. `rule` selects the verifier in `/api/exam-submit`. */
  scoring?: { mode?: string; rule?: string; [field: string]: unknown };
  provenance?: Record<string, unknown>;
  syntheticOnly: true;
  validated: false;
  /** On-disk relative demo path — NOT served (the runner derives it from typeCode). */
  demoPath?: string;
}

let cache: RawBankItem[] | null = null;

/** Resolve the banks dir robustly whether cwd is the app or the repo root. */
function resolveBanksDir(): string {
  const rel = ['research', 'exam-question-types', 'banks'];
  const candidates = [
    path.join(process.cwd(), ...rel),
    path.join(process.cwd(), '..', '..', ...rel),
    path.join(process.cwd(), '..', '..', '..', ...rel),
  ];
  for (const dir of candidates) if (existsSync(dir)) return dir;
  return candidates[0]!;
}

async function loadAll(): Promise<RawBankItem[]> {
  if (cache) return cache;
  const dir = resolveBanksDir();
  const items: RawBankItem[] = [];
  for (const code of BANK_TYPE_CODES) {
    let text: string;
    try {
      text = await readFile(path.join(dir, `${code}.jsonl`), 'utf8');
    } catch {
      continue; // a missing bank must not crash the whole battery
    }
    for (const line of text.split('\n')) {
      const trimmed = line.trim();
      if (!trimmed) continue;
      try {
        items.push(JSON.parse(trimmed) as RawBankItem);
      } catch {
        // skip a malformed line rather than fail the whole file
      }
    }
  }
  cache = items;
  return items;
}

/** Strip every server-only field (answer/scoring/provenance) + the on-disk demoPath. */
export function toServedItem(item: RawBankItem): ServedItem {
  return {
    itemId: item.itemId,
    typeCode: item.typeCode,
    domain: item.domain,
    difficulty: item.difficulty,
    ageBands: item.ageBands,
    content: item.content,
    syntheticOnly: true,
    validated: false,
  };
}

/**
 * A served item WITHOUT its `content` — everything the adaptive engine needs to
 * choose the next item (type, domain, difficulty, age bands) and nothing else.
 *
 * The full pool is ~3k items / ~5 MB of stimulus JSON across the wired banks and
 * grows with every new type, so the browser gets this index once per session and
 * then fetches only the single item it is about to render. `content` is kept as
 * an empty object so an index entry is structurally a `ServedItem` for the
 * engine's selection code.
 */
export type ServedItemIndex = Omit<ServedItem, 'content'> & { content: Record<string, never> };

export function toIndexEntry(item: RawBankItem): ServedItemIndex {
  return {
    itemId: item.itemId,
    typeCode: item.typeCode,
    domain: item.domain,
    difficulty: item.difficulty,
    ageBands: item.ageBands,
    content: {},
    syntheticOnly: true,
    validated: false,
  };
}

export interface ServedQuery {
  typeCode?: string | null;
  /** Target difficulty (1..20). When set, results are sorted nearest-first. */
  difficulty?: number | null;
  /** Item ids already served this session (never re-serve them). */
  exclude?: ReadonlySet<string> | undefined;
  limit?: number | null;
}

/**
 * Served items only (NO answer key). Optionally filtered by `typeCode` and sorted
 * by nearest `difficulty`, excluding already-seen ids.
 */
export async function getServedItems(query: ServedQuery = {}): Promise<ServedItem[]> {
  const all = await loadAll();
  let pool = all;
  if (query.typeCode) pool = pool.filter((i) => i.typeCode === query.typeCode);
  if (query.exclude && query.exclude.size > 0) {
    pool = pool.filter((i) => !query.exclude!.has(i.itemId));
  }

  let served = pool.map(toServedItem);
  if (typeof query.difficulty === 'number' && Number.isFinite(query.difficulty)) {
    const target = query.difficulty;
    served = [...served].sort(
      (a, b) =>
        Math.abs(a.difficulty - target) - Math.abs(b.difficulty - target) ||
        a.itemId.localeCompare(b.itemId),
    );
  }
  if (typeof query.limit === 'number' && query.limit > 0) served = served.slice(0, query.limit);
  return served;
}

/**
 * The whole selection index (no `content`, no answer key) — the pool the
 * adaptive engine runs `nextType`/`nextItem` over, fetched once per session.
 */
export async function getServedIndex(): Promise<ServedItemIndex[]> {
  const all = await loadAll();
  return all.map(toIndexEntry);
}

/** One served item WITH its stimulus content, still key-free. */
export async function getServedItem(itemId: string): Promise<ServedItem | null> {
  const all = await loadAll();
  const found = all.find((i) => i.itemId === itemId);
  return found ? toServedItem(found) : null;
}

/** Look up the FULL bank item (incl. the server-only answer key) by id. */
export async function findBankItem(itemId: string): Promise<RawBankItem | null> {
  const all = await loadAll();
  return all.find((i) => i.itemId === itemId) ?? null;
}
