// GENERATED FILE — DO NOT EDIT BY HAND.
// Regenerate with: node scripts/sync-exam-demos.mjs
//
// Every question type that has BOTH a structured bank
// (research/exam-question-types/banks/<CODE>.jsonl) AND a renderer demo that
// speaks the BUILD_PLAN §2 postMessage protocol. The sync script copies each
// wired demo to apps/web/public/exam-demos/ and emits this registry, which is
// the single source of truth for:
//
//   - the served-item pool (/api/exam-items)
//   - the server-side answer verifier (/api/exam-submit)
//   - the runner's type metadata + demo paths
//
// Wired: 48 types (fluid_reasoning 11 · quantitative 8 · spatial 18 · verbal 11).
// Adding a bank + compliant demo and re-running the sync is all it takes.

export type ExamRegistryDomain = 'fluid_reasoning' | 'verbal' | 'quantitative' | 'spatial';

/**
 * Which server-side verifier in `/api/exam-submit` grades this type. A type with
 * no verifier is never wired — it would score every child 0.
 */
export type ExamVerifier = 'keyed' | 'placement_tolerance' | 'constructed_value' | 'per_type';

export interface ExamRegistryEntry {
  typeCode: string;
  domain: ExamRegistryDomain;
  /** Human-facing type name (catalog `name`). */
  title: string;
  /** Short child-facing instruction shown under the activity frame. */
  blurb: string;
  /** Age bands the bank targets — a selection hint, not a hard filter. */
  ageBands: string[];
  itemCount: number;
  difficultyMin: number;
  difficultyMax: number;
  verifier: ExamVerifier;
  /**
   * Metric ids this demo puts on its ItemResult. Biases the engine's
   * metric-coverage type selection; the stop rule never depends on it.
   */
  metrics: string[];
}

export const EXAM_TYPE_REGISTRY: readonly ExamRegistryEntry[] = [
  {
    typeCode: 'CX-check-01',
    domain: 'fluid_reasoning',
    title: 'Check It Twice',
    blurb: 'A robot sorted things in a hurry with a few mistakes; the child may turn it in right away or review and fix it first - whether they check is the measure.',
    ageBands: ['2-3', '4-5', '6-8', 'K-1'],
    itemCount: 120,
    difficultyMin: 1.08,
    difficultyMax: 19.93,
    verifier: 'per_type',
    metrics: ['M-EFF', 'M-ENGAGE', 'M-EXPLORE', 'M-PATH', 'M-PERSIST', 'M-PLANFUL', 'M-RAPIDGUESS', 'M-REV', 'M-RT', 'M-RTFIRST'],
  },
  {
    typeCode: 'FLU-ANALOGY-01',
    domain: 'fluid_reasoning',
    title: 'Shape Morph',
    blurb: 'Make the third shape change the same way as the first pair.',
    ageBands: ['2-3', '4-5', '6-8'],
    itemCount: 120,
    difficultyMin: 1.04,
    difficultyMax: 19.96,
    verifier: 'keyed',
    metrics: ['M-ENGAGE', 'M-RAPIDGUESS', 'M-REV', 'M-RT', 'M-RTFIRST'],
  },
  {
    typeCode: 'FLU-CARPET-01',
    domain: 'fluid_reasoning',
    title: 'Pattern Carpet',
    blurb: 'The child continues a woven pattern by picking the tile that keeps every row (and column) progressing the same way.',
    ageBands: ['2-3', '4-5', '6-8', 'K-1'],
    itemCount: 120,
    difficultyMin: 1.04,
    difficultyMax: 19.96,
    verifier: 'keyed',
    metrics: ['M-ENGAGE', 'M-RAPIDGUESS', 'M-REV', 'M-RT', 'M-RTFIRST'],
  },
  {
    typeCode: 'FLU-CONCEPT-01',
    domain: 'fluid_reasoning',
    title: 'Mystery Gate',
    blurb: 'A magic gate opens only for figures that follow a secret rule; the child builds their own figures to test, watches which pass, then uses what they learned to…',
    ageBands: ['2-3', '4-5', '6-8'],
    itemCount: 120,
    difficultyMin: 1.11,
    difficultyMax: 19.93,
    verifier: 'per_type',
    metrics: ['M-EFF', 'M-ENGAGE', 'M-EXPLORE', 'M-HINT', 'M-PATH', 'M-RAPIDGUESS', 'M-RT', 'M-RTFIRST'],
  },
  {
    typeCode: 'FLU-DEDUCE-01',
    domain: 'fluid_reasoning',
    title: 'Clue Detective',
    blurb: 'A lineup of figures hides one culprit; clue cards flip over one at a time and the child crosses out every figure a clue rules out until only the answer is left.',
    ageBands: ['2-3', '4-5', '6-8'],
    itemCount: 120,
    difficultyMin: 1.04,
    difficultyMax: 19.93,
    verifier: 'keyed',
    metrics: ['M-EFF', 'M-ENGAGE', 'M-PATH', 'M-RAPIDGUESS', 'M-REV', 'M-RT', 'M-RTFIRST'],
  },
  {
    typeCode: 'FLU-GRIDCOPY-01',
    domain: 'fluid_reasoning',
    title: 'Copy the Change',
    blurb: 'A small example shows a grid changing; the child makes the same change happen on a new grid by tapping cells.',
    ageBands: ['2-3', '4-5', '6-8'],
    itemCount: 120,
    difficultyMin: 1.04,
    difficultyMax: 19.96,
    verifier: 'per_type',
    metrics: ['M-EFF', 'M-ENGAGE', 'M-PATH', 'M-RAPIDGUESS', 'M-REV', 'M-RT', 'M-RTFIRST'],
  },
  {
    typeCode: 'FLU-LADDER-01',
    domain: 'fluid_reasoning',
    title: 'Ranking Ladder',
    blurb: 'Clue cards each show one thing beating another; the child stacks all the clues together to work out the full winner-to-loser order and seats each character o…',
    ageBands: ['2-3', '4-5', '6-8'],
    itemCount: 120,
    difficultyMin: 1.04,
    difficultyMax: 19.96,
    verifier: 'keyed',
    metrics: ['M-ENGAGE', 'M-RAPIDGUESS', 'M-REV', 'M-RT', 'M-RTFIRST'],
  },
  {
    typeCode: 'FLU-MATRIX-01',
    domain: 'fluid_reasoning',
    title: 'Machine Matrix',
    blurb: 'Tap the tile that completes the pattern.',
    ageBands: ['2-3', '4-5', '6-8', 'K-1'],
    itemCount: 120,
    difficultyMin: 1.04,
    difficultyMax: 19.96,
    verifier: 'keyed',
    metrics: ['M-ENGAGE', 'M-RAPIDGUESS', 'M-REV', 'M-RT', 'M-RTFIRST'],
  },
  {
    typeCode: 'FLU-ODDPAIR-01',
    domain: 'fluid_reasoning',
    title: 'Odd Pair Out',
    blurb: 'Several before-and-after pairs all change in the same secret way except one; the child taps the pair whose change is different.',
    ageBands: ['2-3', '4-5', '6-8'],
    itemCount: 120,
    difficultyMin: 1.04,
    difficultyMax: 19.96,
    verifier: 'keyed',
    metrics: ['M-ENGAGE', 'M-RAPIDGUESS', 'M-REV', 'M-RT', 'M-RTFIRST'],
  },
  {
    typeCode: 'FLU-STACK-01',
    domain: 'fluid_reasoning',
    title: 'Stack the Panel',
    blurb: 'The child figures out how two panels in a row combine into the third, then picks the panel that correctly stacks the last row together.',
    ageBands: ['2-3', '4-5', '6-8'],
    itemCount: 120,
    difficultyMin: 1.04,
    difficultyMax: 19.96,
    verifier: 'keyed',
    metrics: ['M-ENGAGE', 'M-RAPIDGUESS', 'M-REV', 'M-RT', 'M-RTFIRST'],
  },
  {
    typeCode: 'FLU-VENN-01',
    domain: 'fluid_reasoning',
    title: 'Double Match',
    blurb: 'Two example groups each share a secret feature; the child picks the figure that belongs to BOTH groups at once.',
    ageBands: ['2-3', '4-5', '6-8'],
    itemCount: 120,
    difficultyMin: 1.04,
    difficultyMax: 19.96,
    verifier: 'keyed',
    metrics: ['M-ENGAGE', 'M-RAPIDGUESS', 'M-REV', 'M-RT', 'M-RTFIRST'],
  },
  {
    typeCode: 'GB-EXPLORE-01',
    domain: 'spatial',
    title: 'Explorer\'s Map',
    blurb: 'The child explores a foggy top-down world that reveals only what is nearby, then shows they built a map in their head by pointing back toward hidden landmark…',
    ageBands: ['2-3', '4-5', '6-8'],
    itemCount: 120,
    difficultyMin: 1,
    difficultyMax: 20,
    verifier: 'per_type',
    metrics: ['M-ENGAGE', 'M-EXPLORE', 'M-PATH', 'M-PLANFUL', 'M-RAPIDGUESS', 'M-REV', 'M-RT', 'M-RTFIRST'],
  },
  {
    typeCode: 'GB-FLAWFINDER-01',
    domain: 'verbal',
    title: 'Fib Finder',
    blurb: 'The child reads a short reason-and-claim and taps the part that does not make sense or the step that does not follow.',
    ageBands: ['2-3', '4-5', '6-8'],
    itemCount: 120,
    difficultyMin: 1,
    difficultyMax: 20,
    verifier: 'keyed',
    metrics: ['M-EXPLORE', 'M-HINT', 'M-IDEAFLU', 'M-PATH', 'M-PLANFUL', 'M-REV', 'M-RT', 'M-RTFIRST'],
  },
  {
    typeCode: 'GB-ROBOPATH-01',
    domain: 'spatial',
    title: 'Path Coder',
    blurb: 'The child lines up a sequence of move and turn arrows, then taps RUN so the robot walks the whole planned route to collect keys and reach the door.',
    ageBands: ['2-3', '4-5', '6-8'],
    itemCount: 120,
    difficultyMin: 1,
    difficultyMax: 20,
    verifier: 'per_type',
    metrics: ['M-EXPLORE', 'M-PATH', 'M-PERSIST', 'M-PLANFUL', 'M-RAPIDGUESS', 'M-REV', 'M-RT', 'M-RTFIRST'],
  },
  {
    typeCode: 'GB-TRACK-01',
    domain: 'spatial',
    title: 'Firefly Jars',
    blurb: 'The child watches which jars catch the glowing fireflies, keeps tracking them as the jars slide and swap places, then taps the jars that still hold a firefly.',
    ageBands: ['2-3', '4-5', '6-8'],
    itemCount: 120,
    difficultyMin: 1,
    difficultyMax: 20,
    verifier: 'per_type',
    metrics: ['M-EFF', 'M-ENGAGE', 'M-EXPLORE', 'M-PATH', 'M-PLANFUL', 'M-RAPIDGUESS', 'M-REV', 'M-RT', 'M-RTFIRST', 'M-SPAN'],
  },
  {
    typeCode: 'GB-WORDFORGE-01',
    domain: 'verbal',
    title: 'Word Forge',
    blurb: 'The child taps letter tiles to build as many real words as they can before the sand timer runs out.',
    ageBands: ['2-3', '4-5', '6-8'],
    itemCount: 120,
    difficultyMin: 1,
    difficultyMax: 20,
    verifier: 'per_type',
    metrics: ['M-ENGAGE', 'M-FLEX', 'M-IDEAFLU', 'M-PATH', 'M-PERSIST', 'M-PLANFUL', 'M-RAPIDGUESS', 'M-REV', 'M-RT', 'M-RTFIRST'],
  },
  {
    typeCode: 'GB-WORDLADDER-01',
    domain: 'verbal',
    title: 'Letter Climb',
    blurb: 'The child changes one letter at a time to climb from the start word to the goal word, each rung a real word.',
    ageBands: ['4-5', '6-8'],
    itemCount: 120,
    difficultyMin: 1,
    difficultyMax: 20,
    verifier: 'per_type',
    metrics: ['M-ENGAGE', 'M-IDEAFLU', 'M-PATH', 'M-PLANFUL', 'M-RAPIDGUESS', 'M-REV', 'M-RT', 'M-RTFIRST'],
  },
  {
    typeCode: 'QUANT-BALANCE-01',
    domain: 'quantitative',
    title: 'Balance Lab',
    blurb: 'The child adds figure weights until both sides of a scale are exactly level.',
    ageBands: ['2-3', '4-5', '6-8', 'K-1'],
    itemCount: 120,
    difficultyMin: 1,
    difficultyMax: 20,
    verifier: 'keyed',
    metrics: ['M-ENGAGE', 'M-RAPIDGUESS', 'M-REV', 'M-RT', 'M-RTFIRST'],
  },
  {
    typeCode: 'QUANT-DOTS-01',
    domain: 'quantitative',
    title: 'More or Fewer',
    blurb: 'The child taps the side that flashed more dots.',
    ageBands: ['2-3', 'K-1'],
    itemCount: 120,
    difficultyMin: 1,
    difficultyMax: 20,
    verifier: 'keyed',
    metrics: ['M-ENGAGE', 'M-RAPIDGUESS', 'M-REV', 'M-RT', 'M-RTFIRST'],
  },
  {
    typeCode: 'QUANT-FUNC-01',
    domain: 'quantitative',
    title: 'Machine Rule',
    blurb: 'Work out the rule and choose what the machine makes next.',
    ageBands: ['2-3', '4-5', '6-8', 'K-1'],
    itemCount: 120,
    difficultyMin: 1,
    difficultyMax: 20,
    verifier: 'keyed',
    metrics: ['M-ENGAGE', 'M-RAPIDGUESS', 'M-REV', 'M-RT', 'M-RTFIRST'],
  },
  {
    typeCode: 'QUANT-GRAPH-01',
    domain: 'quantitative',
    title: 'Story Graph',
    blurb: 'The child makes or chooses the graph that tells the same growing-quantity story as an animation.',
    ageBands: ['2-3', '4-5', '6-8'],
    itemCount: 140,
    difficultyMin: 1,
    difficultyMax: 20,
    verifier: 'keyed',
    metrics: ['M-ENGAGE', 'M-PATH', 'M-PLANFUL', 'M-RAPIDGUESS', 'M-REV', 'M-RT', 'M-RTFIRST'],
  },
  {
    typeCode: 'QUANT-MATRIX-01',
    domain: 'quantitative',
    title: 'Number Web',
    blurb: 'The child finds the quantity tile that completes every connection in a number web.',
    ageBands: ['2-3', '4-5', '6-8'],
    itemCount: 120,
    difficultyMin: 1,
    difficultyMax: 20,
    verifier: 'keyed',
    metrics: ['M-ENGAGE', 'M-RAPIDGUESS', 'M-REV', 'M-RT', 'M-RTFIRST'],
  },
  {
    typeCode: 'QUANT-MIX-01',
    domain: 'quantitative',
    title: 'Fair Share',
    blurb: 'The child changes two ingredient amounts so the new mix keeps the same taste.',
    ageBands: ['2-3', '4-5', '6-8'],
    itemCount: 120,
    difficultyMin: 1,
    difficultyMax: 20,
    verifier: 'per_type',
    metrics: ['M-ENGAGE', 'M-PAE', 'M-PATH', 'M-PLANFUL', 'M-PROPSTRAT', 'M-RAPIDGUESS', 'M-REV', 'M-RT', 'M-RTFIRST'],
  },
  {
    typeCode: 'QUANT-SERIES-01',
    domain: 'quantitative',
    title: 'Pattern Steps',
    blurb: 'Pick what continues the stepping pattern.',
    ageBands: ['2-3', '4-5', '6-8', 'K-1'],
    itemCount: 120,
    difficultyMin: 1,
    difficultyMax: 20,
    verifier: 'keyed',
    metrics: ['M-ENGAGE', 'M-RAPIDGUESS', 'M-REV', 'M-RT', 'M-RTFIRST'],
  },
  {
    typeCode: 'QUANT-WORD-01',
    domain: 'quantitative',
    title: 'Story Model',
    blurb: 'The child rebuilds a silent quantity story with objects or bars and uses the model to find what is missing.',
    ageBands: ['2-3', '4-5', '6-8'],
    itemCount: 220,
    difficultyMin: 1,
    difficultyMax: 20,
    verifier: 'keyed',
    metrics: ['M-ENGAGE', 'M-PATH', 'M-PLANFUL', 'M-PROG', 'M-RAPIDGUESS', 'M-REV', 'M-RT', 'M-RTFIRST'],
  },
  {
    typeCode: 'SPA-FOLDNET-01',
    domain: 'spatial',
    title: 'Fold-the-Net',
    blurb: 'Fold the flat net into a box and find the opposite face.',
    ageBands: ['2-3', '4-5', '6-8'],
    itemCount: 100,
    difficultyMin: 1,
    difficultyMax: 20,
    verifier: 'keyed',
    metrics: ['M-EXPLORE', 'M-RAPIDGUESS', 'M-REV', 'M-RT', 'M-RTFIRST'],
  },
  {
    typeCode: 'SPA-HIDDENCUBE-01',
    domain: 'spatial',
    title: 'X-Ray Cubes',
    blurb: 'A pile of blocks is shown from one corner; the child works out how many blocks there are in total, including the ones hidden behind and underneath, and dials…',
    ageBands: ['2-3', '4-5', '6-8'],
    itemCount: 140,
    difficultyMin: 1,
    difficultyMax: 20,
    verifier: 'per_type',
    metrics: ['M-ENGAGE', 'M-EXPLORE', 'M-RAPIDGUESS', 'M-REV', 'M-RT', 'M-RTFIRST'],
  },
  {
    typeCode: 'SPA-MAZE-01',
    domain: 'spatial',
    title: 'Plan-the-Path',
    blurb: 'The child guides a character from start to exit through a maze, and in harder items plans the shortest route that also collects required gems.',
    ageBands: ['2-3', '4-5', '6-8'],
    itemCount: 100,
    difficultyMin: 1,
    difficultyMax: 20,
    verifier: 'per_type',
    metrics: ['M-EXPLORE', 'M-PATH', 'M-RAPIDGUESS', 'M-REV', 'M-RT', 'M-RTFIRST'],
  },
  {
    typeCode: 'SPA-PICKFOLD-01',
    domain: 'spatial',
    title: 'Which Fold Made It?',
    blurb: 'Shown a paper before and after a single fold, the child works out which crease and direction produced the result by choosing or performing the fold.',
    ageBands: ['2-3', '4-5'],
    itemCount: 100,
    difficultyMin: 1,
    difficultyMax: 20,
    verifier: 'keyed',
    metrics: ['M-EXPLORE', 'M-RAPIDGUESS', 'M-REV', 'M-RT', 'M-RTFIRST'],
  },
  {
    typeCode: 'SPA-PIPES-01',
    domain: 'spatial',
    title: 'Path Connect',
    blurb: 'The child rotates road or pipe tiles in a grid so a single connected path links the start to the goal, and in harder items visits required stops in the fewes…',
    ageBands: ['2-3', '4-5', '6-8'],
    itemCount: 100,
    difficultyMin: 1,
    difficultyMax: 20,
    verifier: 'per_type',
    metrics: ['M-EXPLORE', 'M-RAPIDGUESS', 'M-REV', 'M-RT', 'M-RTFIRST'],
  },
  {
    typeCode: 'SPA-PUNCH-01',
    domain: 'spatial',
    title: 'Fold & Punch',
    blurb: 'The child folds a paper one or more times, punches a hole, then predicts where all the holes will be once it is unfolded.',
    ageBands: ['2-3', '4-5', '6-8'],
    itemCount: 140,
    difficultyMin: 1,
    difficultyMax: 20,
    verifier: 'per_type',
    metrics: ['M-ENGAGE', 'M-PROG', 'M-RAPIDGUESS', 'M-REV', 'M-RT', 'M-RTFIRST'],
  },
  {
    typeCode: 'SPA-ROLL-01',
    domain: 'spatial',
    title: 'Rolling Cube',
    blurb: 'Track a cube as it tips along a path.',
    ageBands: ['2-3', '4-5', '6-8'],
    itemCount: 100,
    difficultyMin: 1,
    difficultyMax: 20,
    verifier: 'keyed',
    metrics: ['M-EXPLORE', 'M-PATH', 'M-RAPIDGUESS', 'M-REV', 'M-RT', 'M-RTFIRST'],
  },
  {
    typeCode: 'SPA-SCENE-01',
    domain: 'spatial',
    title: 'What the Robot Sees',
    blurb: 'A robot sits at one side of a little scene; the child rebuilds what the robot sees by ordering the objects left-to-right from the robot\'s point of view.',
    ageBands: ['2-3', '4-5', '6-8'],
    itemCount: 140,
    difficultyMin: 1,
    difficultyMax: 20,
    verifier: 'per_type',
    metrics: ['M-ENGAGE', 'M-EXPLORE', 'M-RAPIDGUESS', 'M-REV', 'M-RT', 'M-RTFIRST'],
  },
  {
    typeCode: 'SPA-SHADOW-01',
    domain: 'spatial',
    title: 'Shadow Play',
    blurb: 'A light shines on a 3D object and the child works out the flat shadow it throws on the wall - or turns the object until its shadow matches a target.',
    ageBands: ['2-3', '4-5', '6-8'],
    itemCount: 100,
    difficultyMin: 1,
    difficultyMax: 20,
    verifier: 'keyed',
    metrics: ['M-EXPLORE', 'M-RAPIDGUESS', 'M-REV', 'M-RT', 'M-RTFIRST'],
  },
  {
    typeCode: 'SPA-TANGRAM-01',
    domain: 'spatial',
    title: 'Shape-Fill Form Board',
    blurb: 'The child drags loose puzzle pieces, rotating them when needed, to completely fill a target silhouette.',
    ageBands: ['2-3', '4-5', '6-8'],
    itemCount: 100,
    difficultyMin: 1,
    difficultyMax: 20,
    verifier: 'per_type',
    metrics: ['M-EXPLORE', 'M-RAPIDGUESS', 'M-REV', 'M-RT', 'M-RTFIRST'],
  },
  {
    typeCode: 'SPA-VIEW-01',
    domain: 'spatial',
    title: 'What Do They See',
    blurb: 'The child figures out what a character sees from where it stands, by moving the character or pointing a dial toward a target from the character\'s viewpoint.',
    ageBands: ['2-3', '4-5', '6-8'],
    itemCount: 140,
    difficultyMin: 1.03,
    difficultyMax: 19.97,
    verifier: 'per_type',
    metrics: ['M-ENGAGE', 'M-EXPLORE', 'M-RAPIDGUESS', 'M-REV', 'M-RT', 'M-RTFIRST'],
  },
  {
    typeCode: 'SPA-XPLANE-01',
    domain: 'spatial',
    title: 'Place the Slice',
    blurb: 'Given the exact 2D shape wanted, the child positions and tilts a cutting plane through a 3D solid so the cut face becomes that shape.',
    ageBands: ['4-5', '6-8'],
    itemCount: 140,
    difficultyMin: 1.03,
    difficultyMax: 19.97,
    verifier: 'per_type',
    metrics: ['M-EFF', 'M-ENGAGE', 'M-EXPLORE', 'M-PATH', 'M-RAPIDGUESS', 'M-REV', 'M-RT', 'M-RTFIRST'],
  },
  {
    typeCode: 'SPA-XSCAN-01',
    domain: 'spatial',
    title: 'Scan Stacker',
    blurb: 'The child scrubs through a stack of 2D cross-section slices (like a medical scan) and works out which 3D solid would produce them.',
    ageBands: ['4-5', '6-8'],
    itemCount: 140,
    difficultyMin: 1.03,
    difficultyMax: 19.97,
    verifier: 'keyed',
    metrics: ['M-ENGAGE', 'M-EXPLORE', 'M-EXPLOREMOVES', 'M-RAPIDGUESS', 'M-REV', 'M-RT', 'M-RTFIRST'],
  },
  {
    typeCode: 'VER-CLOZE-01',
    domain: 'verbal',
    title: 'Fill the Gap',
    blurb: 'Choose the word that best completes the sentence.',
    ageBands: ['2-3', '4-5', '6-8'],
    itemCount: 100,
    difficultyMin: 1,
    difficultyMax: 20,
    verifier: 'keyed',
    metrics: ['M-EXPLORE', 'M-REV', 'M-RT', 'M-RTFIRST'],
  },
  {
    typeCode: 'VER-EVIDENCE-01',
    domain: 'verbal',
    title: 'Proof Hunt',
    blurb: 'Answer a question about a short story, then tap the exact part that proves your answer.',
    ageBands: ['2-3', '4-5', '6-8'],
    itemCount: 120,
    difficultyMin: 1,
    difficultyMax: 20,
    verifier: 'per_type',
    metrics: ['M-PATH', 'M-REV', 'M-RT', 'M-RTFIRST', 'M-VOCABLVL'],
  },
  {
    typeCode: 'VER-POLYSEME-01',
    domain: 'verbal',
    title: 'Two Meanings',
    blurb: 'Read a sentence containing a word with two meanings, then tap the picture showing the meaning the sentence points to.',
    ageBands: ['2-3', '4-5', '6-8'],
    itemCount: 100,
    difficultyMin: 1,
    difficultyMax: 20,
    verifier: 'keyed',
    metrics: ['M-EXPLORE', 'M-REV', 'M-RT', 'M-RTFIRST'],
  },
  {
    typeCode: 'VER-RELPAIR-01',
    domain: 'verbal',
    title: 'Relation Match',
    blurb: 'Find the pair of words that relate the same way.',
    ageBands: ['2-3', '4-5', '6-8', 'K-1'],
    itemCount: 100,
    difficultyMin: 1,
    difficultyMax: 20,
    verifier: 'keyed',
    metrics: ['M-EXPLORE', 'M-REV', 'M-RT', 'M-RTFIRST'],
  },
  {
    typeCode: 'VER-SENSE-01',
    domain: 'verbal',
    title: 'Sentence Sense',
    blurb: 'Drag the scrambled word cards into order to build the sentence that makes sense - not the silly one that breaks the rules of the world.',
    ageBands: ['2-3', '4-5', '6-8'],
    itemCount: 120,
    difficultyMin: 1,
    difficultyMax: 20,
    verifier: 'per_type',
    metrics: ['M-INFDEPTH', 'M-PATH', 'M-REV', 'M-RT', 'M-RTFIRST', 'M-VOCABLVL'],
  },
  {
    typeCode: 'VER-SEQUENCE-01',
    domain: 'verbal',
    title: 'Story Order',
    blurb: 'Put the mixed-up parts of a story in the right order, then choose what happens next.',
    ageBands: ['2-3', '4-5', '6-8', 'K-1'],
    itemCount: 100,
    difficultyMin: 1,
    difficultyMax: 20,
    verifier: 'keyed',
    metrics: ['M-EXPLORE', 'M-REV', 'M-RT', 'M-RTFIRST'],
  },
  {
    typeCode: 'VER-SORTBOT-01',
    domain: 'verbal',
    title: 'Sorting Robot',
    blurb: 'Watch a robot drop a few example pictures or words into its IN bin or OUT bin, figure out the hidden category rule, then sort new items IN or OUT yourself.',
    ageBands: ['2-3', '4-5', '6-8', 'K-1'],
    itemCount: 100,
    difficultyMin: 1,
    difficultyMax: 20,
    verifier: 'keyed',
    metrics: ['M-EXPLORE', 'M-REV', 'M-RT', 'M-RTFIRST'],
  },
  {
    typeCode: 'WM-bind-01',
    domain: 'spatial',
    title: 'Home Again (object-location binding)',
    blurb: 'Watch which animal lives in which house, then after they come out and shuffle put each animal back in its own house.',
    ageBands: ['2-3', '4-5', '6-8', 'K-1'],
    itemCount: 120,
    difficultyMin: 1.04,
    difficultyMax: 19.96,
    verifier: 'per_type',
    metrics: ['M-DIFFREACH', 'M-ENGAGE', 'M-LAPSE', 'M-PATH', 'M-PLANFUL', 'M-RAPIDGUESS', 'M-REV', 'M-RT', 'M-RTFIRST', 'M-RTVAR', 'M-SPAN'],
  },
  {
    typeCode: 'WM-bubble-01',
    domain: 'verbal',
    title: 'Bubble Pop Memory (n-back / dual n-back)',
    blurb: 'Bubbles float up one at a time showing a picture, and the child taps POP whenever the current bubble matches the one from n bubbles ago; a dual mode adds a s…',
    ageBands: ['2-3', '4-5', '6-8'],
    itemCount: 120,
    difficultyMin: 1,
    difficultyMax: 20,
    verifier: 'per_type',
    metrics: ['M-ENGAGE', 'M-RAPIDGUESS', 'M-REV', 'M-RT', 'M-RTFIRST', 'M-RTVAR', 'M-UPDATECOST', 'M-VOCABLVL'],
  },
  {
    typeCode: 'WM-corsi-01',
    domain: 'spatial',
    title: 'Firefly Trail (spatial span)',
    blurb: 'Fireflies (tiles) light up one-by-one in a growing sequence and the child taps them back in the same order, or in reverse.',
    ageBands: ['2-3', '4-5', '6-8', 'K-1'],
    itemCount: 120,
    difficultyMin: 1.04,
    difficultyMax: 19.96,
    verifier: 'per_type',
    metrics: ['M-DIFFREACH', 'M-ENGAGE', 'M-LAPSE', 'M-PATH', 'M-PLANFUL', 'M-RAPIDGUESS', 'M-REV', 'M-RT', 'M-RTFIRST', 'M-RTVAR', 'M-SPAN'],
  },
] as const;

/** Types with a bank but no servable demo, and why. */
export const EXAM_BLOCKED_TYPES: readonly { typeCode: string; reason: string }[] = [
  { typeCode: 'CX-achieve-02', reason: 'blocked by qa/NOT_SERVABLE.json: Proven answer leak: content.apparatus ships the closed-form outcome model (base, per-level weights, interaction bonus). Evaluating it over content.conclusion.options and taking the argmax recovers the correct key on 120/120 items WITHOUT running a single trial.' },
] as const;

/** Every wired type code, in registry (alphabetical) order. */
export const EXAM_TYPE_CODES: readonly string[] = EXAM_TYPE_REGISTRY.map((t) => t.typeCode);
