/**
 * THROWAWAY ANALYSIS ARTIFACT — evidence for ITEM_SELECTION_BRACKETING_ANALYSIS.md. NOT production
 * code, NOT an entry point, and deliberately NOT under `scripts/`, so it is outside
 * `scripts/tsconfig.json` and is not typechecked or linted by `pnpm verify`.
 *
 * It is committed for one reason: E-095's figures could not be regenerated by anyone because the
 * sweep that produced them was never committed and its parameters were never recorded. Leaving a
 * second set of unreproducible numbers in the register would repeat that mistake.
 *
 * If any option in §5 of the analysis is commissioned, this should be REPLACED by a committed Phase 1
 * harness built the way `scripts/exam-learning-block-harness.ts` is built — separate responder,
 * readout and targeting parameters, a cohort driver, and a null control arm — not extended.
 *
 * Answers, all born-synthetic:
 *   A. Where is Fisher information maximised, under this repo's own information formulas?
 *   B. Where does this repo's staircase settle, relative to a child's true ability?
 *   C-F. What do alternative Phase 1 selection rules do to bias / RMSE / SE / length, on the real
 *        bank with a STOCHASTIC responder (the shipped Phase 1 harness responder is deterministic)?
 *
 * Run from the repo root: pnpm tsx docs/architecture/bracketing-analysis.throwaway.ts   (~2.5 min)
 */
import {
  loadRealBanks,
  type RealBanks,
  type TrueTheta,
} from '../../packages/exam-engine/src/testing/real-bank';
import { GRADE_BAND_SEED } from '../../packages/exam-engine/src/config';
import { isDone } from '../../packages/exam-engine/src/done';
import { nextItem, nextType } from '../../packages/exam-engine/src/selection';
import { startState } from '../../packages/exam-engine/src/state';
import { update } from '../../packages/exam-engine/src/update';
import { hashUnit } from '../../packages/exam-engine/src/rng';
import {
  AREAS,
  type AgeBand,
  type Area,
  type EngineConfig,
  type MetricId,
  type ScoredItem,
  type ServedItem,
  type SessionState,
} from '../../packages/exam-engine/src/types';
import {
  deriveAbilityEstimate,
  abilityStandardError,
} from '../../packages/exam-scoring/src/ability';
import type { AbilityFitOptions } from '../../packages/exam-scoring/src/ability';
import type { ScoredItem as ScoringItem } from '../../packages/exam-scoring/src/types';

const SLOPE = 1.0;
const PRIOR_SD = 6.0;
const SCALE_MIN = 1;
const SCALE_MAX = 20;
const FIVE_OPTION = 0.2;
const Z95 = 1.96;

const FIT: AbilityFitOptions = { slope: SLOPE, priorSd: PRIOR_SD, min: SCALE_MIN, max: SCALE_MAX };

function clamp(x: number, lo: number, hi: number): number {
  return Math.min(hi, Math.max(lo, x));
}
function mean(xs: readonly number[]): number {
  return xs.length === 0 ? NaN : xs.reduce((a, b) => a + b, 0) / xs.length;
}
function sd(xs: readonly number[]): number {
  if (xs.length < 2) return NaN;
  const m = mean(xs);
  return Math.sqrt(xs.reduce((a, b) => a + (b - m) ** 2, 0) / (xs.length - 1));
}
function rmse(errs: readonly number[]): number {
  return Math.sqrt(mean(errs.map((e) => e * e)));
}
function f(x: number, p = 3): string {
  return Number.isFinite(x) ? x.toFixed(p) : 'n/a';
}

// ---------------------------------------------------------------------------
// A. Information geometry
// ---------------------------------------------------------------------------

/** Plain 1PL item information, exactly `abilityStandardError`'s per-item term. */
function info1PL(theta: number, b: number, a = SLOPE): number {
  const p = 1 / (1 + Math.exp(-a * (theta - b)));
  return a * a * p * (1 - p);
}

/** Item information with a lower asymptote, exactly `estimateLearningCurve`'s per-trial term. */
function infoWithFloor(theta: number, b: number, c: number, a = SLOPE): number {
  const star = 1 / (1 + Math.exp(-a * (theta - b)));
  const p = c + (1 - c) * star;
  return (a * a * (p - c) * (p - c) * (1 - p)) / ((1 - c) * (1 - c) * p);
}

function argmaxOffset(c: number): { offset: number; info: number; pCorrect: number } {
  const theta = 10;
  let best = { offset: 0, info: -1, pCorrect: 0 };
  for (let o = -4; o <= 4; o += 0.001) {
    const b = theta + o;
    const i = c === 0 ? info1PL(theta, b) : infoWithFloor(theta, b, c);
    if (i > best.info) {
      const star = 1 / (1 + Math.exp(-SLOPE * (theta - b)));
      best = { offset: Math.round(o * 1000) / 1000, info: i, pCorrect: c + (1 - c) * star };
    }
  }
  return best;
}

function sectionA(): void {
  console.log('\n## A. Where is item information maximised?\n');
  console.log(
    'Offset = item difficulty minus ability (negative = easier than the child). Information from\n' +
      "this repo's own formulas: `abilityStandardError` for c = 0, `estimateLearningCurve` for c > 0.\n",
  );

  console.log('| assumed guessing floor c | info-maximising offset | P(correct) there |');
  console.log('| --- | --- | --- |');
  for (const c of [0, 1 / 6, FIVE_OPTION, 0.25]) {
    const best = argmaxOffset(c);
    const label = c === 0 ? '0 (what ability.ts assumes)' : f(c, 3);
    console.log(`| ${label} | ${best.offset >= 0 ? '+' : ''}${f(best.offset, 2)} | ${f(best.pCorrect, 3)} |`);
  }

  console.log('\n### Relative efficiency of aiming off-centre (c = 0, the shipped standing fit)\n');
  console.log('| offset from ability | information | relative to centre | items for same information |');
  console.log('| --- | --- | --- | --- |');
  const centre = info1PL(10, 10);
  for (const o of [0, 0.5, 1, 1.5, 2, 2.5, 3, 4]) {
    const i = info1PL(10, 10 + o);
    console.log(
      `| ±${f(o, 1)} | ${f(i, 4)} | ${f(i / centre, 3)} | ${f(centre / i, 2)}x |`,
    );
  }

  console.log('\n### Same, with a real five-option floor (c = 0.2)\n');
  console.log('| offset from ability | information | relative to the c=0.2 optimum |');
  console.log('| --- | --- | --- |');
  const best02 = argmaxOffset(FIVE_OPTION);
  for (const o of [-2, -1, -0.5, -0.27, 0, 0.5, 1, 2, 3]) {
    const i = infoWithFloor(10, 10 + o, FIVE_OPTION);
    console.log(`| ${o >= 0 ? '+' : ''}${f(o, 2)} | ${f(i, 4)} | ${f(i / best02.info, 3)} |`);
  }
}

// ---------------------------------------------------------------------------
// B. Staircase equilibrium
// ---------------------------------------------------------------------------

/**
 * Where an up/down staircase settles: the difficulty at which expected drift is zero.
 * P * upStep = (1 - P) * downStep  =>  P = downStep / (upStep + downStep).
 * Then invert the response curve to get the offset from the child's true ability.
 */
function equilibriumOffset(upStep: number, downStep: number, c: number): { p: number; offset: number } {
  const p = downStep / (upStep + downStep);
  const star = (p - c) / (1 - c);
  if (star <= 0 || star >= 1) return { p, offset: NaN };
  // p = c + (1-c) sigma(a(theta - b)) => theta - b = ln(star/(1-star))/a => b - theta = -that
  const offset = -Math.log(star / (1 - star)) / SLOPE;
  return { p, offset };
}

function sectionB(): void {
  console.log('\n## B. Where does the staircase settle relative to true ability?\n');
  console.log(
    'A staircase settles where expected drift is zero, i.e. at the difficulty the child succeeds on\n' +
      'with probability downStep/(upStep+downStep). `nearMissSoften: 0.5` shrinks WRONG steps only,\n' +
      'so the up and down steps are asymmetric and that probability is below 0.5.\n',
  );
  console.log('| down/up step ratio | implied P(correct) at equilibrium | offset of the settled estimate from true ability |');
  console.log('| --- | --- | --- |');
  for (const ratio of [1.0, 0.9, 0.75, 0.6, 0.5]) {
    for (const c of [0, FIVE_OPTION]) {
      const e = equilibriumOffset(1, ratio, c);
      console.log(
        `| ${f(ratio, 2)} (c = ${f(c, 1)}) | ${f(e.p, 3)} | ${e.offset >= 0 ? '+' : ''}${f(e.offset, 2)} |`,
      );
    }
  }
}

// ---------------------------------------------------------------------------
// C. Phase 1 selection-rule comparison, stochastic responder, real bank
// ---------------------------------------------------------------------------

type Rule = 'centre' | 'endpoint-alt' | 'endpoint-upper' | 'offset-minus' | 'fit-centre' | 'fit-centre-c';

/** Corrected 1PL location fit WITH a guessing floor — what `ability.ts` does not have. */
function fitWithFloor(items: readonly { difficulty: number; score: number }[], c: number): number | null {
  if (items.length === 0) return null;
  const grad = (theta: number): number => {
    let g = 0;
    for (const it of items) {
      const b = clamp(it.difficulty, SCALE_MIN, SCALE_MAX);
      const star = 1 / (1 + Math.exp(-SLOPE * (theta - b)));
      const p = c + (1 - c) * star;
      if (p <= 0 || p >= 1) continue;
      g += (SLOPE * (p - c) * (clamp(it.score, 0, 1) - p)) / (p * (1 - c));
    }
    g -= (theta - (SCALE_MIN + SCALE_MAX) / 2) / (PRIOR_SD * PRIOR_SD);
    return g;
  };
  let lo = SCALE_MIN;
  let hi = SCALE_MAX;
  if (grad(lo) <= 0) return lo;
  if (grad(hi) >= 0) return hi;
  for (let i = 0; i < 60; i += 1) {
    const mid = (lo + hi) / 2;
    if (grad(mid) > 0) lo = mid;
    else hi = mid;
  }
  return (lo + hi) / 2;
}

interface ChildResult {
  items: number;
  hitCap: boolean;
  /** Per-area error of the engine's reported staircase standing level. */
  staircaseErr: number[];
  /** Per-area error of the fitted ability (the estimator the scorer / debug panel use). */
  fitErr: number[];
  /** Per-area error of a guessing-corrected fit over the same trace. */
  fitCErr: number[];
  /** Per-area final SE of the shipped fit. */
  finalSe: number[];
}

function mulberry32(a: number): () => number {
  let s = a;
  return () => {
    s |= 0;
    s = (s + 0x6d2b79f5) | 0;
    let t = Math.imul(s ^ (s >>> 15), 1 | s);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** Stochastic responder: 1PL with an explicit guessing floor. Metric bag mirrors the real harness. */
function respond(
  served: ServedItem,
  real: RealBanks,
  trueTheta: TrueTheta,
  c: number,
  rng: () => number,
): ScoredItem {
  const theta = trueTheta[served.domain];
  const star = 1 / (1 + Math.exp(-SLOPE * (theta - served.difficulty)));
  const p = c + (1 - c) * star;
  const correct = rng() < p;
  const score = correct ? 1 : 0;
  const errType = correct ? 1 : clamp(1 - (served.difficulty - theta) / 5, 0, 1);
  const rtMs = Math.round(800 + 55 * served.difficulty + (correct ? 0 : 260));

  const spec = real.catalog.get(served.typeCode);
  const metrics: Record<MetricId, number> = {};
  for (const metricId of spec?.perItem ?? []) {
    if (metricId === 'M-RT') metrics[metricId] = rtMs;
    else if (metricId === 'M-RTFIRST') metrics[metricId] = Math.round(rtMs * 0.35);
    else if (metricId === 'M-REV') metrics[metricId] = correct ? 0 : 1;
    else if (metricId === 'M-ACC') metrics[metricId] = score;
    else if (metricId === 'M-ERRTYPE') metrics[metricId] = errType;
    else metrics[metricId] = Math.round(hashUnit(0x5eed, `${metricId}:${served.itemId}`) * 1000) / 1000;
  }
  metrics['M-ACC'] = score;
  metrics['M-ERRTYPE'] = errType;
  if (correct) metrics['M-DIFFREACH'] = served.difficulty;

  const stimulus = real.stimulus.get(served.itemId);
  return {
    itemId: served.itemId,
    typeCode: served.typeCode,
    domain: served.domain,
    response: { selectedKey: correct ? 'A' : 'B' },
    metrics,
    telemetry: [],
    correct,
    score,
    difficulty: served.difficulty,
    ...(stimulus ? { stimulus } : {}),
  };
}

/** The aim for the next item, per rule. */
function aimFor(
  rule: Rule,
  state: SessionState,
  area: Area,
  areaTrace: readonly ScoredItem[],
  gradeBand: AgeBand,
): number {
  const staircase = state.areas[area].difficulty;
  if (rule === 'centre') return staircase;

  const scoring = areaTrace as unknown as readonly ScoringItem[];
  const est = deriveAbilityEstimate(scoring, FIT);
  if (est === null) return GRADE_BAND_SEED[gradeBand];
  const se = abilityStandardError(est, scoring, FIT) ?? PRIOR_SD;

  switch (rule) {
    case 'endpoint-alt': {
      // Alternate low edge / high edge: the literal "present questions at the ends of the SE range".
      const high = areaTrace.length % 2 === 0;
      return clamp(est + (high ? +Z95 * se : -Z95 * se), SCALE_MIN, SCALE_MAX);
    }
    case 'endpoint-upper':
      return clamp(est + Z95 * se, SCALE_MIN, SCALE_MAX);
    case 'offset-minus':
      // The information-maximising offset under a real five-option floor.
      return clamp(est - 0.27, SCALE_MIN, SCALE_MAX);
    case 'fit-centre':
      return clamp(est, SCALE_MIN, SCALE_MAX);
    case 'fit-centre-c': {
      const corrected = fitWithFloor(areaTrace, FIVE_OPTION);
      return clamp(corrected ?? est, SCALE_MIN, SCALE_MAX);
    }
    default:
      return staircase;
  }
}

const APP_CONFIG: Partial<EngineConfig> = {
  minItemsPerArea: 4,
  evenSpreadTolerance: 1,
  stabilityWindow: 4,
  stabilitySd: 1.5,
  stabilityDrift: 1.0,
  difficultyWindow: 4,
  accWindowSize: 8,
  estWindowSize: 8,
  hardItemCap: 40,
};

function runChild(
  rule: Rule,
  gradeBand: AgeBand,
  trueTheta: TrueTheta,
  real: RealBanks,
  c: number,
  seed: number,
  capOverride?: number,
): ChildResult {
  const rng = mulberry32(seed);
  let state = startState(gradeBand, { ...APP_CONFIG, ...(capOverride ? { hardItemCap: capOverride } : {}) });
  const byArea = new Map<Area, ScoredItem[]>(AREAS.map((a) => [a, []]));

  while (!isDone(state)) {
    const typeCode = nextType(state, real.banks);
    if (typeCode === null) break;
    const type = real.banks.types.find((t) => t.typeCode === typeCode);
    if (!type) break;
    const area = type.domain;

    const aim = aimFor(rule, state, area, byArea.get(area) ?? [], gradeBand);
    // Override ONLY the aim handed to selection; the engine's own state update is untouched.
    const aimed: SessionState = {
      ...state,
      areas: { ...state.areas, [area]: { ...state.areas[area], difficulty: aim } },
    };

    let served: ServedItem;
    try {
      served = nextItem(aimed, typeCode, real.banks);
    } catch {
      break;
    }
    const scored = respond(served, real, trueTheta, c, rng);
    byArea.get(area)?.push(scored);
    state = update(state, scored);
  }

  const staircaseErr: number[] = [];
  const fitErr: number[] = [];
  const fitCErr: number[] = [];
  const finalSe: number[] = [];
  for (const area of AREAS) {
    const trace = byArea.get(area) ?? [];
    const truth = trueTheta[area];
    staircaseErr.push(state.areas[area].difficulty - truth);
    const scoring = trace as unknown as readonly ScoringItem[];
    const est = deriveAbilityEstimate(scoring, FIT);
    fitErr.push(est === null ? NaN : est - truth);
    const se = est === null ? NaN : (abilityStandardError(est, scoring, FIT) ?? NaN);
    finalSe.push(se);
    const corrected = fitWithFloor(trace, FIVE_OPTION);
    fitCErr.push(corrected === null ? NaN : corrected - truth);
  }

  return {
    items: state.itemsServed,
    hitCap: state.itemsServed >= (capOverride ?? APP_CONFIG.hardItemCap ?? 40),
    staircaseErr,
    fitErr,
    fitCErr,
    finalSe,
  };
}

interface ArmSummary {
  rule: Rule;
  n: number;
  items: number;
  capRate: number;
  staircaseBias: number;
  staircaseRmse: number;
  fitBias: number;
  fitRmse: number;
  fitCBias: number;
  fitCRmse: number;
  meanSe: number;
}

function runCohort(
  rule: Rule,
  real: RealBanks,
  c: number,
  children: number,
  capOverride?: number,
): ArmSummary {
  const rng = mulberry32(4242);
  const sc: number[] = [];
  const ft: number[] = [];
  const ftc: number[] = [];
  const ses: number[] = [];
  const lens: number[] = [];
  let caps = 0;

  for (let i = 0; i < children; i += 1) {
    // One true ability per area, drawn uniformly across the usable scale, from a '4-5' seed (11).
    const theta: TrueTheta = {
      fluid_reasoning: 3 + 14 * rng(),
      verbal: 3 + 14 * rng(),
      quantitative: 3 + 14 * rng(),
      spatial: 3 + 14 * rng(),
    };
    const r = runChild(rule, '4-5', theta, real, c, 1000 + i * 7919, capOverride);
    sc.push(...r.staircaseErr.filter(Number.isFinite));
    ft.push(...r.fitErr.filter(Number.isFinite));
    ftc.push(...r.fitCErr.filter(Number.isFinite));
    ses.push(...r.finalSe.filter(Number.isFinite));
    lens.push(r.items);
    if (r.hitCap) caps += 1;
  }

  return {
    rule,
    n: children,
    items: mean(lens),
    capRate: caps / children,
    staircaseBias: mean(sc),
    staircaseRmse: rmse(sc),
    fitBias: mean(ft),
    fitRmse: rmse(ft),
    fitCBias: mean(ftc),
    fitCRmse: rmse(ftc),
    meanSe: mean(ses),
  };
}

function sectionC(real: RealBanks): void {
  const CHILDREN = 150;
  const rules: Rule[] = ['centre', 'endpoint-alt', 'endpoint-upper', 'offset-minus', 'fit-centre', 'fit-centre-c'];

  for (const c of [0, FIVE_OPTION]) {
    console.log(
      `\n## C. Phase 1 selection rules, stochastic responder (slope 1.0, guessing floor ${f(c, 1)}), real bank\n`,
    );
    console.log(
      `${CHILDREN} simulated children, true ability drawn U(3, 17) independently per area, all seeded\n` +
        "at grade band '4-5' (seed 11). App engine config (hardItemCap 40). Bias/RMSE in scale points.\n",
    );
    console.log(
      '| selection rule | items | ended on cap | staircase bias | staircase RMSE | fitted bias | fitted RMSE | c-corrected fit bias | c-corrected fit RMSE | mean final SE |',
    );
    console.log('| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |');
    for (const rule of rules) {
      const s = runCohort(rule, real, c, CHILDREN);
      console.log(
        `| ${s.rule} | ${f(s.items, 1)} | ${f(100 * s.capRate, 0)}% | ${f(s.staircaseBias, 2)} | ${f(s.staircaseRmse, 2)} | ` +
          `${f(s.fitBias, 2)} | ${f(s.fitRmse, 2)} | ${f(s.fitCBias, 2)} | ${f(s.fitCRmse, 2)} | ${f(s.meanSe, 3)} |`,
      );
    }
  }
}

/** Fixed-length comparison: same item budget for every arm, so efficiency is not confounded by length. */
function sectionD(real: RealBanks): void {
  console.log('\n## D. Fixed item budget — efficiency at equal cost\n');
  console.log(
    'Stop rule disabled (cap forced, minItemsPerArea raised) so every arm spends the SAME number of\n' +
      'items. This isolates information per item from "how long the stop rule let it run".\n',
  );
  const CHILDREN = 120;
  const rules: Rule[] = ['centre', 'endpoint-alt', 'endpoint-upper', 'offset-minus', 'fit-centre', 'fit-centre-c'];

  for (const c of [0, FIVE_OPTION]) {
    console.log(`\n### responder guessing floor ${f(c, 1)}\n`);
    console.log('| selection rule | items | fitted bias | fitted RMSE | mean final SE | c-corrected fit RMSE |');
    console.log('| --- | --- | --- | --- | --- | --- |');
    for (const rule of rules) {
      // Force a fixed length by making the stop rule unsatisfiable within the cap.
      const s = runCohortFixed(rule, real, c, CHILDREN, 40);
      console.log(
        `| ${s.rule} | ${f(s.items, 1)} | ${f(s.fitBias, 2)} | ${f(s.fitRmse, 2)} | ${f(s.meanSe, 3)} | ${f(s.fitCRmse, 2)} |`,
      );
    }
  }
}

function runCohortFixed(
  rule: Rule,
  real: RealBanks,
  c: number,
  children: number,
  cap: number,
): ArmSummary {
  const rng = mulberry32(4242);
  const sc: number[] = [];
  const ft: number[] = [];
  const ftc: number[] = [];
  const ses: number[] = [];
  const lens: number[] = [];

  for (let i = 0; i < children; i += 1) {
    const theta: TrueTheta = {
      fluid_reasoning: 3 + 14 * rng(),
      verbal: 3 + 14 * rng(),
      quantitative: 3 + 14 * rng(),
      spatial: 3 + 14 * rng(),
    };
    const r = runChildFixed(rule, '4-5', theta, real, c, 1000 + i * 7919, cap);
    sc.push(...r.staircaseErr.filter(Number.isFinite));
    ft.push(...r.fitErr.filter(Number.isFinite));
    ftc.push(...r.fitCErr.filter(Number.isFinite));
    ses.push(...r.finalSe.filter(Number.isFinite));
    lens.push(r.items);
  }

  return {
    rule,
    n: children,
    items: mean(lens),
    capRate: 1,
    staircaseBias: mean(sc),
    staircaseRmse: rmse(sc),
    fitBias: mean(ft),
    fitRmse: rmse(ft),
    fitCBias: mean(ftc),
    fitCRmse: rmse(ftc),
    meanSe: mean(ses),
  };
}

/** Same loop, but ignores the stop rule entirely and serves exactly `cap` items. */
function runChildFixed(
  rule: Rule,
  gradeBand: AgeBand,
  trueTheta: TrueTheta,
  real: RealBanks,
  c: number,
  seed: number,
  cap: number,
): ChildResult {
  const rng = mulberry32(seed);
  // `nextType` returns null once `isDone`, so the stop rule has to be made unsatisfiable for the
  // budget to be genuinely fixed: an unreachable `minItemsPerArea` keeps `coverageIsEven` false.
  let state = startState(gradeBand, {
    ...APP_CONFIG,
    hardItemCap: 10_000,
    minItemsPerArea: 10_000,
  });
  const byArea = new Map<Area, ScoredItem[]>(AREAS.map((a) => [a, []]));

  for (let n = 0; n < cap; n += 1) {
    const typeCode = nextType(state, real.banks);
    if (typeCode === null) break;
    const type = real.banks.types.find((t) => t.typeCode === typeCode);
    if (!type) break;
    const area = type.domain;
    const aim = aimFor(rule, state, area, byArea.get(area) ?? [], gradeBand);
    const aimed: SessionState = {
      ...state,
      areas: { ...state.areas, [area]: { ...state.areas[area], difficulty: aim } },
    };
    let served: ServedItem;
    try {
      served = nextItem(aimed, typeCode, real.banks);
    } catch {
      break;
    }
    const scored = respond(served, real, trueTheta, c, rng);
    byArea.get(area)?.push(scored);
    state = update(state, scored);
  }

  const staircaseErr: number[] = [];
  const fitErr: number[] = [];
  const fitCErr: number[] = [];
  const finalSe: number[] = [];
  for (const area of AREAS) {
    const trace = byArea.get(area) ?? [];
    const truth = trueTheta[area];
    staircaseErr.push(state.areas[area].difficulty - truth);
    const scoring = trace as unknown as readonly ScoringItem[];
    const est = deriveAbilityEstimate(scoring, FIT);
    fitErr.push(est === null ? NaN : est - truth);
    finalSe.push(est === null ? NaN : (abilityStandardError(est, scoring, FIT) ?? NaN));
    const corrected = fitWithFloor(trace, FIVE_OPTION);
    fitCErr.push(corrected === null ? NaN : corrected - truth);
  }

  return { items: state.itemsServed, hitCap: true, staircaseErr, fitErr, fitCErr, finalSe };
}

/**
 * E. Convergence trajectory. Fitted RMSE and mean SE after k items IN ONE AREA, at a fixed budget.
 * This is the direct test of "does endpoint targeting converge more slowly".
 */
function sectionE(real: RealBanks): void {
  console.log('\n## E. Convergence trajectory — accuracy after k items in an area\n');
  console.log(
    'Fixed budget of 40 items per session (stop rule made unsatisfiable). For each area, the fitted\n' +
      'ability after its first k items is compared to that area\u2019s truth. 120 children x 4 areas.\n',
  );
  const CHILDREN = 120;
  const KS = [2, 4, 6, 8, 10];
  const rules: Rule[] = ['centre', 'endpoint-alt', 'offset-minus'];

  for (const c of [0, FIVE_OPTION]) {
    console.log(`\n### responder guessing floor ${f(c, 1)}\n`);
    console.log(`| selection rule | ${KS.map((k) => `RMSE @${k}`).join(' | ')} | ${KS.map((k) => `SE @${k}`).join(' | ')} |`);
    console.log(`| --- | ${KS.map(() => '---').join(' | ')} | ${KS.map(() => '---').join(' | ')} |`);
    for (const rule of rules) {
      const rng = mulberry32(4242);
      const errsAt = new Map<number, number[]>(KS.map((k) => [k, []]));
      const seAt = new Map<number, number[]>(KS.map((k) => [k, []]));

      for (let i = 0; i < CHILDREN; i += 1) {
        const theta: TrueTheta = {
          fluid_reasoning: 3 + 14 * rng(),
          verbal: 3 + 14 * rng(),
          quantitative: 3 + 14 * rng(),
          spatial: 3 + 14 * rng(),
        };
        const traces = traceChild(rule, '4-5', theta, real, c, 1000 + i * 7919, 40);
        for (const area of AREAS) {
          const trace = traces.get(area) ?? [];
          for (const k of KS) {
            if (trace.length < k) continue;
            const slice = trace.slice(0, k) as unknown as readonly ScoringItem[];
            const est = deriveAbilityEstimate(slice, FIT);
            if (est === null) continue;
            errsAt.get(k)?.push(est - theta[area]);
            const se = abilityStandardError(est, slice, FIT);
            if (se !== null && Number.isFinite(se)) seAt.get(k)?.push(se);
          }
        }
      }
      console.log(
        `| ${rule} | ${KS.map((k) => f(rmse(errsAt.get(k) ?? []), 2)).join(' | ')} | ` +
          `${KS.map((k) => f(mean(seAt.get(k) ?? []), 2)).join(' | ')} |`,
      );
    }
  }
}

/** Run a fixed-budget session and return the per-area traces, in served order. */
function traceChild(
  rule: Rule,
  gradeBand: AgeBand,
  trueTheta: TrueTheta,
  real: RealBanks,
  c: number,
  seed: number,
  cap: number,
): Map<Area, ScoredItem[]> {
  const rng = mulberry32(seed);
  let state = startState(gradeBand, {
    ...APP_CONFIG,
    hardItemCap: 10_000,
    minItemsPerArea: 10_000,
  });
  const byArea = new Map<Area, ScoredItem[]>(AREAS.map((a) => [a, []]));

  for (let n = 0; n < cap; n += 1) {
    const typeCode = nextType(state, real.banks);
    if (typeCode === null) break;
    const type = real.banks.types.find((t) => t.typeCode === typeCode);
    if (!type) break;
    const area = type.domain;
    const aim = aimFor(rule, state, area, byArea.get(area) ?? [], gradeBand);
    const aimed: SessionState = {
      ...state,
      areas: { ...state.areas, [area]: { ...state.areas[area], difficulty: aim } },
    };
    let served: ServedItem;
    try {
      served = nextItem(aimed, typeCode, real.banks);
    } catch {
      break;
    }
    const scored = respond(served, real, trueTheta, c, rng);
    byArea.get(area)?.push(scored);
    state = update(state, scored);
  }
  return byArea;
}

/**
 * F. Robustness when the seed is badly wrong — the strongest argument FOR a non-centre rule.
 * Every child is seeded at the wrong end of the scale.
 */
function sectionF(real: RealBanks): void {
  console.log('\n## F. Robustness to a badly wrong starting prior\n');
  console.log(
    "Every child is seeded 'K-1' (start 3) but has true ability 16-19, and vice versa. This is the\n" +
      'case where centre-targeting is supposed to get stuck. Variable length, app config.\n',
  );
  const rules: Rule[] = ['centre', 'endpoint-alt', 'offset-minus', 'fit-centre'];
  const cases: { label: string; band: AgeBand; lo: number; hi: number }[] = [
    { label: "seeded 'K-1' (3), true 16-19", band: 'K-1', lo: 16, hi: 19 },
    { label: "seeded 'above-level' (18), true 2-5", band: 'above-level', lo: 2, hi: 5 },
  ];

  for (const c of [0, FIVE_OPTION]) {
    console.log(`\n### responder guessing floor ${f(c, 1)}\n`);
    console.log('| case | selection rule | items | ended on cap | staircase bias | fitted bias | fitted RMSE |');
    console.log('| --- | --- | --- | --- | --- | --- | --- |');
    for (const kase of cases) {
      for (const rule of rules) {
        const rng = mulberry32(99);
        const sc: number[] = [];
        const ft: number[] = [];
        const lens: number[] = [];
        let caps = 0;
        for (let i = 0; i < 100; i += 1) {
          const draw = (): number => kase.lo + (kase.hi - kase.lo) * rng();
          const theta: TrueTheta = {
            fluid_reasoning: draw(),
            verbal: draw(),
            quantitative: draw(),
            spatial: draw(),
          };
          const r = runChild(rule, kase.band, theta, real, c, 5000 + i * 7919);
          sc.push(...r.staircaseErr.filter(Number.isFinite));
          ft.push(...r.fitErr.filter(Number.isFinite));
          lens.push(r.items);
          if (r.hitCap) caps += 1;
        }
        console.log(
          `| ${kase.label} | ${rule} | ${f(mean(lens), 1)} | ${f(caps, 0)}% | ${f(mean(sc), 2)} | ${f(mean(ft), 2)} | ${f(rmse(ft), 2)} |`,
        );
      }
    }
  }
}

// ---------------------------------------------------------------------------

console.log('# Item-selection bracketing analysis (throwaway; born-synthetic)\n');
sectionA();
sectionB();
const real = loadRealBanks();
console.log(
  `\nReal bank loaded: ${real.banks.types.length} wired types, ${real.banks.items.length} items.`,
);
sectionC(real);
sectionD(real);
sectionE(real);
sectionF(real);
