import { createHash } from 'node:crypto';
import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

/**
 * Emit the persona-simulator output in the schema `scripts/validation-harness`
 * already consumes (README "Dataset schema"), so the Python psychometrics pipeline
 * runs over simulator output with NO analysis-code change.
 *
 * The harness loader FAILS CLOSED: it refuses any dataset whose sibling manifest
 * does not prove `synthetic_only=true`, `validated=false`, `contains_real_data=false`
 * and whose SHA-256 does not match (D-006, R9, SEC-05). This writer therefore emits
 * the manifest the guard demands, and nothing here may ever be pointed at real
 * data — that requires a formal authorized live-data decision (B-06).
 *
 * NOTE ON THE `cogat_sas` / `map_rit` COLUMNS: the harness schema names them after
 * real instruments, but the values written here are SYNTHETIC PROXIES generated
 * from the same latent theta as the item responses. They are therefore CIRCULAR
 * with the new-test score and are not convergent-validity evidence of any kind.
 * They exist so the pipeline's column contract is satisfied end-to-end.
 */

export type CsvValue = string | number;

export interface HarnessDataset {
  columns: string[];
  rows: Record<string, CsvValue>[];
}

function inferColumnTypes(dataset: HarnessDataset): Record<string, string> {
  const types: Record<string, string> = {};
  for (const column of dataset.columns) {
    let type = 'int';
    for (const row of dataset.rows) {
      const value = row[column];
      if (typeof value === 'string') {
        type = 'str';
        break;
      }
      if (typeof value === 'number' && !Number.isInteger(value)) type = 'float';
    }
    types[column] = type;
  }
  return types;
}

function csvCell(value: CsvValue): string {
  const text = typeof value === 'number' ? String(value) : value;
  return /[",\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text;
}

export interface WriteHarnessDatasetOptions {
  outDir: string;
  /** File stem; the manifest is written alongside as `<name>.manifest.json`. */
  name: string;
  dataset: HarnessDataset;
  seed: string;
  generationConfig: Record<string, unknown>;
  groundTruth: Record<string, unknown>;
  /** Extra manifest keys (claim boundaries, column notes). */
  extraManifest?: Record<string, unknown>;
}

export interface WrittenDataset {
  csvPath: string;
  manifestPath: string;
  sha256: string;
  rows: number;
}

export function writeHarnessDataset(options: WriteHarnessDatasetOptions): WrittenDataset {
  const { outDir, name, dataset, seed } = options;
  mkdirSync(outDir, { recursive: true });
  const csvPath = path.join(outDir, `${name}.csv`);
  const manifestPath = path.join(outDir, `${name}.manifest.json`);

  const lines = [dataset.columns.join(',')];
  for (const row of dataset.rows) {
    lines.push(dataset.columns.map((c) => csvCell(row[c] ?? '')).join(','));
  }
  const csv = `${lines.join('\n')}\n`;
  writeFileSync(csvPath, csv);
  const sha256 = createHash('sha256').update(csv).digest('hex');

  const manifest = {
    // --- born-synthetic tags the harness guard checks (D-006, R9) -------------
    synthetic_only: true,
    validated: false,
    source: 'born-synthetic',
    contains_real_data: false,
    data_class: 'synthetic',
    privacy_note:
      'No real or live student data. Rows are simulated personas generated by ' +
      'packages/cat-engine/src/persona-sim and run through the real session shell. D-006, R9.',
    // --- provenance / audit (R7) ---------------------------------------------
    schema_version: '1',
    generator: 'scripts/persona-sim/run-recovery.ts',
    created_utc: new Date().toISOString().replace(/\.\d{3}Z$/, 'Z'),
    seed,
    n_rows: dataset.rows.length,
    columns: dataset.columns,
    column_types: inferColumnTypes(dataset),
    dataset_file: path.basename(csvPath),
    dataset_sha256: sha256,
    generation_config: options.generationConfig,
    full_config: { seed, generation: options.generationConfig },
    synthetic_ground_truth: options.groundTruth,
    ...options.extraManifest,
  };
  writeFileSync(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);

  return { csvPath, manifestPath, sha256, rows: dataset.rows.length };
}
