import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import process from 'node:process';

// The engine is imported by PATH rather than by package name: this script is not a
// workspace package, so adding a package dependency (and a lockfile entry) just to
// run a research script would be a heavier change than the script warrants.
import {
  archetypeDescription,
  createPersonaRun,
  PERSONA_ARCHETYPES,
  samplePersonaCohort,
  type Persona,
  type PersonaTrial,
} from '../../packages/cat-engine/src/persona-sim/index';
import { probabilityCorrect } from '../../packages/cat-engine/src/irt';
import { hashSeed, mulberry32 } from '../../packages/cat-engine/src/rng';
import { isRapidGuess } from '../../packages/cat-engine/src/rte';
import { learningRate as olsLearningRate } from '../../packages/cat-engine/src/scoring';
import { estimateThetaEap, estimateThetaMle } from '../../packages/cat-engine/src/theta';
import {
  SCORED_DOMAINS,
  type ScoredDomain,
  type ScoredResponse,
} from '../../packages/cat-engine/src/types';

import { driveSession } from '../../apps/web/src/lib/exam/session';
import { FixedSequencer, type Sequencer } from '../../apps/web/src/lib/exam/sequencer';
import { TwoStageSequencer } from '../../apps/web/src/lib/exam/two-stage-sequencer';

import { syntheticRecoveryBank } from './bank';
import { writeHarnessDataset, type CsvValue } from './harness-export';
import {
  agreement,
  bias,
  classify,
  fmt,
  mean,
  pearson,
  percentileOf,
  rmse,
  round,
  sd,
  spearman,
  type ClassificationResult,
} from './stats';

/**
 * Persona -> real session -> theta recovery runner
 * (`PERSONA_SIM_AND_VALIDATION_DESIGN.md` §1, "smallest vertical slice").
 *
 * WHAT THIS CAN AND CANNOT SHOW. It samples personas with KNOWN latent ability,
 * runs each through the production session shell and the production scoring rule,
 * recovers theta with the production estimator, and compares. Because the
 * responses were generated by the SAME 3PL the estimator inverts, the recovery is
 * CIRCULAR: a good RMSE demonstrates that the code path is wired correctly and
 * quantifies estimator bias/precision and the item count a target SE needs. It is
 * NOT evidence that any metric measures real ability, NOT convergent validity, and
 * NOT program impact — those are separate milestones needing external criteria and
 * a counterfactual design (R10).
 *
 * Everything is born-synthetic: no network, no database, no real data (D-006, R9).
 */

interface Options {
  n: number;
  seed: string;
  outDir: string;
  /** Absolute theta cut for the classification analysis. */
  cut: number;
  targetSes: number[];
  runHarness: boolean;
}

function parseArgs(argv: readonly string[]): Options {
  const get = (flag: string): string | undefined => {
    const i = argv.indexOf(flag);
    return i >= 0 ? argv[i + 1] : undefined;
  };
  return {
    n: Number(get('--n') ?? 1000),
    seed: get('--seed') ?? 'persona-sim-2026-07-27',
    outDir: get('--out') ?? path.join(process.cwd(), 'scripts/persona-sim/out'),
    // 1.2816 = the 90th percentile of N(0,1): a screening band, never an admission
    // decision (R10). GT owns the real cut as versioned policy (D-016).
    cut: Number(get('--cut') ?? 1.2816),
    targetSes: (get('--target-se') ?? '0.5,0.45,0.4,0.35,0.3,0.25').split(',').map(Number),
    runHarness: !argv.includes('--no-harness'),
  };
}

type ArmId = 'fixed' | 'two-stage';

interface ArmSpec {
  id: ArmId;
  label: string;
  makeSequencer: () => Sequencer;
}

const ARMS: ArmSpec[] = [
  {
    id: 'fixed',
    label: 'FixedSequencer (all items, domain-balanced)',
    makeSequencer: () => new FixedSequencer(),
  },
  {
    id: 'two-stage',
    label: 'TwoStageSequencer (bracketed standing -> effort placement)',
    makeSequencer: () => new TwoStageSequencer({ phase1CapPerDomain: 8, phase2PerDomain: 4 }),
  },
];

interface DomainRecovery {
  domain: ScoredDomain;
  itemsUsed: number;
  eap: number | null;
  eapSe: number | null;
  mle: number | null;
  mleSe: number | null;
}

interface PersonaArmResult {
  persona: Persona;
  arm: ArmId;
  itemsPresented: number;
  trials: PersonaTrial[];
  /** Mismatches between the production scoring rule and the generator's truth. */
  scoringMismatches: number;
  domains: DomainRecovery[];
  /** Composite EAP over standing trials that pass the RT-based gate (pooled). */
  compositeEap: number;
  compositeSe: number;
  compositeMle: number;
  /** Composite EAP with NO gating at all, for the gate's incremental effect. */
  compositeEapUngated: number;
  /**
   * Composite EAP over trials the GENERATOR marked on-task. The RT filter can only
   * catch FAST disengagement, so this is the "if engagement telemetry were perfect"
   * upper bound and isolates estimator bias from gate leakage.
   */
  compositeEapOracle: number;
  compositeSeOracle: number;
  effortValidRate: number;
  detectedRapidGuesses: number;
  /** OLS score slope inside the novel (effort) block, averaged over domains. */
  learningRateSlope: number | null;
  /**
   * The same slope after subtracting each item's expected score at the recovered
   * theta. The effort block is administered at ASCENDING difficulty, so a raw score
   * slope mixes the learning climb with difficulty escalation; residualizing on the
   * 3PL expectation removes the escalation and leaves the climb.
   */
  learningRateResidualSlope: number | null;
}

const bank = syntheticRecoveryBank();
const irtFor = (itemId: string) => bank.irtByItemId.get(itemId);

function toScoredResponses(trials: readonly PersonaTrial[]): ScoredResponse[] {
  return trials.map((t) => ({ irt: t.irt, correct: t.correct }));
}

/** The production gate: a response at or below the item RT floor is not evidence. */
function isEffortfulByGate(trial: PersonaTrial): boolean {
  return !isRapidGuess(trial.rtMs, bank.rapidGuessThresholdMs);
}

function runPersonaArm(persona: Persona, arm: ArmSpec, seed: string): PersonaArmResult {
  const run = createPersonaRun(persona, `${seed}|${arm.id}`, {
    itemIrt: (item) => irtFor(item.itemId),
  });
  const session = driveSession(bank.items, arm.makeSequencer(), run.respond);

  // The production path resolved correctness from the raw option index against the
  // bank key. If it disagrees with what the generator drew, the scoring path is
  // wrong — this is the one non-circular check in the whole runner.
  let scoringMismatches = 0;
  session.results.forEach((result, i) => {
    const trial = run.trials[i];
    if (!trial) {
      scoringMismatches += 1;
      return;
    }
    const expected = trial.correct ? 1 : 0;
    if (result.accuracy !== expected) scoringMismatches += 1;
  });

  const standing = run.trials.filter((t) => t.stage === 'standing');
  const gated = standing.filter(isEffortfulByGate);

  const domains: DomainRecovery[] = SCORED_DOMAINS.map((domain) => {
    const trials = gated.filter((t) => t.domain === domain);
    if (trials.length === 0) {
      return { domain, itemsUsed: 0, eap: null, eapSe: null, mle: null, mleSe: null };
    }
    const responses = toScoredResponses(trials);
    const eap = estimateThetaEap(responses);
    const mle = estimateThetaMle(responses);
    return {
      domain,
      itemsUsed: trials.length,
      eap: eap.theta,
      eapSe: eap.se,
      mle: mle.theta,
      mleSe: mle.se,
    };
  });

  const pooledGated = estimateThetaEap(toScoredResponses(gated));
  const pooledUngated = estimateThetaEap(toScoredResponses(standing));
  const pooledMle = estimateThetaMle(toScoredResponses(gated));
  const pooledOracle = estimateThetaEap(toScoredResponses(standing.filter((t) => t.onTask)));

  const slopes: number[] = [];
  const residualSlopes: number[] = [];
  for (const domain of SCORED_DOMAINS) {
    const block = run.trials.filter((t) => t.stage === 'effort' && t.domain === domain);
    if (block.length < 3) continue;
    const order = block.map((t) => (t.novelBlockIndex ?? 0) + 1);
    const scores = block.map((t) => (t.correct ? 1 : 0));
    const slope = olsLearningRate(order, scores);
    if (slope != null) slopes.push(slope);
    const thetaHat = domains.find((d) => d.domain === domain)?.eap;
    if (thetaHat != null) {
      const residuals = block.map((t, i) => scores[i]! - probabilityCorrect(thetaHat, t.irt));
      const residualSlope = olsLearningRate(order, residuals);
      if (residualSlope != null) residualSlopes.push(residualSlope);
    }
  }

  return {
    persona,
    arm: arm.id,
    itemsPresented: run.trials.length,
    trials: run.trials,
    scoringMismatches,
    domains,
    compositeEap: pooledGated.theta,
    compositeSe: pooledGated.se,
    compositeMle: pooledMle.theta,
    compositeEapUngated: pooledUngated.theta,
    compositeEapOracle: pooledOracle.theta,
    compositeSeOracle: pooledOracle.se,
    effortValidRate: standing.length === 0 ? Number.NaN : gated.length / standing.length,
    detectedRapidGuesses: standing.length - gated.length,
    learningRateSlope: slopes.length ? mean(slopes) : null,
    learningRateResidualSlope: residualSlopes.length ? mean(residualSlopes) : null,
  };
}

// --- aggregate recovery -------------------------------------------------------

interface RecoveryBlock {
  n: number;
  rmse: number;
  bias: number;
  pearson: number;
  spearman: number;
  meanSe: number;
}

function recoveryBlock(
  truth: readonly number[],
  estimate: readonly number[],
  ses: readonly number[],
): RecoveryBlock {
  return {
    n: truth.length,
    rmse: rmse(truth, estimate),
    bias: bias(truth, estimate),
    pearson: pearson(truth, estimate),
    spearman: spearman(truth, estimate),
    meanSe: mean(ses),
  };
}

/**
 * Mean posterior SE and RMSE after the first k ADMINISTERED standing items, per
 * domain and pooled. This is the design doc's key output: how many items a target
 * SE needs.
 *
 * The x-axis is ADMINISTERED items, not surviving items, and the estimate at k uses
 * whichever of the first k passed the gate. Indexing by surviving items instead
 * would censor the curve — personas who lose items to the gate would silently drop
 * out of the high-k rows and make the form look more precise than it is.
 */
function seCurve(results: readonly PersonaArmResult[], scope: ScoredDomain | 'pooled') {
  const perK = new Map<number, { se: number[]; err: number[] }>();
  for (const result of results) {
    const standing = result.trials.filter(
      (t) => t.stage === 'standing' && (scope === 'pooled' || t.domain === scope),
    );
    const truth = scope === 'pooled' ? result.persona.thetaMean : result.persona.theta[scope];
    for (let k = 1; k <= standing.length; k++) {
      const estimate = estimateThetaEap(
        toScoredResponses(standing.slice(0, k).filter(isEffortfulByGate)),
      );
      const bucket = perK.get(k) ?? { se: [], err: [] };
      bucket.se.push(estimate.se);
      bucket.err.push(estimate.theta - truth);
      perK.set(k, bucket);
    }
  }
  return [...perK.entries()]
    .sort((a, b) => a[0] - b[0])
    .map(([items, bucket]) => ({
      items,
      personas: bucket.se.length,
      meanSe: mean(bucket.se),
      rmse: Math.sqrt(mean(bucket.err.map((e) => e * e))),
      bias: mean(bucket.err),
    }));
}

/**
 * The smallest administered-item count whose MEAN posterior SE meets `target`.
 * Points backed by fewer than 90% of the cohort are ignored: a shorter form that
 * only some personas reached cannot be quoted as a form length.
 */
function itemsForTargetSe(
  curve: readonly { items: number; meanSe: number; personas: number }[],
  target: number,
  cohortSize: number,
): number | null {
  for (const point of curve) {
    if (point.personas < 0.9 * cohortSize) continue;
    if (point.meanSe <= target) return point.items;
  }
  return null;
}

// --- harness dataset ----------------------------------------------------------

function buildHarnessDataset(results: readonly PersonaArmResult[], seed: string) {
  const itemColumns = bank.standingItemIdsInBankOrder.map(
    (_, i) => `nt_${String(i + 1).padStart(2, '0')}`,
  );
  const columns = [
    'student_id',
    'grade',
    'cogat_sas',
    'map_rit',
    ...itemColumns,
    'newtest_total',
    'criterion_eoy',
    'subgroup_demo',
    'ell_status',
    'ses_band',
    'archetype',
    'true_theta_mean',
    'theta_hat_eap',
    'true_learning_rate',
  ];
  const columnByItemId = new Map(
    bank.standingItemIdsInBankOrder.map((id, i) => [id, itemColumns[i]!]),
  );

  const rows = results.map((result, index) => {
    const persona = result.persona;
    const rand = mulberry32(hashSeed(`${seed}|covariates|${persona.personaId}`));
    const normal = () => {
      let u = 0;
      let v = 0;
      let s = 0;
      do {
        u = 2 * rand() - 1;
        v = 2 * rand() - 1;
        s = u * u + v * v;
      } while (s === 0 || s >= 1);
      return u * Math.sqrt((-2 * Math.log(s)) / s);
    };

    const grade = 3 + Math.floor(rand() * 6);
    const theta = persona.thetaMean;
    // SYNTHETIC PROXIES for the harness's column contract, generated from the same
    // latent theta -> circular with the new test by construction. NOT CogAT/MAP.
    const cogat = Math.round(
      Math.min(160, Math.max(55, 100 + 16 * (0.9 * theta + 0.44 * normal()))),
    );
    const mapRit = Math.round(
      Math.min(300, Math.max(120, 190 + (grade - 3) * 5 + 15 * (0.82 * theta + 0.4 * normal()))),
    );
    const lambdaZ = (persona.learningRate - 0.03) / 0.03;
    const criterion =
      Math.round((50 + 10 * (0.55 * theta + 0.3 * lambdaZ + 0.55 * normal())) * 100) / 100;

    const row: Record<string, CsvValue> = {
      student_id: `PERSONA-SYN-${String(index + 1).padStart(6, '0')}`,
      grade,
      cogat_sas: cogat,
      map_rit: mapRit,
      newtest_total: 0,
      criterion_eoy: criterion,
      subgroup_demo: rand() < 0.45 ? 'focal' : 'reference',
      ell_status: rand() < 0.22 ? 'ELL' : 'non-ELL',
      ses_band: rand() < 0.4 ? 'lower-income' : 'higher-income',
      archetype: persona.archetype,
      true_theta_mean: round(theta, 4),
      theta_hat_eap: round(result.compositeEap, 4),
      true_learning_rate: round(persona.learningRate, 5),
    };
    for (const column of itemColumns) row[column] = 0;
    let total = 0;
    for (const trial of result.trials) {
      const column = columnByItemId.get(trial.itemId);
      if (!column) continue;
      const scored = trial.correct ? 1 : 0;
      row[column] = scored;
      total += scored;
    }
    row.newtest_total = total;
    return row;
  });

  return { columns, rows };
}

// --- report -------------------------------------------------------------------

const CLAIM_HEADER = [
  '> **CLAIM BOUNDARY — READ FIRST.** Every row here is born-synthetic',
  '> (`synthetic_only: true`, `validated: false`; D-006, R9). Personas were generated by',
  '> the 3PL in `packages/cat-engine/src/irt.ts` and then scored by the estimator that',
  '> inverts that same 3PL, so **theta recovery here is CIRCULAR**. These numbers',
  '> demonstrate (a) that the session/scoring/estimation path is wired correctly,',
  "> (b) the estimator's bias and precision under known truth, and (c) how many items a",
  '> target SE requires. They are **not** evidence that any metric measures real ability,',
  '> **not** convergent or predictive validity, and **not** program impact — access,',
  '> reliability, outcome change, and causal impact are separate milestones (R10).',
  "> Tuning anything on this data tunes to the simulator's assumptions, not to children.",
].join('\n');

function mdTable(headers: readonly string[], rows: readonly (readonly string[])[]): string {
  return [
    `| ${headers.join(' | ')} |`,
    `|${headers.map(() => '---').join('|')}|`,
    ...rows.map((r) => `| ${r.join(' | ')} |`),
  ].join('\n');
}

function classificationRow(label: string, c: ClassificationResult): string[] {
  return [
    label,
    String(c.n),
    fmt(c.accuracy),
    fmt(c.kappa),
    fmt(c.sensitivity),
    fmt(c.specificity),
    fmt(c.falseNegativeRate),
    `${c.falseNegative}`,
  ];
}

function main(): void {
  const options = parseArgs(process.argv.slice(2));
  const startedAt = new Date().toISOString();
  const cohort = samplePersonaCohort({ seed: options.seed, n: options.n });

  const byArm = new Map<ArmId, PersonaArmResult[]>();
  for (const arm of ARMS) {
    byArm.set(
      arm.id,
      cohort.map((persona) => runPersonaArm(persona, arm, options.seed)),
    );
  }

  const armSummaries = ARMS.map((arm) => {
    const results = byArm.get(arm.id)!;
    const truthComposite = results.map((r) => r.persona.thetaMean);
    const eapComposite = results.map((r) => r.compositeEap);
    const mleComposite = results.map((r) => r.compositeMle);
    const ungated = results.map((r) => r.compositeEapUngated);
    const oracle = results.map((r) => r.compositeEapOracle);
    const ses = results.map((r) => r.compositeSe);

    const perDomain = SCORED_DOMAINS.map((domain) => {
      const usable = results.filter((r) => r.domains.find((d) => d.domain === domain)?.eap != null);
      const truth = usable.map((r) => r.persona.theta[domain]);
      const eap = usable.map((r) => r.domains.find((d) => d.domain === domain)!.eap!);
      const mle = usable.map((r) => r.domains.find((d) => d.domain === domain)!.mle!);
      const domainSes = usable.map((r) => r.domains.find((d) => d.domain === domain)!.eapSe!);
      return {
        domain,
        meanItems: mean(usable.map((r) => r.domains.find((d) => d.domain === domain)!.itemsUsed)),
        eap: recoveryBlock(truth, eap, domainSes),
        mle: recoveryBlock(truth, mle, domainSes),
      };
    });

    const perArchetype = PERSONA_ARCHETYPES.map((archetype) => {
      const group = results.filter((r) => r.persona.archetype === archetype);
      const truth = group.map((r) => r.persona.thetaMean);
      return {
        archetype,
        description: archetypeDescription(archetype),
        n: group.length,
        eap: recoveryBlock(
          truth,
          group.map((r) => r.compositeEap),
          group.map((r) => r.compositeSe),
        ),
        eapUngated: recoveryBlock(
          truth,
          group.map((r) => r.compositeEapUngated),
          group.map((r) => r.compositeSe),
        ),
        eapOracle: recoveryBlock(
          truth,
          group.map((r) => r.compositeEapOracle),
          group.map((r) => r.compositeSeOracle),
        ),
        meanEffortValidRate: mean(group.map((r) => r.effortValidRate)),
      };
    });

    const classification = classify(truthComposite, eapComposite, options.cut);
    const classificationUngated = classify(truthComposite, ungated, options.cut);
    const classificationOracle = classify(truthComposite, oracle, options.cut);
    // Select the same SHARE of the cohort the truth cut selects, but threshold on the
    // estimate's own distribution — the operationally realistic comparison.
    const selectedShare = truthComposite.filter((t) => t >= options.cut).length / results.length;
    const classificationMatched = classify(
      truthComposite,
      eapComposite,
      options.cut,
      percentileOf(eapComposite, 100 * (1 - selectedShare)),
    );

    const curves = {
      pooled: seCurve(results, 'pooled'),
      ...Object.fromEntries(SCORED_DOMAINS.map((d) => [d, seCurve(results, d)])),
    } as Record<string, ReturnType<typeof seCurve>>;

    const lambdaTruth: number[] = [];
    const lambdaSlope: number[] = [];
    const lambdaResidualTruth: number[] = [];
    const lambdaResidualSlope: number[] = [];
    for (const r of results) {
      if (r.learningRateSlope != null) {
        lambdaTruth.push(r.persona.learningRate);
        lambdaSlope.push(r.learningRateSlope);
      }
      if (r.learningRateResidualSlope != null) {
        lambdaResidualTruth.push(r.persona.learningRate);
        lambdaResidualSlope.push(r.learningRateResidualSlope);
      }
    }

    return {
      arm: arm.id,
      label: arm.label,
      meanItemsPresented: mean(results.map((r) => r.itemsPresented)),
      scoringMismatches: results.reduce((s, r) => s + r.scoringMismatches, 0),
      composite: {
        eap: recoveryBlock(truthComposite, eapComposite, ses),
        mle: recoveryBlock(truthComposite, mleComposite, ses),
        eapUngated: recoveryBlock(truthComposite, ungated, ses),
        eapOracle: recoveryBlock(
          truthComposite,
          oracle,
          results.map((r) => r.compositeSeOracle),
        ),
      },
      perDomain,
      perArchetype,
      classification,
      classificationUngated,
      classificationOracle,
      classificationMatched,
      engagement: {
        meanEffortValidRate: mean(results.map((r) => r.effortValidRate)),
        meanDetectedRapidGuesses: mean(results.map((r) => r.detectedRapidGuesses)),
        personasBelowGate: results.filter((r) => r.effortValidRate < 0.8).length,
      },
      learningRate: {
        n: lambdaTruth.length,
        pearson: pearson(lambdaTruth, lambdaSlope),
        spearman: spearman(lambdaTruth, lambdaSlope),
        meanSlope: mean(lambdaSlope),
        sdSlope: sd(lambdaSlope),
        residualN: lambdaResidualTruth.length,
        residualPearson: pearson(lambdaResidualTruth, lambdaResidualSlope),
        residualSpearman: spearman(lambdaResidualTruth, lambdaResidualSlope),
        residualMeanSlope: mean(lambdaResidualSlope),
      },
      seCurves: curves,
      itemsForTargetSe: Object.fromEntries(
        Object.entries(curves).map(([scope, curve]) => [
          scope,
          Object.fromEntries(
            options.targetSes.map((target) => [
              target,
              itemsForTargetSe(curve, target, results.length),
            ]),
          ),
        ]),
      ),
    };
  });

  // Decision consistency BETWEEN the two structures at the same cut: how often the
  // two sequencers put the same child on the same side of the band.
  const fixedResults = byArm.get('fixed')!;
  const twoStageResults = byArm.get('two-stage')!;
  const crossArm = agreement(
    fixedResults.map((r) => r.compositeEap >= options.cut),
    twoStageResults.map((r) => r.compositeEap >= options.cut),
  );

  mkdirSync(options.outDir, { recursive: true });

  const report = {
    claimBoundary:
      'Born-synthetic recovery study. Recovering theta from the generative model that produced ' +
      'the responses is circular: it evidences code correctness, estimator bias/precision, and ' +
      'item-count requirements only. Not real validity; not program impact (R10).',
    syntheticOnly: true as const,
    validated: false as const,
    startedAt,
    options: { ...options, targetSes: options.targetSes },
    bank: {
      items: bank.items.length,
      standingItems: bank.standingItemIdsInBankOrder.length,
      rapidGuessThresholdMs: bank.rapidGuessThresholdMs,
    },
    cohort: {
      n: cohort.length,
      byArchetype: Object.fromEntries(
        PERSONA_ARCHETYPES.map((a) => [a, cohort.filter((p) => p.archetype === a).length]),
      ),
      trueThetaMean: round(mean(cohort.map((p) => p.thetaMean)), 4),
      trueThetaSd: round(sd(cohort.map((p) => p.thetaMean)), 4),
    },
    arms: armSummaries,
    crossArmDecisionConsistency: crossArm,
  };

  const jsonPath = path.join(options.outDir, 'persona-recovery.json');
  writeFileSync(jsonPath, `${JSON.stringify(report, null, 2)}\n`);

  // --- markdown report -------------------------------------------------------
  const lines: string[] = [];
  lines.push('# Persona-Simulator Theta-Recovery Report (SYNTHETIC)', '');
  lines.push(CLAIM_HEADER, '');
  lines.push(
    `Run: N=${cohort.length} personas · seed \`${options.seed}\` · bank ${bank.items.length} items ` +
      `(${bank.standingItemIdsInBankOrder.length} standing) · cut theta >= ${options.cut} · ${startedAt}`,
    '',
  );
  lines.push(
    `Cohort true theta (mean of 4 domains): mean ${fmt(mean(cohort.map((p) => p.thetaMean)))}, ` +
      `SD ${fmt(sd(cohort.map((p) => p.thetaMean)))}.`,
    '',
  );

  for (const summary of armSummaries) {
    lines.push(`## Arm: ${summary.label}`, '');
    lines.push(
      `Mean items presented per persona: ${fmt(summary.meanItemsPresented, 1)}. ` +
        `Production-scoring vs generator mismatches: **${summary.scoringMismatches}** ` +
        '(any non-zero value means the keyed scoring path disagrees with the simulated response).',
      '',
    );
    const compositeRow = (label: string, block: RecoveryBlock, showSe: boolean): string[] => [
      label,
      String(block.n),
      fmt(block.rmse),
      fmt(block.bias),
      fmt(block.pearson),
      fmt(block.spearman),
      showSe ? fmt(block.meanSe) : '—',
    ];
    lines.push('### Composite theta recovery (all standing items pooled)', '');
    lines.push(
      mdTable(
        ['condition', 'n', 'RMSE', 'bias', 'Pearson r', 'Spearman rho', 'mean SE'],
        [
          compositeRow('EAP · RT gate (production path)', summary.composite.eap, true),
          compositeRow('MLE · RT gate', summary.composite.mle, false),
          compositeRow('EAP · no gate', summary.composite.eapUngated, false),
          compositeRow('EAP · perfect engagement telemetry', summary.composite.eapOracle, true),
        ],
      ),
      '',
    );
    lines.push(
      'The three gate conditions separate two different things. `no gate` -> `RT gate` is what the ' +
        'production rapid-guess filter buys. `RT gate` -> `perfect engagement telemetry` is what the ' +
        'RT filter CANNOT buy: it only catches FAST disengagement, so a slow checked-out response ' +
        "still enters theta at the guessing floor. The last row is therefore the estimator's own " +
        'bias/precision under known truth, with disengagement removed by construction.',
      '',
    );
    lines.push('### Per-domain recovery (EAP)', '');
    lines.push(
      mdTable(
        ['domain', 'mean items', 'n', 'RMSE', 'bias', 'Pearson r', 'mean SE', 'MLE RMSE'],
        summary.perDomain.map((d) => [
          d.domain,
          fmt(d.meanItems, 1),
          String(d.eap.n),
          fmt(d.eap.rmse),
          fmt(d.eap.bias),
          fmt(d.eap.pearson),
          fmt(d.eap.meanSe),
          fmt(d.mle.rmse),
        ]),
      ),
      '',
    );
    lines.push('### Per-archetype composite recovery (EAP)', '');
    lines.push(
      mdTable(
        [
          'archetype',
          'n',
          'RMSE',
          'bias',
          'Pearson r',
          'RMSE no gate',
          'RMSE perfect telemetry',
          'mean effort-valid rate',
        ],
        summary.perArchetype.map((a) => [
          a.archetype,
          String(a.n),
          fmt(a.eap.rmse),
          fmt(a.eap.bias),
          fmt(a.eap.pearson),
          fmt(a.eapUngated.rmse),
          fmt(a.eapOracle.rmse),
          fmt(a.meanEffortValidRate),
        ]),
      ),
      '',
    );
    lines.push(
      `### Classification at theta >= ${options.cut} (screening band, NOT an admission decision)`,
      '',
    );
    lines.push(
      mdTable(
        [
          'condition',
          'n',
          'accuracy',
          'kappa',
          'sensitivity',
          'specificity',
          'false-negative rate',
          'FN count',
        ],
        [
          classificationRow('EAP · RT gate (production path)', summary.classification),
          classificationRow('EAP · no gate', summary.classificationUngated),
          classificationRow('EAP · perfect engagement telemetry', summary.classificationOracle),
          classificationRow(
            `EAP · RT gate, cut matched on the estimate (${fmt(summary.classificationMatched.estimateCut, 3)})`,
            summary.classificationMatched,
          ),
        ],
      ),
      '',
    );
    lines.push(
      'EAP shrinks toward the prior, so applying the TRUE-theta threshold directly to theta-hat ' +
        'under-selects and inflates false negatives. The last row keeps the same selected share but ' +
        'thresholds on the estimate distribution; the gap between the two rows is a policy artefact ' +
        'of how a cut is defined, not a measurement result. Either way this is a screening band, ' +
        'never an admission decision (R10).',
      '',
    );
    lines.push('### Engagement gate', '');
    lines.push(
      `Mean effort-valid rate ${fmt(summary.engagement.meanEffortValidRate)}; ` +
        `mean detected rapid guesses per persona ${fmt(summary.engagement.meanDetectedRapidGuesses, 2)}; ` +
        `personas below a 0.8 effort-valid floor: ${summary.engagement.personasBelowGate}.`,
      '',
    );
    lines.push('### SE vs number of administered items (pooled across domains)', '');
    lines.push(
      mdTable(
        ['administered items', 'personas', 'mean SE', 'RMSE', 'bias'],
        summary.seCurves
          .pooled!.filter((p) => p.items <= 8 || p.items % 4 === 0)
          .map((p) => [
            String(p.items),
            String(p.personas),
            fmt(p.meanSe),
            fmt(p.rmse),
            fmt(p.bias),
          ]),
      ),
      '',
    );
    lines.push(
      'Administered items needed to reach a target mean SE (points backed by fewer than 90% of the ' +
        'cohort are ignored):',
      '',
    );
    lines.push(
      mdTable(
        ['scope', ...options.targetSes.map((t) => `SE<=${t}`), 'best mean SE (at k items)'],
        Object.entries(summary.itemsForTargetSe).map(([scope, targets]) => {
          const curve = summary.seCurves[scope] ?? [];
          const usable = curve.filter((p) => p.personas >= 0.9 * cohort.length);
          const best = usable.length ? usable[usable.length - 1]! : null;
          return [
            scope,
            ...options.targetSes.map((t) => {
              const value = (targets as Record<string, number | null>)[String(t)];
              return value == null ? 'not reached' : String(value);
            }),
            best ? `${fmt(best.meanSe)} (k=${best.items})` : 'n/a',
          ];
        }),
      ),
      '',
    );
    lines.push('### Learning-rate channel (STRETCH — hypothesis only, H-series)', '');
    lines.push(
      mdTable(
        ['lambda estimator', 'n', 'Pearson r', 'Spearman rho', 'mean slope'],
        [
          [
            'raw OLS score slope over the novel block',
            String(summary.learningRate.n),
            fmt(summary.learningRate.pearson),
            fmt(summary.learningRate.spearman),
            fmt(summary.learningRate.meanSlope, 4),
          ],
          [
            'slope of the 3PL residual (difficulty removed)',
            String(summary.learningRate.residualN),
            fmt(summary.learningRate.residualPearson),
            fmt(summary.learningRate.residualSpearman),
            fmt(summary.learningRate.residualMeanSlope, 4),
          ],
        ],
      ),
      '',
    );
    lines.push(
      'Read this as a NULL, and specifically as a POWER null. Two things are visible. (1) The block ' +
        'is administered at ASCENDING difficulty, so the raw score slope conflates the learning climb ' +
        'with difficulty escalation — that is what the negative mean raw slope is; residualizing ' +
        'against the 3PL expectation flips the mean slope positive, which is the climb. (2) Removing ' +
        'the confound does NOT rescue the per-persona correlation, so the binding constraint is trial ' +
        'count, not the confound: a lambda of ~0.03 theta/trial over a block this short moves the ' +
        'expected score by only a few hundredths, against a per-persona slope SD an order of magnitude ' +
        'larger. A within-session learning rate is not recoverable from a block of this length at all. ' +
        'This is a statement about THIS block design under THESE assumptions — it is neither support ' +
        'for nor refutation of the learning-rate hypothesis, which stays a labelled hypothesis ' +
        '(H-series) and not a validated metric.',
      '',
    );
  }

  lines.push('## Cross-structure decision consistency', '');
  lines.push(
    `Fixed vs two-stage agreement on the same cut: ${fmt(crossArm.agreement)} ` +
      `(kappa ${fmt(crossArm.kappa)}, n=${crossArm.n}). Disagreement is a precision consequence of ` +
      'the shorter two-stage form, not evidence that either structure is more valid.',
    '',
  );

  const mdPath = path.join(options.outDir, 'persona-recovery.md');
  writeFileSync(mdPath, `${lines.join('\n')}\n`);

  console.log(`report (json): ${jsonPath}`);
  console.log(`report (md):   ${mdPath}`);

  // --- harness dataset -------------------------------------------------------
  if (!options.runHarness) {
    console.log('');
    console.log(lines.join('\n'));
    return;
  }
  const dataset = buildHarnessDataset(fixedResults, options.seed);
  const written = writeHarnessDataset({
    outDir: options.outDir,
    name: 'persona_sim_scores',
    dataset,
    seed: options.seed,
    generationConfig: {
      n_personas: cohort.length,
      bank_items: bank.items.length,
      standing_items: bank.standingItemIdsInBankOrder.length,
      arm: 'fixed',
      rapid_guess_threshold_ms: bank.rapidGuessThresholdMs,
      response_model: '3PL (packages/cat-engine/src/irt.ts) driven by persona latent theta',
    },
    groundTruth: {
      model: 'correlated multivariate-normal latent traits -> 3PL responses',
      latent_traits:
        'per-domain theta, learning rate, speed, consistency, engagement, planfulness, creativity, working memory',
      dial_to_theta: 'theta = (dial - 10.5) / 3',
      archetype_counts: Object.fromEntries(
        PERSONA_ARCHETYPES.map((a) => [a, cohort.filter((p) => p.archetype === a).length]),
      ),
      notes:
        'true_theta_mean / true_learning_rate columns are the injected truth, retained for audit. ' +
        'Recovery against them is circular by construction.',
    },
    extraManifest: {
      claim_boundary:
        'cogat_sas and map_rit are SYNTHETIC PROXIES generated from the same latent theta as the ' +
        'item responses. They are circular with newtest_total and are NOT convergent-validity ' +
        'evidence. criterion_eoy is a synthetic criterion; incremental-validity output over it ' +
        'demonstrates the method only.',
    },
  });

  console.log(
    `harness csv:   ${written.csvPath} (${written.rows} rows, sha256 ${written.sha256.slice(0, 12)}...)`,
  );
  console.log('');
  console.log(lines.join('\n'));
}

main();
