/**
 * U0 — the learning-block measurement harness (STAGE2_QUESTION_DESIGN §9.1).
 *
 * Drives a candidate item bank through the REAL administration path — `nextTargetTheta` +
 * `selectNextNovelItem` + `estimateLearningCurve` + `learningRateReadout` — for a simulated cohort,
 * in either `systemPersistence` mode, and reports what the bank's own difficulty grid does to the
 * estimator. It is the instrument Gate A (§4.1.2) is read off, and it is deliberately the first unit
 * built: a bank that cannot support the fit must be found before a renderer is written for it.
 *
 * WHAT THIS CAN AND CANNOT SHOW. Recovering an injected climb from responses generated by that same
 * climb is circular, and `learning-curve.ts` already says so. So the harness is NOT evidence that a
 * block measures learning. Its two honest uses are the converse:
 *
 *   1. **It does not manufacture λ.** Run a cohort with `λ_true = 0` — fixed ability, no learning
 *      whatsoever — through the real targeting rule on a real bank. The fitted λ̄ must come back at
 *      zero. When it does not, the bank's stated difficulties correlate with trial index and §1.1(d)
 *      of the design doc names the failure: structured labelling error maps straight onto `lambda`.
 *   2. **The bank's grid supports the estimator at all.** Recovery, attenuation and posterior SE on
 *      the bank's ACTUAL difficulty grid, compared against E-095's figures, which were measured on
 *      an idealised 0.5-point grid.
 *
 * WHY THE MODE IS A PARAMETER HERE TOO. D-S2-3 makes the scrambled-system control a generator mode
 * rather than a separate artifact, so the two arms are two bank files off one code path. The harness
 * takes the arm as an argument for the same reason: if the two arms were measured by different
 * drivers the contrast would be confounded with the driver. `--mode` selects which bank file of a
 * dual-mode pair is loaded; it changes nothing else about the simulation. The harness models NO
 * difference in child behaviour between arms — only children can supply that, which is Gate B.
 *
 * CLAIM BOUNDARY. Everything here is born-synthetic against `validated: false` banks. No output of
 * this script is evidence about a real child, and passing Gate A is not passing the gate (§4.1.2).
 *
 * Usage:
 *   pnpm exam:block-harness                          # calibration + Gate A on the reference bank
 *   pnpm exam:block-harness -- --calibrate           # E-095 reproduction: grid vs an existing bank
 *   pnpm exam:block-harness -- --noise-sweep         # sensitivity to the handover-noise SD
 *   pnpm exam:block-harness -- --guessing-probe      # what the `guessing = 0` fit does to a static child
 *   pnpm exam:block-harness -- --fix-probe           # every candidate remedy, costed side by side
 *   pnpm exam:block-harness -- --gate-a --bank FLU-OPCHAIN-01
 *   pnpm exam:block-harness -- --gate-a --bank grid          # Gate A with no bank at all
 *   pnpm exam:block-harness -- --gate-a --bank <path/to/bank.jsonl> --mode perTrial
 *   pnpm exam:block-harness -- --gate-a --bank grid --seeds 20260730,11,22,33,44,55,66,77
 *
 * Flags: --children N  --length N  --lambda-mean X  --lambda-sd X  --standing-noise X
 *        --guessing X  --fit-guessing X  --target-guessing X  --seed N  --seeds a,b,c  --json
 *        --targeting level|level-plain|projecting|frozen
 *
 * `--guessing` is the SIMULATED CHILD's floor (the truth). `--fit-guessing` and `--target-guessing`
 * are what the estimator assumes, in the readout fit and inside `nextTargetTheta` respectively.
 * Keeping the three separate is the whole point: the defect is a disagreement between them.
 */
import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { dirname, isAbsolute, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  RECOMMENDED_NOVEL_BLOCK_LENGTH,
  selectNextNovelItem,
  type AgeBand,
  type BankItem,
} from '../packages/exam-engine/src';
import {
  DEFAULT_GUESSING,
  MIN_TRIALS_FOR_PROJECTION,
  estimateBlockLevel,
  estimateLearningCurve,
  learningRateReadout,
  nextTargetTheta,
  type LearningTrial,
} from '../packages/exam-scoring/src';

// --- reference constants ------------------------------------------------------

/**
 * E-095's published figures at each block length, on an idealised 0.5-point grid at `slope: 1.0`
 * with adaptively-targeted difficulty and a noisy standing handover, over 400 simulated children
 * per cell at a population λ SD of 0.03. Quoted from `learning-rate-readout.ts`, which is the
 * module the evidence register points at.
 */
const E095 = {
  8: { r: 0.066, meanSe: 0.138, attenuation: 0.22 },
  15: { r: 0.183, meanSe: 0.101, attenuation: 0.57 },
  30: { r: 0.448, meanSe: 0.047, attenuation: 0.98 },
  45: { r: 0.746, meanSe: 0.026, attenuation: 1.02 },
  60: { r: 0.862, meanSe: 0.017, attenuation: 0.97 },
} as const;

/** Scale bounds and the design assumptions the standing fit also makes. */
const SCALE_MIN = 1;
const SCALE_MAX = 20;
const SLOPE = 1.0;
/** `LEARNING_BLOCK_TARGET_OFFSET` in `apps/web/src/lib/exam/phase2.ts`. */
const TARGET_OFFSET = 1;

/**
 * The bank the calibration run uses as its "existing bank" reference.
 *
 * `FLU-MATRIX-01` because it is the fluid exemplar the other generators were written against, it is
 * in the block's own area (D-S2-1), and E-080 measured its supply directly: fluid difficulty is
 * near-uniform at ~90 items per integer bin across the wired banks.
 */
const REFERENCE_BANK = 'FLU-MATRIX-01';

/**
 * The block-length ladder E-095 reports. Every calibration run walks all five so the comparison is
 * against the whole published table rather than the single cell that happens to agree.
 */
const LENGTH_LADDER = [8, 15, 30, 45, 60] as const;

/**
 * Tolerance on the E-095 comparison at 30 trials, in correlation points / SE points.
 *
 * Wide on purpose. The sweep that produced E-095 is not in the repository and its θ0 distribution
 * and handover-noise SD are unrecorded, so the reproduction is a re-implementation from the
 * published description rather than a re-run. A tight band would be asserting agreement with
 * parameters nobody wrote down. See the "underspecified" note printed by `--calibrate`.
 */
const E095_TOLERANCE = { r: 0.1, meanSe: 0.015, attenuation: 0.2 } as const;

// --- seeded randomness --------------------------------------------------------

function xmur3(str: string): () => number {
  let h = 1779033703 ^ str.length;
  for (let i = 0; i < str.length; i += 1) {
    h = Math.imul(h ^ str.charCodeAt(i), 3432918353);
    h = (h << 13) | (h >>> 19);
  }
  return () => {
    h = Math.imul(h ^ (h >>> 16), 2246822507);
    h = Math.imul(h ^ (h >>> 13), 3266489909);
    h ^= h >>> 16;
    return h >>> 0;
  };
}

function mulberry32(a: number): () => number {
  let s = a;
  return () => {
    s |= 0;
    s = (s + 0x6d2b79f5) | 0;
    let t = Math.imul(s ^ (s >>> 15), 1 | s);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** Seeded uniform stream. Same xmur3 → mulberry32 idiom the bank generators use. */
function makeRng(seed: string): () => number {
  return mulberry32(xmur3(seed)());
}

/** Box–Muller normal draw from a uniform stream. */
function normal(rng: () => number, mean: number, sd: number): number {
  const u = Math.max(rng(), Number.EPSILON);
  const v = rng();
  return mean + sd * Math.sqrt(-2 * Math.log(u)) * Math.cos(2 * Math.PI * v);
}

function clamp(x: number, lo: number, hi: number): number {
  return Math.min(hi, Math.max(lo, x));
}

// --- statistics ---------------------------------------------------------------

function mean(xs: readonly number[]): number {
  return xs.length === 0 ? Number.NaN : xs.reduce((a, b) => a + b, 0) / xs.length;
}

function sd(xs: readonly number[]): number {
  if (xs.length < 2) return Number.NaN;
  const m = mean(xs);
  return Math.sqrt(xs.reduce((a, b) => a + (b - m) * (b - m), 0) / (xs.length - 1));
}

function pearson(xs: readonly number[], ys: readonly number[]): number {
  const n = Math.min(xs.length, ys.length);
  if (n < 2) return Number.NaN;
  const mx = mean(xs.slice(0, n));
  const my = mean(ys.slice(0, n));
  let sxy = 0;
  let sxx = 0;
  let syy = 0;
  for (let i = 0; i < n; i += 1) {
    const dx = (xs[i] ?? 0) - mx;
    const dy = (ys[i] ?? 0) - my;
    sxy += dx * dy;
    sxx += dx * dx;
    syy += dy * dy;
  }
  return sxx > 0 && syy > 0 ? sxy / Math.sqrt(sxx * syy) : Number.NaN;
}

/** OLS slope of `ys` on `xs` — the attenuation coefficient in the regression sense. */
function slopeOf(xs: readonly number[], ys: readonly number[]): number {
  const n = Math.min(xs.length, ys.length);
  if (n < 2) return Number.NaN;
  const mx = mean(xs.slice(0, n));
  const my = mean(ys.slice(0, n));
  let sxy = 0;
  let sxx = 0;
  for (let i = 0; i < n; i += 1) {
    const dx = (xs[i] ?? 0) - mx;
    sxy += dx * ((ys[i] ?? 0) - my);
    sxx += dx * dx;
  }
  return sxx > 0 ? sxy / sxx : Number.NaN;
}

/** Monte-Carlo standard error of a mean, which is what "≈ 0 within error" has to be judged against. */
function seOfMean(xs: readonly number[]): number {
  return sd(xs) / Math.sqrt(xs.length);
}

// --- item pools ---------------------------------------------------------------

function repoRoot(): string {
  let dir = dirname(fileURLToPath(import.meta.url));
  for (let depth = 0; depth < 10; depth += 1) {
    if (existsSync(join(dir, 'pnpm-workspace.yaml'))) return dir;
    const parent = resolve(dir, '..');
    if (parent === dir) break;
    dir = parent;
  }
  throw new Error('learning-block harness: could not locate the workspace root');
}

const BANK_DIR = join(repoRoot(), 'research/exam-question-types/banks');

/**
 * Where a scrambled-control arm lives.
 *
 * `banks/` is the directory the app serves from, so the `perTrial` arm is deliberately not in it
 * (see the header of `generators/FLU-OPCHAIN-01.mjs`). Gate A still has to run BOTH arms through
 * this one driver — §4.1.1 requires the same driver, or the contrast is confounded with it — so the
 * harness names the control directory explicitly. This is research tooling: it never runs in the
 * app, and reaching a bank from here serves nothing to anybody.
 */
const CONTROL_BANK_DIR = join(repoRoot(), 'research/exam-question-types/control-banks');

function poolItem(itemId: string, typeCode: string, difficulty: number): BankItem {
  return {
    itemId,
    typeCode,
    domain: 'fluid_reasoning',
    difficulty,
    ageBands: ['4-5'] as AgeBand[],
    content: {},
    answer: { correctKey: 'A' },
    scoring: { mode: 'deterministic_key' },
    provenance: { generator: 'grammar' },
    syntheticOnly: true,
    validated: false,
  };
}

/**
 * An idealised pool on a fixed difficulty grid — E-095's "0.5-point item grid".
 *
 * This is the control condition for the harness itself: it isolates what the ESTIMATOR does from
 * what a particular bank's grid does to it. `perRung` has to exceed the block length divided by the
 * number of rungs the block visits, or the pool runs out and the comparison measures exhaustion.
 */
function gridPool(step: number, perRung: number): BankItem[] {
  const items: BankItem[] = [];
  for (let d = SCALE_MIN; d <= SCALE_MAX + 1e-9; d += step) {
    const difficulty = Math.round(d * 100) / 100;
    for (let i = 0; i < perRung; i += 1) {
      items.push(poolItem(`grid-${difficulty.toFixed(2)}-${i}`, 'GRID-IDEAL-01', difficulty));
    }
  }
  return items;
}

/** Resolve `--bank` as a path, a bank file stem, or a bare type code, in either bank directory. */
function resolveBankPath(ref: string): string {
  const candidates = [
    isAbsolute(ref) ? ref : resolve(process.cwd(), ref),
    join(BANK_DIR, ref),
    join(BANK_DIR, `${ref}.jsonl`),
    join(CONTROL_BANK_DIR, ref),
    join(CONTROL_BANK_DIR, `${ref}.jsonl`),
  ];
  for (const candidate of candidates) if (existsSync(candidate)) return candidate;
  const listing = (dir: string) =>
    existsSync(dir)
      ? readdirSync(dir)
          .filter((f) => f.endsWith('.jsonl'))
          .join(', ')
      : '(missing)';
  throw new Error(
    `no bank found for "${ref}".\n  banks/: ${listing(BANK_DIR)}\n  control-banks/: ${listing(CONTROL_BANK_DIR)}`,
  );
}

interface LoadedBank {
  label: string;
  path: string;
  items: BankItem[];
}

/**
 * The reference the harness uses when `--bank grid` is asked for: the idealised pool as a bank.
 *
 * Gate A takes a bank, and until now the bank-free control could only be reached through
 * `--calibrate`, which does not run the gate. That is the wrong way round for the question the gate
 * is for: A1 asks whether the PIPELINE manufactures a climb, and the only condition that settles
 * where a manufactured climb comes from is the one with no bank in it. `STAGE2_BANK_RECOVERY_MEASUREMENT`
 * §3.1 had to assemble that row by hand from a different code path; this makes it the same command.
 */
const GRID_BANK_REF = 'grid';

function loadBank(ref: string): LoadedBank {
  if (ref === GRID_BANK_REF) {
    return {
      label: 'ideal 0.5-point grid (no bank)',
      path: '(synthesised in-process — gridPool(0.5, 12))',
      items: gridPool(0.5, 12),
    };
  }
  const path = resolveBankPath(ref);
  const items: BankItem[] = [];
  for (const line of readFileSync(path, 'utf8').split('\n')) {
    const trimmed = line.trim();
    if (trimmed.length === 0) continue;
    const row = JSON.parse(trimmed) as Record<string, unknown>;
    const itemId = row['itemId'];
    const typeCode = row['typeCode'];
    const difficulty = row['difficulty'];
    if (typeof itemId !== 'string' || typeof typeCode !== 'string') continue;
    if (typeof difficulty !== 'number' || !Number.isFinite(difficulty)) continue;
    items.push(poolItem(itemId, typeCode, difficulty));
  }
  if (items.length === 0) throw new Error(`bank ${path} yielded no usable items`);
  return { label: ref, path, items };
}

/**
 * Which bank file an arm reads, given a `--bank` reference and a `--mode`.
 *
 * A dual-mode pair is the bare `<CODE>.jsonl` in `banks/` (the consistent arm, which is the one the
 * app serves) plus `<CODE>.perTrial.jsonl` in `control-banks/`. A reference naming either arm, or
 * naming neither, resolves to the requested one; a single-arm bank ignores the mode.
 */
function bankRefForMode(ref: string, mode: Persistence): string {
  if (ref === GRID_BANK_REF) return ref;
  const stem = ref.replace(/\.jsonl$/, '').replace(/\.(consistent|perTrial)$/, '');
  if (mode === 'perTrial') {
    const control = `${stem}.perTrial`;
    return existsSync(join(CONTROL_BANK_DIR, `${control}.jsonl`)) ? control : ref;
  }
  return existsSync(join(BANK_DIR, `${stem}.jsonl`)) ? stem : ref;
}

// --- one block ----------------------------------------------------------------

type Persistence = 'consistent' | 'perTrial';

interface ChildSpec {
  /** Ability at trial 0, on the [1, 20] scale. */
  theta0: number;
  /** True climb in scale points per trial. */
  lambda: number;
  /**
   * The settled standing estimate handed over from Phase 1. Deliberately NOT equal to `theta0`:
   * §4.4 of the design doc names regression to the mean at the handover as a source of spurious λ,
   * and E-095's sweep included the same noise, so a harness without it would flatter the estimator.
   */
  standing: number;
  seed: string;
}

interface BlockRun {
  trials: LearningTrial[];
  served: { difficulty: number; target: number; correct: boolean }[];
  /** True when the pool ran out before the requested length — reportable, never silent. */
  exhausted: boolean;
}

interface Responder {
  slope: number;
  /** Lower asymptote of the response curve. The item's real pseudo-guessing floor, not the fit's. */
  guessing: number;
}

/**
 * What the ESTIMATOR assumes, held separately from what the child actually does.
 *
 * Two floors rather than one because the block runs the estimator twice per trial in two different
 * roles, and they can be corrected independently. `readout` is the floor the reported fit uses;
 * `targeting` is the floor `nextTargetTheta` uses when it re-fits to choose the next difficulty.
 * Correcting only the first leaves the difficulty walk itself still driven by a misspecified fit,
 * and the walk is half the mechanism — so an arm that changes one and not the other is a distinct,
 * measurable remedy rather than a variation on the same one.
 */
interface FitSpec {
  readonly readout: number;
  readonly targeting: number;
}

/**
 * Which rule chooses the difficulty of the next trial. `level` is what ships.
 *
 * The other three are diagnostics, not administration options, and they exist because the
 * differences between them are the whole of D-206:
 *
 * - `projecting` is the rule the block shipped with before D-206 — aim at `theta0 + lambda * t`,
 *   the ability PROJECTED for the next trial. It closes a loop from the estimate of `lambda` back
 *   onto the design that identifies `lambda`. Kept so the before/after can be run at matched seeds
 *   in one version of this harness; a comparison across two harness versions would be confounded
 *   with the harness.
 * - `level-plain` is D-206 as first drafted: the level fit plus the offset, with no accuracy
 *   correction on top. It removes the loop but lags a climbing child, and the size of that lag is
 *   what the correction in `level` was added to fix. Kept so the correction's cost is measurable
 *   against the thing it was added to rather than against the rule two revisions back.
 * - `frozen` holds the difficulty at `standing + offset` for the whole block. It is the open-loop
 *   bound: the block still uses the real fit, but nothing the fit says reaches what gets served. It
 *   is the only way to separate what the ESTIMATOR does from what the LOOP does.
 */
type TargetingRule = 'level' | 'level-plain' | 'projecting' | 'frozen';

/** The rule D-206 replaced, kept here rather than in the estimator so the shipped path has one. */
function projectingTargetTheta(
  trials: readonly LearningTrial[],
  standing: number,
  fitGuessing: number,
): number {
  if (trials.length < MIN_TRIALS_FOR_PROJECTION) {
    return clamp(standing + TARGET_OFFSET, SCALE_MIN, SCALE_MAX);
  }
  const fit = estimateLearningCurve(trials, {
    slope: SLOPE,
    priorTheta0Mean: standing,
    guessing: fitGuessing,
  });
  return clamp(fit.theta0 + fit.lambda * trials.length + TARGET_OFFSET, SCALE_MIN, SCALE_MAX);
}

/**
 * Administer one novel block, using the shipped administration path end to end.
 *
 * The engine picks the item (`selectNextNovelItem`), the scorer picks the difficulty to aim at
 * (`nextTargetTheta`), and the simulated child answers under a 1PL with an explicit guessing floor.
 * Nothing about the block is pre-scripted: the difficulty walk is whatever the targeting rule and
 * the bank's grid produce together, which is the only reason the run says anything about the bank.
 */
function runBlock(
  pool: readonly BankItem[],
  child: ChildSpec,
  length: number,
  responder: Responder,
  fit: FitSpec,
  targeting: TargetingRule,
  selectionSeed: number,
): BlockRun {
  const rng = makeRng(`response|${child.seed}`);
  const trials: LearningTrial[] = [];
  const served: BlockRun['served'] = [];
  const administered: string[] = [];
  let exhausted = false;

  for (let t = 0; t < length; t += 1) {
    let target: number;
    if (targeting === 'frozen') {
      target = clamp(child.standing + TARGET_OFFSET, SCALE_MIN, SCALE_MAX);
    } else if (targeting === 'projecting') {
      target = projectingTargetTheta(trials, child.standing, fit.targeting);
    } else if (targeting === 'level-plain') {
      target =
        trials.length < MIN_TRIALS_FOR_PROJECTION
          ? clamp(child.standing + TARGET_OFFSET, SCALE_MIN, SCALE_MAX)
          : clamp(
              estimateBlockLevel(trials, {
                slope: SLOPE,
                priorTheta0Mean: child.standing,
                guessing: fit.targeting,
              }) + TARGET_OFFSET,
              SCALE_MIN,
              SCALE_MAX,
            );
    } else {
      target = nextTargetTheta(trials, {
        standingEstimate: child.standing,
        targetOffset: TARGET_OFFSET,
        slope: responder.slope,
        guessing: fit.targeting,
      });
    }
    const item = selectNextNovelItem(pool, administered, target, selectionSeed);
    if (item === null) {
      exhausted = true;
      break;
    }
    administered.push(item.itemId);

    const ability = child.theta0 + child.lambda * t;
    const star = 1 / (1 + Math.exp(-responder.slope * (ability - item.difficulty)));
    const p = responder.guessing + (1 - responder.guessing) * star;
    const correct = rng() < p;

    trials.push({ difficulty: item.difficulty, score: correct ? 1 : 0, trialIndex: t });
    served.push({ difficulty: item.difficulty, target, correct });
  }

  return { trials, served, exhausted };
}

// --- a cohort -----------------------------------------------------------------

interface CohortOptions {
  pool: readonly BankItem[];
  children: number;
  length: number;
  lambdaMean: number;
  lambdaSd: number;
  /** SD of the noise on the standing handover, in scale points. */
  standingNoise: number;
  theta0Mean: number;
  theta0Sd: number;
  responder: Responder;
  fit: FitSpec;
  /** Which rule chooses the next difficulty. Defaults to the shipped one. See {@link TargetingRule}. */
  targeting?: TargetingRule;
  /**
   * Contamination floor to declare on `A2_REFERENCE` for the third readout pass, which is how the
   * cost of the evidence bar gets measured. Supplied from the matching λ_true = 0 run, so the bar is
   * always the floor this arm actually manufactures rather than a figure chosen to look good.
   */
  barFloor?: number;
  seed: number;
}

interface CohortResult {
  n: number;
  length: number;
  trueLambda: number[];
  fitLambda: number[];
  fitLambdaSe: number[];
  /** Mean served difficulty over the final third — §4.1.1's manipulation check observable. */
  lateDifficulty: number[];
  /** Highest difficulty served to each child, for the saturation check (A3). */
  peakDifficulty: number[];
  /** Highest difficulty each child's targeting rule ASKED for, before the pool had its say. */
  peakDemand: number[];
  /** Fraction of children whose readout came back `above` against a separable reference. */
  aboveRate: number;
  /**
   * Fraction whose readout declined to name a band at all, against the same separable reference.
   *
   * The cost side of every remedy below. A fix that restores λ̄ = 0 by widening the posterior until
   * nothing is reportable has not made the measurement honest, it has removed it, and only this
   * column distinguishes the two.
   */
  indeterminateRate: number;
  /** Same, against {@link NARROW_REFERENCE} — the reportability question rather than the band. */
  narrowIndeterminateRate: number;
  /** Same, against the SD 0.15 reference WITH this arm's own contamination floor declared. */
  barIndeterminateRate: number;
  exhaustedCount: number;
  poolMax: number;
  shortBlocks: number;
}

/**
 * A separable reference, used ONLY to count false `above` verdicts for Gate A's A2.
 *
 * Deliberately not an honest reference: at 30 trials an honest narrow reference returns
 * `indeterminate` for everybody (E-095), which would make A2 vacuously pass. `sd: 0.15` is the
 * smallest spread at which the bands separate at this length, which is the same device
 * `exam-phase2-demo.ts` calls its "wide reference" and flags as not a claim about children.
 *
 * `contaminationFloor: 0` is not a claim that there is no contamination — E-200 measures plenty. It
 * is what makes A2 a measurement of the pipeline's false-`above` rate rather than a measurement of
 * the bar: with the floor declared, the readout would refuse to name any band at this length and A2
 * would pass on every bank ever built. The `--fix-probe` table reports the bar's cost separately.
 */
const A2_REFERENCE = { mean: 0, sd: 0.15, contaminationFloor: 0 } as const;

/**
 * The reference the project's own synthetic work actually used: centre 0.06, SD 0.03.
 *
 * Carried alongside `A2_REFERENCE` so every remedy is costed against BOTH the widest reference
 * anyone has proposed and the only one with a stated provenance. The two answer different questions.
 * Against `A2_REFERENCE` a remedy can be judged on how often it names a band; against this one the
 * answer is expected to be "never", and a remedy that changed that would be the surprise.
 */
const NARROW_REFERENCE = { mean: 0.06, sd: 0.03, contaminationFloor: 0 } as const;

function runCohort(options: CohortOptions): CohortResult {
  const {
    pool,
    children,
    length,
    lambdaMean,
    lambdaSd,
    standingNoise,
    theta0Mean,
    theta0Sd,
    responder,
    fit: fitSpec,
    targeting = 'level',
    barFloor = 0,
    seed,
  } = options;

  const rng = makeRng(`cohort|${seed}|${length}|${lambdaMean}|${lambdaSd}|${standingNoise}`);
  const trueLambda: number[] = [];
  const fitLambda: number[] = [];
  const fitLambdaSe: number[] = [];
  const lateDifficulty: number[] = [];
  const peakDifficulty: number[] = [];
  const peakDemand: number[] = [];
  let aboveCount = 0;
  let indeterminateCount = 0;
  let narrowIndeterminateCount = 0;
  let barIndeterminateCount = 0;
  let exhaustedCount = 0;
  let shortBlocks = 0;

  for (let c = 0; c < children; c += 1) {
    const theta0 = clamp(normal(rng, theta0Mean, theta0Sd), SCALE_MIN, SCALE_MAX);
    const lambda = lambdaSd > 0 ? normal(rng, lambdaMean, lambdaSd) : lambdaMean;
    const standing = clamp(theta0 + normal(rng, 0, standingNoise), SCALE_MIN, SCALE_MAX);
    const child: ChildSpec = { theta0, lambda, standing, seed: `${seed}|${length}|${c}` };

    const run = runBlock(pool, child, length, responder, fitSpec, targeting, seed);
    if (run.exhausted) exhaustedCount += 1;
    if (run.trials.length < length) shortBlocks += 1;
    if (run.trials.length === 0) continue;

    const fit = estimateLearningCurve(run.trials, {
      slope: responder.slope,
      priorTheta0Mean: child.standing,
      guessing: fitSpec.readout,
    });
    trueLambda.push(lambda);
    fitLambda.push(fit.lambda);
    fitLambdaSe.push(fit.lambdaSe);

    const cut = Math.floor((2 * run.served.length) / 3);
    lateDifficulty.push(mean(run.served.slice(cut).map((s) => s.difficulty)));
    peakDifficulty.push(Math.max(...run.served.map((s) => s.difficulty)));
    peakDemand.push(Math.max(...run.served.map((s) => s.target)));

    const readout = learningRateReadout(run.trials, {
      reference: A2_REFERENCE,
      minTrials: length,
      fit: { slope: responder.slope, guessing: fitSpec.readout },
    });
    if (readout.band === 'above') aboveCount += 1;
    if (readout.band === 'indeterminate') indeterminateCount += 1;

    const narrow = learningRateReadout(run.trials, {
      reference: NARROW_REFERENCE,
      minTrials: length,
      fit: { slope: responder.slope, guessing: fitSpec.readout },
    });
    if (narrow.band === 'indeterminate') narrowIndeterminateCount += 1;

    const barred = learningRateReadout(run.trials, {
      reference: { ...A2_REFERENCE, contaminationFloor: barFloor },
      minTrials: length,
      fit: { slope: responder.slope, guessing: fitSpec.readout },
    });
    if (barred.band === 'indeterminate') barIndeterminateCount += 1;
  }

  return {
    n: fitLambda.length,
    length,
    trueLambda,
    fitLambda,
    fitLambdaSe,
    lateDifficulty,
    peakDifficulty,
    peakDemand,
    aboveRate: fitLambda.length === 0 ? Number.NaN : aboveCount / fitLambda.length,
    indeterminateRate: fitLambda.length === 0 ? Number.NaN : indeterminateCount / fitLambda.length,
    narrowIndeterminateRate:
      fitLambda.length === 0 ? Number.NaN : narrowIndeterminateCount / fitLambda.length,
    barIndeterminateRate:
      fitLambda.length === 0 ? Number.NaN : barIndeterminateCount / fitLambda.length,
    exhaustedCount,
    poolMax: Math.max(...pool.map((i) => i.difficulty)),
    shortBlocks,
  };
}

// --- reporting ----------------------------------------------------------------

function f(x: number, places = 3): string {
  return Number.isFinite(x) ? x.toFixed(places) : 'n/a';
}

function recoveryRow(result: CohortResult): {
  length: number;
  r: number;
  meanSe: number;
  attenuationRatio: number;
  attenuationSlope: number;
  fitLambdaSd: number;
} {
  const trueMean = mean(result.trueLambda);
  return {
    length: result.length,
    r: pearson(result.trueLambda, result.fitLambda),
    meanSe: mean(result.fitLambdaSe),
    // Two readings of "attenuation", because E-095 quotes one number ("fit/true") and does not say
    // which. They diverge when the prior shrinks the spread differently from the mean, and a
    // reproduction that reported only the agreeing one would be choosing its own evidence.
    attenuationRatio: trueMean === 0 ? Number.NaN : mean(result.fitLambda) / trueMean,
    attenuationSlope: slopeOf(result.trueLambda, result.fitLambda),
    fitLambdaSd: sd(result.fitLambda),
  };
}

interface Settings {
  children: number;
  length: number;
  lambdaMean: number;
  lambdaSd: number;
  standingNoise: number;
  theta0Mean: number;
  theta0Sd: number;
  guessing: number;
  /**
   * Whether `--guessing` was supplied. `--fix-probe` needs a responder that actually has a floor,
   * or every arm is comparing corrections against a truth of zero; it defaults its own responder to
   * the five-option floor, and this is how it tells "not supplied" from an explicit `--guessing 0`.
   */
  guessingExplicit: boolean;
  fitGuessing: number;
  targetGuessing: number;
  /** Which rule chooses the next difficulty. Diagnostic; `level` is what the block administers. */
  targeting: TargetingRule;
  seed: number;
  /**
   * Every seed Gate A should be run at. One cell of 400 children carries about ±0.04 of noise on
   * `r` and ±0.0033 on the null-cohort λ̄ (`STAGE2_BANK_RECOVERY_MEASUREMENT` §9), which is wider
   * than several differences worth reporting, so a single-seed Gate A cannot settle whether A1
   * passes. Supplying more than one prints a replication block alongside the per-seed reports.
   */
  seeds: number[];
  bank: string | null;
  mode: Persistence;
  json: boolean;
  calibrate: boolean;
  gateA: boolean;
  noiseSweep: boolean;
  guessingProbe: boolean;
  fixProbe: boolean;
}

function parseArgs(argv: readonly string[]): Settings {
  const flag = (name: string): string | null => {
    const index = argv.indexOf(`--${name}`);
    return index >= 0 ? (argv[index + 1] ?? null) : null;
  };
  const num = (name: string, fallback: number): number => {
    const raw = flag(name);
    if (raw === null) return fallback;
    const parsed = Number(raw);
    if (!Number.isFinite(parsed)) throw new Error(`--${name} expects a number, got "${raw}"`);
    return parsed;
  };
  const modeRaw = flag('mode') ?? 'consistent';
  if (modeRaw !== 'consistent' && modeRaw !== 'perTrial') {
    throw new Error(`--mode expects consistent|perTrial, got "${modeRaw}"`);
  }
  const targetingRules: readonly TargetingRule[] = ['level', 'level-plain', 'projecting', 'frozen'];
  const targetingRaw = flag('targeting') ?? 'level';
  if (!targetingRules.includes(targetingRaw as TargetingRule)) {
    throw new Error(`--targeting expects ${targetingRules.join('|')}, got "${targetingRaw}"`);
  }
  const seed = num('seed', 20260730);
  const seedsRaw = flag('seeds');
  const seeds =
    seedsRaw === null
      ? [seed]
      : seedsRaw.split(',').map((part) => {
          const parsed = Number(part.trim());
          if (!Number.isFinite(parsed)) throw new Error(`--seeds expects numbers, got "${part}"`);
          return parsed;
        });

  return {
    children: num('children', 400),
    length: num('length', RECOMMENDED_NOVEL_BLOCK_LENGTH),
    lambdaMean: num('lambda-mean', 0.06),
    lambdaSd: num('lambda-sd', 0.03),
    // 1.5 scale points, the `stabilitySd` the engine calls a settled estimate. E-095 says only
    // "deliberately noisy"; this is the repo's own figure for how noisy "settled" is.
    standingNoise: num('standing-noise', 1.5),
    theta0Mean: num('theta0-mean', 10.5),
    theta0Sd: num('theta0-sd', 3),
    guessing: num('guessing', 0),
    guessingExplicit: argv.includes('--guessing'),
    fitGuessing: num('fit-guessing', DEFAULT_GUESSING),
    targetGuessing: num('target-guessing', DEFAULT_GUESSING),
    targeting: targetingRaw as TargetingRule,
    seed,
    seeds,
    bank: flag('bank'),
    mode: modeRaw,
    json: argv.includes('--json'),
    calibrate: argv.includes('--calibrate'),
    gateA: argv.includes('--gate-a'),
    noiseSweep: argv.includes('--noise-sweep'),
    guessingProbe: argv.includes('--guessing-probe'),
    fixProbe: argv.includes('--fix-probe'),
  };
}

function cohortOptionsFor(
  settings: Settings,
  pool: readonly BankItem[],
  overrides: Partial<CohortOptions> = {},
): CohortOptions {
  return {
    pool,
    children: settings.children,
    length: settings.length,
    lambdaMean: settings.lambdaMean,
    lambdaSd: settings.lambdaSd,
    standingNoise: settings.standingNoise,
    theta0Mean: settings.theta0Mean,
    theta0Sd: settings.theta0Sd,
    responder: { slope: SLOPE, guessing: settings.guessing },
    fit: { readout: settings.fitGuessing, targeting: settings.targetGuessing },
    targeting: settings.targeting,
    seed: settings.seed,
    ...overrides,
  };
}

// --- calibration: does the harness reproduce E-095? ---------------------------

interface CalibrationRow {
  pool: string;
  length: number;
  r: number;
  meanSe: number;
  attenuationRatio: number;
  attenuationSlope: number;
  publishedR: number;
  publishedSe: number;
  publishedAttenuation: number;
}

function calibrate(settings: Settings): { rows: CalibrationRow[]; verdict: string[] } {
  const pools: { label: string; items: BankItem[] }[] = [
    { label: 'ideal 0.5-point grid', items: gridPool(0.5, 12) },
    { label: `bank ${REFERENCE_BANK}`, items: loadBank(REFERENCE_BANK).items },
  ];

  const rows: CalibrationRow[] = [];
  for (const pool of pools) {
    for (const length of LENGTH_LADDER) {
      const result = runCohort(cohortOptionsFor(settings, pool.items, { length }));
      const row = recoveryRow(result);
      const published = E095[length];
      rows.push({
        pool: pool.label,
        length,
        r: row.r,
        meanSe: row.meanSe,
        attenuationRatio: row.attenuationRatio,
        attenuationSlope: row.attenuationSlope,
        publishedR: published.r,
        publishedSe: published.meanSe,
        publishedAttenuation: published.attenuation,
      });
    }
  }

  const verdict: string[] = [];
  for (const row of rows.filter((r) => r.length === 30)) {
    const dR = Math.abs(row.r - row.publishedR);
    const dSe = Math.abs(row.meanSe - row.publishedSe);
    const dAtt = Math.min(
      Math.abs(row.attenuationRatio - row.publishedAttenuation),
      Math.abs(row.attenuationSlope - row.publishedAttenuation),
    );
    const ok =
      dR <= E095_TOLERANCE.r && dSe <= E095_TOLERANCE.meanSe && dAtt <= E095_TOLERANCE.attenuation;
    verdict.push(
      `${ok ? 'MATCH' : 'DIVERGES'}  ${row.pool} at 30 trials: ` +
        `|Δr| ${f(dR)} (tol ${E095_TOLERANCE.r}), |ΔSE| ${f(dSe)} (tol ${E095_TOLERANCE.meanSe}), ` +
        `|Δattenuation| ${f(dAtt)} (tol ${E095_TOLERANCE.attenuation})`,
    );
  }
  return { rows, verdict };
}

// --- Gate A -------------------------------------------------------------------

interface GateACheck {
  id: 'A1' | 'A2' | 'A3' | 'A4';
  name: string;
  pass: boolean;
  observed: string;
  condition: string;
  meaningOfFailure: string;
}

interface GateAReport {
  bank: string;
  path: string;
  mode: Persistence;
  items: number;
  difficultySpan: [number, number];
  distinctRungs: number;
  guessing: number;
  checks: GateACheck[];
  /** Fitted-λ SD on this bank, which U1's power script needs instead of the doc's 0.06 estimate. */
  fitLambdaSd: number;
  recovery: ReturnType<typeof recoveryRow>;
  nullMean: number;
  nullSe: number;
}

/**
 * Gate A (§4.1.2) on one bank in one mode.
 *
 * A1 is the check that earns its keep: a cohort with no learning at all must fit λ̄ = 0. A2 asks
 * whether the readout would call those non-learners fast. A3 asks whether the pool has the headroom
 * §1.1(c) requires. A4 asks whether the bank's grid supports the estimator at all, and also MEASURES
 * the fitted-λ SD the Gate B power calculation depends on.
 */
function gateA(settings: Settings, bank: LoadedBank, mode: Persistence): GateAReport {
  const pool = bank.items;

  // A1 / A2 — a cohort with λ_true = 0 for every child. No spread, so any fitted spread is the
  // pipeline's own.
  const nullCohort = runCohort(
    cohortOptionsFor(settings, pool, { lambdaMean: 0, lambdaSd: 0, length: settings.length }),
  );
  const nullMean = mean(nullCohort.fitLambda);
  const nullSe = seOfMean(nullCohort.fitLambda);
  const a1Pass = Math.abs(nullMean) <= 2 * nullSe;

  // The nominal rate is the tail mass beyond the band edge under the reference used, which for a
  // half-width of 0.5 SD is ~0.309 in a normal. A pipeline that manufactures nothing should sit
  // well under it; this asks only that it does not EXCEED it.
  const nominalAboveRate = 0.309;
  const a2Pass = nullCohort.aboveRate <= nominalAboveRate;

  // A3 — the fastest learner the design contemplates must not pin to the top of the pool.
  //
  // Split into two causes, because §4.1.2 states A3 as one check and it is two. A child pins at the
  // pool maximum either because the BANK stops below what the targeting rule asked for — which is
  // the §1.1(c) headroom defect A3 exists to catch and is fixable by generating deeper items — or
  // because the targeting rule asked for a difficulty ABOVE 20 and `nextTargetTheta` clamped it to
  // the scale. The second is a property of the [1, 20] scale, so no bank can fix it, and charging it
  // to the bank would make A3 unpassable for any cohort containing high-standing children. Only the
  // first is a failure. The second is reported as a stated boundary. See the deviation note below.
  const fastCohort = runCohort(
    cohortOptionsFor(settings, pool, {
      lambdaMean: 0.15,
      lambdaSd: 0,
      length: settings.length,
      children: Math.max(40, Math.floor(settings.children / 4)),
    }),
  );
  const poolMax = Math.max(...pool.map((i) => i.difficulty));
  let bankLimited = 0;
  let scaleLimited = 0;
  for (let i = 0; i < fastCohort.peakDifficulty.length; i += 1) {
    if ((fastCohort.peakDifficulty[i] ?? 0) < poolMax - 1e-9) continue;
    // The demand is clamped to SCALE_MAX by `nextTargetTheta`, so a child sitting AT the clamp is
    // one the scale cut off, not one the bank ran out on.
    if ((fastCohort.peakDemand[i] ?? 0) >= SCALE_MAX - 1e-9) scaleLimited += 1;
    else bankLimited += 1;
  }
  const a3Pass = bankLimited === 0 && fastCohort.exhaustedCount === 0;

  // A4 — recovery on this bank's actual grid, against E-095's 30-trial figures.
  const recoveryCohort = runCohort(cohortOptionsFor(settings, pool, { length: settings.length }));
  const recovery = recoveryRow(recoveryCohort);
  const published = settings.length === 30 ? E095[30] : null;
  const a4Pass =
    published !== null &&
    Math.abs(recovery.r - published.r) <= E095_TOLERANCE.r &&
    Math.abs(recovery.meanSe - published.meanSe) <= E095_TOLERANCE.meanSe;

  const difficulties = pool.map((i) => i.difficulty);
  const rungs = new Set(difficulties.map((d) => Math.round(d * 2) / 2));

  return {
    bank: bank.label,
    path: bank.path,
    mode,
    items: pool.length,
    difficultySpan: [Math.min(...difficulties), Math.max(...difficulties)],
    distinctRungs: rungs.size,
    guessing: settings.guessing,
    fitLambdaSd: recovery.fitLambdaSd,
    recovery,
    nullMean,
    nullSe,
    checks: [
      {
        id: 'A1',
        name: 'static-child null',
        pass: a1Pass,
        observed: `fitted λ̄ = ${f(nullMean, 4)} ± ${f(nullSe, 4)} (Monte-Carlo SE) over ${nullCohort.n} children`,
        condition: 'fitted λ distribution centred on 0 within Monte-Carlo error (|λ̄| ≤ 2 SE)',
        meaningOfFailure:
          'the ladder itself produces a climb — almost always trial-index-correlated difficulty ' +
          'misspecification (§1.1(d)), occasionally pool saturation',
      },
      {
        id: 'A2',
        name: 'false-positive rate',
        pass: a2Pass,
        observed: `${f(100 * nullCohort.aboveRate, 1)}% of static children read "above" (nominal ${f(100 * nominalAboveRate, 1)}%)`,
        condition: '`learningRateReadout` returns `above` no more often than the nominal band rate',
        meaningOfFailure: 'the readout would call non-learners fast learners',
      },
      {
        id: 'A3',
        name: 'no saturation',
        pass: a3Pass,
        observed:
          `fastest simulated learner (λ = 0.15), ${fastCohort.peakDifficulty.length} children: ` +
          `${bankLimited} pinned at the pool maximum ${f(poolMax, 2)} with the bank short of what was asked for; ` +
          `${scaleLimited} pinned because the projection hit the ${SCALE_MAX}-point scale ceiling (not a bank defect); ` +
          `${fastCohort.exhaustedCount} block(s) ran out of items`,
        condition:
          'no child is served the pool maximum while the targeting rule asked for more, and no block exhausts',
        meaningOfFailure:
          'headroom is short of §1.1(c), so the top of the λ distribution would be truncated',
      },
      {
        id: 'A4',
        name: 'recovery sanity',
        pass: a4Pass,
        observed:
          `r = ${f(recovery.r)} (E-095 ${f(published?.r ?? Number.NaN)}), ` +
          `mean SE = ${f(recovery.meanSe)} (E-095 ${f(published?.meanSe ?? Number.NaN)}), ` +
          `attenuation ratio ${f(recovery.attenuationRatio)} / slope ${f(recovery.attenuationSlope)}, ` +
          `fitted-λ SD = ${f(recovery.fitLambdaSd, 4)}`,
        condition: `recovery and mean SE within ±${E095_TOLERANCE.r} / ±${E095_TOLERANCE.meanSe} of E-095 at 30 trials`,
        meaningOfFailure:
          "the bank's grid is too coarse or too shallow to support the estimator at all",
      },
    ],
  };
}

// --- CLI ----------------------------------------------------------------------

function printSettings(settings: Settings): void {
  console.log(
    `Simulation: ${settings.children} children/cell, λ ~ N(${settings.lambdaMean}, ${settings.lambdaSd}²), ` +
      `θ0 ~ N(${settings.theta0Mean}, ${settings.theta0Sd}²), handover noise SD ${settings.standingNoise}, ` +
      `slope ${SLOPE}, target offset +${TARGET_OFFSET}, responder guessing floor ${settings.guessing}, ` +
      `estimator floor ${settings.fitGuessing} (readout) / ${settings.targetGuessing} (targeting), ` +
      `targeting rule ${settings.targeting}, seed ${settings.seed}.`,
  );
}

function printCalibration(settings: Settings): CalibrationRow[] {
  console.log('\n## U0 calibration — does the harness reproduce E-095?\n');
  printSettings(settings);
  console.log(
    '\nE-095 was measured on an idealised 0.5-point grid. The bank row is the same simulation on a\n' +
      'real bank, and the difference between the two rows IS the effect of a bank\u2019s grid.\n',
  );

  const { rows, verdict } = calibrate(settings);
  console.log('| pool | trials | r | E-095 r | mean SE | E-095 SE | atten. ratio | atten. slope |');
  console.log('| --- | --- | --- | --- | --- | --- | --- | --- |');
  for (const row of rows) {
    console.log(
      `| ${row.pool} | ${row.length} | ${f(row.r)} | ${f(row.publishedR)} | ${f(row.meanSe)} | ` +
        `${f(row.publishedSe)} | ${f(row.attenuationRatio)} | ${f(row.attenuationSlope)} |`,
    );
  }

  console.log('\nAgainst the 30-trial cell, which is the acceptance criterion for U0:');
  for (const line of verdict) console.log(`  ${line}`);

  const zero = runCohort(
    cohortOptionsFor(settings, gridPool(0.5, 12), { lambdaMean: 0, lambdaSd: 0, length: 30 }),
  );
  const zeroMean = mean(zero.fitLambda);
  const zeroSe = seOfMean(zero.fitLambda);
  console.log(
    `\nUnbiasedness of the harness itself (λ_true = 0 for every child, ideal grid, 30 trials):\n` +
      `  fitted λ̄ = ${f(zeroMean, 4)} ± ${f(zeroSe, 4)}  ->  ` +
      `${Math.abs(zeroMean) <= 2 * zeroSe ? 'CENTRED ON ZERO' : 'BIASED — do not trust it on a bank'}`,
  );

  console.log(
    '\nUNDERSPECIFIED, and worth stating plainly: the sweep that produced E-095 is not in the\n' +
      'repository, and the register records neither the θ0 distribution nor the handover-noise SD it\n' +
      'used. The figures above are a re-implementation from the published description, so agreement\n' +
      'is evidence the description is reproducible — not a re-run. `--noise-sweep` shows how much of\n' +
      'the 30-trial cell moves with the one parameter that was not written down.',
  );
  return rows;
}

/**
 * What the estimator's `guessing = 0` does to a child who is not learning.
 *
 * `learning-curve.ts` documents `guessing: 0` as a known misspecification and predicts, in §4.6 of
 * the design document, that lucky early successes "inflate `theta0` and flatten `lambda`". Run
 * against a responder that actually has a five-option floor, the sign comes out the other way, and
 * the reason is the targeting loop the block adds on top of the fit: a fit that reads chance
 * successes as ability raises `theta0`, `nextTargetTheta` then aims higher, the served difficulty
 * climbs across trials, and the fit reads that climb as learning. §4.6 reasoned about the fit
 * standing still; inside an adaptive block the loop closes and reverses the sign.
 *
 * This probe exists so the finding is a command rather than a paragraph. It is a property of the
 * estimator and the targeting rule, not of any bank, so it runs the ideal grid alongside whatever
 * banks are named — and the ideal grid is the row that settles the attribution.
 */
function printGuessingProbe(settings: Settings, bankRefs: readonly string[]): void {
  console.log('\n## What a static child fits when the responder has a guessing floor\n');
  console.log(
    'Every row is a cohort with λ_true = 0 for EVERY child — no learning whatsoever. The estimator\n' +
      'is pinned at `guessing = 0` in BOTH roles (readout fit and targeting re-fit), which is what it\n' +
      'shipped with; only the simulated responder\u2019s floor changes. A1 asks for λ̄ = 0, so any row\n' +
      'that is not zero is the pipeline manufacturing a climb. `--fix-probe` costs the remedies.\n',
  );
  console.log('| pool | responder floor | fitted λ̄ | Monte-Carlo SE | false `above` rate |');
  console.log('| --- | --- | --- | --- | --- |');

  const pools: { label: string; items: BankItem[] }[] = [
    { label: 'ideal 0.5-point grid (no bank)', items: gridPool(0.5, 12) },
    ...bankRefs.map((ref) => {
      const bank = loadBank(ref);
      return { label: bank.label, items: bank.items };
    }),
  ];

  for (const pool of pools) {
    for (const guessing of [0, 0.2]) {
      const cohort = runCohort(
        cohortOptionsFor(settings, pool.items, {
          lambdaMean: 0,
          lambdaSd: 0,
          length: 30,
          responder: { slope: SLOPE, guessing },
          fit: { readout: 0, targeting: 0 },
        }),
      );
      const m = mean(cohort.fitLambda);
      console.log(
        `| ${pool.label} | ${guessing.toFixed(1)} | ${f(m, 4)} | ${f(seOfMean(cohort.fitLambda), 4)} | ` +
          `${f(100 * cohort.aboveRate, 1)}% |`,
      );
    }
  }

  console.log(
    '\nThe ideal-grid rows carry the attribution: with no bank involved at all, a five-option floor\n' +
      'moves a non-learner from λ̄ ≈ 0 to λ̄ ≈ 0.04, which is a large fraction of the 0.06 reference\n' +
      'mean this project uses as a plausible centre. That is a MEASUREMENT decision for the owner —\n' +
      "§8.4's \u201Cdecision on the guessing floor\u201D — and no item design can remove it. A bank can only\n" +
      'avoid making it worse.',
  );
}

/**
 * Every candidate remedy for the floor misspecification, costed on the same cohort.
 *
 * Each arm is run twice against the same seeds: once on a cohort with λ_true = 0 for every child,
 * which measures what the arm MANUFACTURES, and once on the λ ~ N(mean, sd²) cohort, which measures
 * what it COSTS. Reporting either alone is how a remedy gets adopted on half its evidence — a floor
 * that fixes the null by widening the posterior until nothing is reportable would look perfect in
 * the first table and is useless.
 *
 * The `indet` column is against `A2_REFERENCE` (SD 0.15), the widest reference anyone has proposed
 * and the only one at which bands separate at all at 30 trials. Against an honest narrow reference
 * every arm here is 100% indeterminate, including the status quo, so that column would not
 * discriminate between them.
 */
function printFixProbe(settings: Settings, bankRefs: readonly string[]): void {
  const truth = settings.guessingExplicit ? settings.guessing : DEFAULT_GUESSING;

  console.log('\n## Costing the remedies\n');
  console.log(
    `Responder floor is pinned at ${truth.toFixed(2)} for every arm — a real five-option item — and only what the\n` +
      'ESTIMATOR assumes changes. `fit c` is the floor the reported fit uses; `target c` is the floor\n' +
      '`nextTargetTheta` uses when it re-fits to pick the next difficulty. The null columns are a\n' +
      'cohort with λ_true = 0 for every child; the recovery columns are the same arm on a cohort with\n' +
      `λ ~ N(${settings.lambdaMean}, ${settings.lambdaSd}²).\n`,
  );

  interface Arm {
    label: string;
    fit: FitSpec;
    length: number;
    /** Responder floor, when an arm is probing what a WRONG assumed floor costs. */
    responderGuessing?: number;
    targeting?: TargetingRule;
  }

  const projecting: TargetingRule = 'projecting';
  const arms: Arm[] = [
    {
      label: 'pre-D-200 (c = 0 both, projecting)',
      fit: { readout: 0, targeting: 0 },
      length: 30,
      targeting: projecting,
    },
    {
      label: 'D-200 fit only (c = 0.2 readout, projecting)',
      fit: { readout: 0.2, targeting: 0 },
      length: 30,
      targeting: projecting,
    },
    {
      label: 'D-200 fit + targeting (c = 0.2, projecting)',
      fit: { readout: 0.2, targeting: 0.2 },
      length: 30,
      targeting: projecting,
    },
    {
      label: 'D-206 part 1 only: level, no accuracy correction',
      fit: { readout: 0.2, targeting: 0.2 },
      length: 30,
      targeting: 'level-plain',
    },
    {
      label: 'D-206 shipped: c = 0.2, level + accuracy correction',
      fit: { readout: 0.2, targeting: 0.2 },
      length: 30,
    },
    { label: 'D-206 level targeting, c = 0 both', fit: { readout: 0, targeting: 0 }, length: 30 },
    { label: 'D-206 shipped, 45 trials', fit: { readout: 0.2, targeting: 0.2 }, length: 45 },
    { label: 'D-206 shipped, 60 trials', fit: { readout: 0.2, targeting: 0.2 }, length: 60 },
    {
      label: 'D-206 shipped, 4-option truth (0.25) assumed 0.2',
      fit: { readout: 0.2, targeting: 0.2 },
      length: 30,
      responderGuessing: 0.25,
    },
    {
      label: 'D-206 shipped, 6-option truth (0.167) assumed 0.2',
      fit: { readout: 0.2, targeting: 0.2 },
      length: 30,
      responderGuessing: 1 / 6,
    },
    {
      label: 'DIAGNOSTIC frozen target, c = 0',
      fit: { readout: 0, targeting: 0 },
      length: 30,
      targeting: 'frozen',
    },
    {
      label: 'DIAGNOSTIC frozen target, c = 0.2',
      fit: { readout: 0.2, targeting: 0.2 },
      length: 30,
      targeting: 'frozen',
    },
  ];

  const pools: { label: string; items: BankItem[] }[] = [
    { label: 'ideal 0.5-point grid (no bank)', items: gridPool(0.5, 12) },
    ...bankRefs.map((ref) => {
      const bank = loadBank(ref);
      return { label: bank.label, items: bank.items };
    }),
  ];

  for (const pool of pools) {
    console.log(`\n### ${pool.label}\n`);
    console.log(
      '| arm | null λ̄ | ±MC SE | false `above` | r | mean SE | atten. slope | indet (SD 0.15) | + bar | indet (SD 0.03) |',
    );
    console.log('| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |');
    for (const arm of arms) {
      const responder = { slope: SLOPE, guessing: arm.responderGuessing ?? truth };
      const targeting = arm.targeting ?? 'level';
      const nullCohort = runCohort(
        cohortOptionsFor(settings, pool.items, {
          lambdaMean: 0,
          lambdaSd: 0,
          length: arm.length,
          responder,
          fit: arm.fit,
          targeting,
        }),
      );
      const recoveryCohort = runCohort(
        cohortOptionsFor(settings, pool.items, {
          length: arm.length,
          responder,
          fit: arm.fit,
          targeting,
          barFloor: Math.max(0, mean(nullCohort.fitLambda)),
        }),
      );
      const row = recoveryRow(recoveryCohort);
      console.log(
        `| ${arm.label} | ${f(mean(nullCohort.fitLambda), 4)} | ${f(seOfMean(nullCohort.fitLambda), 4)} | ` +
          `${f(100 * nullCohort.aboveRate, 1)}% | ` +
          `${f(row.r)} | ${f(row.meanSe)} | ${f(row.attenuationSlope)} | ` +
          `${f(100 * recoveryCohort.indeterminateRate, 1)}% | ` +
          `${f(100 * recoveryCohort.barIndeterminateRate, 1)}% | ` +
          `${f(100 * recoveryCohort.narrowIndeterminateRate, 1)}% |`,
      );
    }
  }

  console.log(
    `\nWhat ships is \`DEFAULT_GUESSING = ${DEFAULT_GUESSING}\` (D-200) plus level targeting (D-206), which is the\n` +
      '"D-206 shipped" row. The two are independent corrections to the same artifact and the table is\n' +
      'the 2 × 2: neither alone reaches the frozen-target row, and the frozen row is the open-loop\n' +
      'bound rather than a target anyone chose. Read the `r` column beside the null column — a remedy\n' +
      'that zeroes the null by making the estimator insensitive shows up there and nowhere else.',
  );
}

function printNoiseSweep(settings: Settings): void {
  console.log('\n## Sensitivity of the 30-trial cell to the unrecorded handover-noise SD\n');
  const pool = gridPool(0.5, 12);
  console.log('| handover noise SD | r | mean SE | atten. ratio | atten. slope |');
  console.log('| --- | --- | --- | --- | --- |');
  for (const standingNoise of [0, 0.5, 1, 1.5, 2, 3]) {
    const row = recoveryRow(
      runCohort(cohortOptionsFor(settings, pool, { standingNoise, length: 30 })),
    );
    console.log(
      `| ${standingNoise.toFixed(1)} | ${f(row.r)} | ${f(row.meanSe)} | ` +
        `${f(row.attenuationRatio)} | ${f(row.attenuationSlope)} |`,
    );
  }
  console.log(
    `\nE-095 at 30 trials: r ${E095[30].r}, mean SE ${E095[30].meanSe}, attenuation ${E095[30].attenuation}.`,
  );
}

function printGateA(report: GateAReport): boolean {
  console.log(
    `\n## Gate A — ${report.bank} (mode ${report.mode}, guessing floor ${report.guessing})\n`,
  );
  console.log(
    `  ${report.items} items, difficulty ${f(report.difficultySpan[0], 2)}..${f(report.difficultySpan[1], 2)}, ` +
      `${report.distinctRungs} distinct 0.5-point rungs\n  ${report.path}\n`,
  );
  console.log('| check | verdict | observed |');
  console.log('| --- | --- | --- |');
  for (const check of report.checks) {
    console.log(
      `| **${check.id}** ${check.name} | ${check.pass ? 'PASS' : 'FAIL'} | ${check.observed} |`,
    );
  }
  const failures = report.checks.filter((c) => !c.pass);
  console.log('');
  for (const check of failures) {
    console.log(`  ${check.id} FAILED. Condition: ${check.condition}`);
    console.log(`    A failure means: ${check.meaningOfFailure}`);
  }
  console.log(
    `  Fitted-λ SD on this bank: ${f(report.fitLambdaSd, 4)}. This is the figure U1's power script\n` +
      "    must use in place of the design document's 0.06 estimate (§4.1.3).",
  );
  console.log(
    `  Headroom boundary: §1.1(c) asks for ≥6 scale points above \`standing + 1\`. On a bounded\n` +
      `    [${SCALE_MIN}, ${SCALE_MAX}] scale that is only geometrically available for standing ≤ ` +
      `${SCALE_MAX - 1 - 6}, so it cannot\n` +
      `    be met for every standing a real child can arrive with, whatever the bank contains. This\n` +
      `    bank tops out at ${f(report.difficultySpan[1], 2)}; the residue is a scale limit, reported by A3 and not\n` +
      `    charged to the bank.`,
  );
  if (failures.some((c) => c.id === 'A1')) {
    console.log(
      '\n  A1 FAILED. Under §9.4 as superseded by D-207 this stops the type\u2019s track ONLY if the\n' +
        '  failure is worse than the bank-free bound. Run `--gate-a --bank grid` at the same settings\n' +
        '  and compare: a bank whose A1 sits at the grid\u2019s own value has not manufactured anything\n' +
        '  a different bank could remove, and stopping its track would not address the cause.',
    );
  }
  return failures.length === 0;
}

/**
 * Gate A's two quantitative checks, replicated across seeds.
 *
 * A1's condition is `|λ̄| ≤ 2 × Monte-Carlo SE`, and at one seed that SE is the spread WITHIN a
 * 400-child cell. It says nothing about whether the next seed would return the same λ̄, and the
 * seed-to-seed spread is the larger of the two (§9). This block is the honest version of the
 * check: the per-seed means, and the SE of their mean.
 */
function printSeedReplication(reports: readonly GateAReport[], seeds: readonly number[]): void {
  const nulls = reports.map((r) => r.nullMean);
  const rs = reports.map((r) => r.recovery.r);
  const ses = reports.map((r) => r.recovery.meanSe);
  const sds = reports.map((r) => r.fitLambdaSd);

  const nullMean = mean(nulls);
  const nullSe = seOfMean(nulls);
  const first = reports[0];
  console.log(`\n### Replication across ${seeds.length} seeds — ${first?.bank ?? '?'}\n`);
  console.log('| quantity | mean of seeds | ± SE of that mean | [min, max] |');
  console.log('| --- | --- | --- | --- |');
  const row = (label: string, xs: readonly number[], places = 4) =>
    console.log(
      `| ${label} | ${f(mean(xs), places)} | ${f(seOfMean(xs), places)} | ` +
        `[${f(Math.min(...xs), places)}, ${f(Math.max(...xs), places)}] |`,
    );
  row('A1 null-cohort λ̄', nulls);
  row('A4 recovery r', rs, 3);
  row('A4 mean posterior SE', ses, 3);
  row('fitted-λ SD', sds);

  const passCount = (id: GateACheck['id']) =>
    reports.filter((r) => r.checks.find((c) => c.id === id)?.pass).length;
  console.log(
    `\n  **SEs from zero: ${f(Math.abs(nullMean) / nullSe, 1)}** ` +
      `(λ̄ = ${f(nullMean)} ± ${f(nullSe)}). Seeds: ${seeds.join(', ')}.\n` +
      `  Per-seed verdicts: A1 passes at ${passCount('A1')}/${reports.length} seeds, ` +
      `A2 at ${passCount('A2')}/${reports.length}, A3 at ${passCount('A3')}/${reports.length}, ` +
      `A4 at ${passCount('A4')}/${reports.length}.`,
  );
}

function main(): void {
  const settings = parseArgs(process.argv.slice(2));
  const explicit =
    settings.gateA || settings.noiseSweep || settings.guessingProbe || settings.fixProbe;
  const runCalibration = settings.calibrate || !explicit;
  const output: Record<string, unknown> = {};

  console.log('# Learning-block measurement harness (U0)\n');
  console.log(
    'Born-synthetic. Every bank below carries `validated: false`; nothing here is evidence about a\n' +
      'real child, and clearing Gate A is not clearing the gate (STAGE2_QUESTION_DESIGN §4.1.2).',
  );

  if (runCalibration) output['calibration'] = printCalibration(settings);
  if (settings.noiseSweep) printNoiseSweep(settings);
  if (settings.guessingProbe) {
    printGuessingProbe(settings, settings.bank === null ? [REFERENCE_BANK] : [settings.bank]);
  }
  if (settings.fixProbe) {
    printFixProbe(settings, settings.bank === null ? [REFERENCE_BANK] : [settings.bank]);
  }

  let allPass = true;
  if (settings.gateA || (settings.bank !== null && !settings.guessingProbe && !settings.fixProbe)) {
    const ref = settings.bank ?? REFERENCE_BANK;
    const modes: Persistence[] =
      settings.bank === null ? [settings.mode] : ['consistent', 'perTrial'];
    const reports: GateAReport[] = [];
    const seen = new Set<string>();
    for (const mode of modes) {
      const resolved = bankRefForMode(ref, mode);
      if (seen.has(resolved)) continue;
      seen.add(resolved);
      const bank = loadBank(resolved);
      const perSeed = settings.seeds.map((seed) => gateA({ ...settings, seed }, bank, mode));
      reports.push(...perSeed);
      // The full report is per-seed detail; at more than one seed it buries the replication that
      // is the point of asking for several, so only the first is printed in full.
      const [head, ...rest] = perSeed;
      if (head) allPass = printGateA(head) && allPass;
      for (const report of rest) allPass = report.checks.every((c) => c.pass) && allPass;
      if (settings.seeds.length > 1) printSeedReplication(perSeed, settings.seeds);
    }
    output['gateA'] = reports;
  }

  if (settings.json) console.log(`\n${JSON.stringify(output, null, 2)}`);
  if (!allPass) process.exitCode = 1;
}

main();
