/**
 * `persona-sim` — the born-synthetic persona simulator
 * (`PERSONA_SIM_AND_VALIDATION_DESIGN.md` §1).
 *
 * Three layers, all pure and seeded:
 *   `latent.ts`      correlated latent traits (the ground truth)
 *   `measurement.ts` latent -> one trial's observables (accuracy / RT / gate)
 *   `sampler.ts`     a persona as the session shell's `respond` callback
 *
 * CLAIM BOUNDARY: personas are synthetic by construction (`syntheticOnly: true`,
 * `validated: false`; D-006, R9). Recovering an injected latent from responses
 * generated by this same model is CIRCULAR: it demonstrates that the scoring path
 * is correct and quantifies estimator bias, precision, and how many items a target
 * SE needs. It is not evidence that any metric measures real ability, and it is
 * not evidence of program impact (R10).
 */

export * from './latent';
export * from './measurement';
export * from './sampler';
