import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import process from 'node:process';

import { hashSeed, mulberry32 } from '../../packages/cat-engine/src/rng';
import type { Persona } from '../../packages/cat-engine/src/persona-sim/index';
import type { IrtParameters, ScoredDomain } from '../../packages/cat-engine/src/types';
import type { SimBankItem, SimServedItem } from '../../packages/cat-engine/src/persona-sim/sampler';

/**
 * Shared plumbing for the psychometric sweep scripts
 * (`docs/PSYCHOMETRIC_SWEEP_2026-07-28.md`).
 *
 * WHY THIS EXISTS: the three sweeps administer items the production bank does not
 * contain (blocks of arbitrary length, difficulty targeted continuously at a
 * running estimate, item pools at other guessing floors), so they cannot reuse
 * `scripts/persona-sim/bank.ts`. They still drive the SAME persona generator, so
 * the responses are produced by the same measurement models the recorded baseline
 * used — only the administration schedule differs.
 *
 * The recorded baseline in `docs/PERSONA_SIM_RESULTS.md` must keep reproducing, so
 * nothing here is imported by `scripts/persona-sim/*` and nothing here perturbs a
 * persona's RNG substream: a persona's draws are keyed by
 * `(seed, personaId, order, itemId)`, so a sweep that uses its own seed suffix and
 * its own item ids is independent of the baseline stream by construction.
 *
 * Born-synthetic only: no network, no database, no real data (D-006, R9).
 */

export const CLAIM_HEADER = [
  '> **CLAIM BOUNDARY — READ BEFORE ANY NUMBER BELOW.** Born-synthetic',
  '> (`synthetic_only: true`, `validated: false`; D-006, R9). Personas are generated by the',
  '> 3PL in `packages/cat-engine/src/irt.ts` and then scored by estimators that invert that',
  '> same 3PL, so every recovery number here is **CIRCULAR**. This sweep establishes method,',
  '> code correctness, and STATISTICAL POWER under known truth — what a design could detect',
  "> if the simulator's assumptions held. It is **not** evidence that any metric measures",
  '> real ability, **not** convergent or predictive validity, and **not** program impact.',
  '> Access, reliability, outcome change, and causal impact are separate milestones (R10).',
  "> Tuning anything on these numbers tunes to the simulator's assumptions, not to children.",
].join('\n');

/** Minimal flag parser: `--flag value` and bare `--flag` booleans. */
export function flagValue(argv: readonly string[], flag: string): string | undefined {
  const i = argv.indexOf(flag);
  return i >= 0 ? argv[i + 1] : undefined;
}

export function numberFlag(argv: readonly string[], flag: string, fallback: number): number {
  const raw = flagValue(argv, flag);
  return raw == null ? fallback : Number(raw);
}

export function mdTable(headers: readonly string[], rows: readonly (readonly string[])[]): string {
  return [
    `| ${headers.join(' | ')} |`,
    `|${headers.map(() => '---').join('|')}|`,
    ...rows.map((r) => `| ${r.join(' | ')} |`),
  ].join('\n');
}

export interface ArtifactOptions {
  outDir: string;
  name: string;
  lines: readonly string[];
  json: Record<string, unknown>;
  seed: string;
}

/** Write the paired markdown + JSON artifact, both stamped born-synthetic. */
export function writeArtifact(options: ArtifactOptions): { mdPath: string; jsonPath: string } {
  mkdirSync(options.outDir, { recursive: true });
  const mdPath = path.join(options.outDir, `${options.name}.md`);
  const jsonPath = path.join(options.outDir, `${options.name}.json`);
  writeFileSync(mdPath, `${options.lines.join('\n')}\n`);
  writeFileSync(
    jsonPath,
    `${JSON.stringify(
      {
        claimBoundary:
          'Born-synthetic power study. Personas are generated by the same 3PL that scores them, ' +
          'so recovery is circular: it establishes method, correctness, and statistical power ' +
          'only. Not real validity; not program impact (R10).',
        syntheticOnly: true,
        validated: false,
        seed: options.seed,
        ...options.json,
      },
      null,
      2,
    )}\n`,
  );
  return { mdPath, jsonPath };
}

export function defaultOutDir(): string {
  return path.join(process.cwd(), 'scripts/psychometric-sweep/out');
}

/**
 * Scale a cohort's injected lambda by a constant factor.
 *
 * Multiplicative rather than additive: the correlation an estimator can achieve
 * depends on the SPREAD of lambda across personas relative to estimator noise, so
 * "2x effect size" has to mean twice the between-persona SD, not a shifted mean.
 * Scaling the whole draw keeps every persona's rank, which makes Spearman
 * comparable across scales.
 */
export function scaleCohortLambda(cohort: readonly Persona[], scale: number): Persona[] {
  if (scale === 1) return [...cohort];
  return cohort.map((persona) => ({ ...persona, learningRate: persona.learningRate * scale }));
}

/**
 * A synthetic administration slot. The sweep builds these directly instead of
 * going through `apps/web`'s bank + sequencer because the schedules under test do
 * not exist as a bank: they place difficulty continuously, per trial, per persona.
 */
export interface SweepItem {
  served: SimServedItem;
  bankItem: SimBankItem;
  irt: IrtParameters;
}

/** Deterministic discrimination for a sweep slot; constant across cells. */
export function sweepDiscrimination(key: string, min = 0.9, max = 1.6): number {
  return min + (max - min) * mulberry32(hashSeed(`sweep-a|${key}`))();
}

/**
 * Build one administration slot. `stage` matters: the persona sampler treats
 * `effort` items as the novel block where ability climbs by lambda per trial, and
 * `standing` items as climb-free.
 */
export function sweepItem(
  itemId: string,
  domain: ScoredDomain,
  stage: 'standing' | 'effort',
  irt: IrtParameters,
  difficultyLevel: number,
): SweepItem {
  const shape = {
    itemId,
    typeCode: `SWEEP-${stage.toUpperCase()}`,
    domain,
    difficultyLevel,
    renderKind: 'single-select',
    stage,
  } as const;
  return { served: shape, bankItem: shape, irt };
}
