/**
 * gen-type-registry.ts
 *
 * Derives the canonical list of question-type codes and their item-model
 * metadata from the AUTHORITATIVE source of truth
 * (research/exam-question-types/catalog/master_types.jsonl) and emits a
 * committed, typed TypeScript module the item-bank schema imports.
 *
 * Regenerate with: pnpm --filter @gt-selection/item-bank gen:registry
 *
 * This copies only structural metadata (code, domain, age bands, difficulty
 * levers, provenance). It invents no items and no answer keys. All emitted
 * content is born-synthetic research metadata (RES-013).
 */
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(HERE, '../../..');
const MASTER = resolve(REPO_ROOT, 'research/exam-question-types/catalog/master_types.jsonl');
const OUT = resolve(HERE, '../src/generated/type-registry.generated.ts');

const VALID_DOMAINS = ['fluid_reasoning', 'verbal', 'quantitative', 'spatial'] as const;
type Domain = (typeof VALID_DOMAINS)[number];

interface RawMaster {
  type_id: string;
  name: string;
  areas: string[];
  topics_techniques_covered?: string[];
  measurements?: string[];
  age_bands?: string[];
  demo_path?: string;
  adaptive?: {
    works_well?: string;
    difficulty_levers?: string | string[];
    aig_cloneable?: string;
  };
}

interface TypeModel {
  typeCode: string;
  domain: Domain;
  name: string;
  ageBands: string[];
  subconstructs: string[];
  measurements: string[];
  difficultyLevers: string;
  aigCloneable: string;
  adaptiveWorksWell: string;
  demoPath: string;
}

function main(): void {
  const raw = readFileSync(MASTER, 'utf-8');
  const sha = createHash('sha256').update(raw).digest('hex');
  const rows: RawMaster[] = raw
    .split('\n')
    .filter((l) => l.trim().length > 0)
    .map((l) => JSON.parse(l) as RawMaster);

  const models: TypeModel[] = rows.map((r) => {
    const areas = r.areas ?? [];
    const domain = areas[0];
    if (areas.length !== 1 || !VALID_DOMAINS.includes(domain as Domain)) {
      throw new Error(
        `Type ${r.type_id} has non-single or invalid domain: ${JSON.stringify(areas)}`,
      );
    }
    return {
      typeCode: r.type_id,
      domain: domain as Domain,
      name: r.name,
      ageBands: r.age_bands ?? [],
      subconstructs: r.topics_techniques_covered ?? [],
      measurements: r.measurements ?? [],
      difficultyLevers: Array.isArray(r.adaptive?.difficulty_levers)
        ? r.adaptive.difficulty_levers.join('; ')
        : (r.adaptive?.difficulty_levers ?? ''),
      aigCloneable: r.adaptive?.aig_cloneable ?? 'med',
      adaptiveWorksWell: r.adaptive?.works_well ?? 'med',
      demoPath: r.demo_path ?? `demos/${r.type_id}.html`,
    };
  });

  models.sort((a, b) =>
    a.domain === b.domain ? a.typeCode.localeCompare(b.typeCode) : a.domain.localeCompare(b.domain),
  );

  const codes = models.map((m) => m.typeCode);
  const dupes = codes.filter((c, i) => codes.indexOf(c) !== i);
  if (dupes.length > 0) throw new Error(`Duplicate type codes: ${dupes.join(', ')}`);

  const modelsObj: Record<string, TypeModel> = {};
  for (const m of models) modelsObj[m.typeCode] = m;

  const domainByType: Record<string, Domain> = {};
  for (const m of models) domainByType[m.typeCode] = m.domain;

  const banner =
    '// AUTO-GENERATED by scripts/gen-type-registry.ts — DO NOT EDIT BY HAND.\n' +
    '// Source of truth: research/exam-question-types/catalog/master_types.jsonl\n' +
    '// Regenerate: pnpm --filter @gt-selection/item-bank gen:registry\n' +
    '// Born-synthetic research metadata only (RES-013).\n';

  const body = [
    banner,
    `export const MASTER_TYPES_SHA256 = ${JSON.stringify(sha)};`,
    '',
    `export const TYPE_CODES = ${JSON.stringify(codes, null, 2)} as const;`,
    '',
    'export type QuestionTypeCode = (typeof TYPE_CODES)[number];',
    '',
    `export const VALID_DOMAINS = ${JSON.stringify([...VALID_DOMAINS])} as const;`,
    'export type Domain = (typeof VALID_DOMAINS)[number];',
    '',
    'export interface RawTypeModel {',
    '  typeCode: QuestionTypeCode;',
    '  domain: Domain;',
    '  name: string;',
    '  ageBands: string[];',
    '  subconstructs: string[];',
    '  measurements: string[];',
    '  difficultyLevers: string;',
    '  aigCloneable: string;',
    '  adaptiveWorksWell: string;',
    '  demoPath: string;',
    '}',
    '',
    `export const DOMAIN_BY_TYPE: Record<QuestionTypeCode, Domain> = ${JSON.stringify(
      domainByType,
      null,
      2,
    )};`,
    '',
    `export const RAW_TYPE_MODELS: Record<QuestionTypeCode, RawTypeModel> = ${JSON.stringify(
      modelsObj,
      null,
      2,
    )};`,
    '',
  ].join('\n');

  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, body, 'utf-8');
  console.log(
    `Wrote ${OUT}\n  ${codes.length} type codes, sha256=${sha.slice(0, 12)}…\n  domains: ${VALID_DOMAINS.map(
      (d) => `${d}=${models.filter((m) => m.domain === d).length}`,
    ).join(', ')}`,
  );
}

main();
