#!/usr/bin/env bash
#
# Every command behind docs/product/STAGE2_BANK_RECOVERY_MEASUREMENT.md, in order.
#
# This script ADDS NOTHING to the harness. It is a record of invocations, written so that the
# findings document's tables can be regenerated by one command instead of reassembled from a
# transcript. `scripts/exam-learning-block-harness.ts`, the estimator, the readout, the banks and
# the generator are untouched by this work — the question was whether a bank purpose-built for the
# 30-trial learning-rate measurement recovers it, and tuning any of those would have answered a
# different question.
#
# Two conventions hold across every run and they are what make the pools comparable:
#
#   * `--guessing 0.2` is the SIMULATED CHILD's floor — a real five-option item. FLU-OPCHAIN-01 is
#     234/234 five-option, so 0.2 is exact for it. FLU-MATRIX-01 is mixed (63 four-option,
#     27 five-option, 30 six-option), so 0.2 is an approximation there; PR #22 used the same 0.2 and
#     matching it is the point. `--fix-probe` defaults its own responder to 0.2, which is why the
#     fix-probe runs below do not pass the flag.
#   * everything else is left at the harness default, including `--seed 20260730` and 400 children
#     per cell, so the ideal-grid rows are identical across runs and can be diffed as a check that
#     nothing but the pool changed.
#
# Usage:  bash scripts/stage2-bank-recovery-runs.sh [output-dir]
# Runtime: ~4 minutes.
set -euo pipefail

OUT="${1:-/tmp/stage2-bank-recovery}"
mkdir -p "$OUT"
cd "$(dirname "$0")/.."

run() {
  local name="$1"
  shift
  echo "--> $name: pnpm exam:block-harness -- $*"
  pnpm exam:block-harness -- "$@" >"$OUT/$name.txt" 2>&1 || true
}

# --- 1. Baseline. Reproduce PR #22 before measuring anything new with the same instrument. -------
run fixprobe-matrix --fix-probe --bank FLU-MATRIX-01

# --- 2. The question. Null contamination, recovery, and both indeterminate rates on the ---------
#        purpose-built bank, at PR #22's arms and settings. `+ bar` is the SD-0.15 reference with
#        this arm's own measured floor declared, which is what D-200 makes required.
run fixprobe-opchain-consistent --fix-probe --bank FLU-OPCHAIN-01

# --- 3. The scrambled control (D-S2-3). Identical block, system re-drawn every trial. -----------
run fixprobe-opchain-pertrial --fix-probe --bank FLU-OPCHAIN-01.perTrial

# --- 4. The recovery ladder, comparable to PR #22's corrected E-095 table. ----------------------
#        `--calibrate` walks 8/15/30/45/60 on the ideal grid and FLU-MATRIX-01, which are its two
#        hard-wired pools. FLU-OPCHAIN-01 is not one of them, so its ladder comes from Gate A at
#        each length instead: `gateA`'s A4 cohort is built by the same `cohortOptionsFor` call at
#        the same seed, so the cells are matched rather than merely similar. A4 is also reported
#        as FAIL at every length except 30, because its pass condition is defined only against
#        E-095's 30-trial cell; read the observed figures, not the verdict, on those rows.
run calibrate-ladder-grid-matrix --calibrate --guessing 0.2
for len in 8 15 30 45 60; do
  run "ladder-opchain-$len" --gate-a --bank FLU-OPCHAIN-01 --guessing 0.2 --length "$len"
  run "ladder-matrix-$len" --gate-a --bank FLU-MATRIX-01 --guessing 0.2 --length "$len"
done

# --- 5. Headroom (§1.1(c)). ---------------------------------------------------------------------
#        Gate A's A3 already separates the two causes of a child pinning at the top of the pool —
#        the bank stopping short of what the targeting rule asked for, which is the §1.1(c) defect,
#        versus `nextTargetTheta` clamping to the 20-point scale, which no bank can fix. Sweeping
#        standing with the population spread collapsed (`--theta0-sd 0 --standing-noise 0`) turns
#        that pair of counts into the standing at which truncation begins.
for standing in 6 8 10 11 12 13 14 15 16 17; do
  run "headroom-opchain-standing-$standing" \
    --gate-a --bank FLU-OPCHAIN-01 --guessing 0.2 \
    --theta0-mean "$standing" --theta0-sd 0 --standing-noise 0
  run "headroom-matrix-standing-$standing" \
    --gate-a --bank FLU-MATRIX-01 --guessing 0.2 \
    --theta0-mean "$standing" --theta0-sd 0 --standing-noise 0
done

# --- 6. Sensitivity to the one E-095 parameter nobody wrote down. -------------------------------
#        `--noise-sweep` is hard-wired to the ideal grid, so the bank arm of the same sweep is
#        Gate A at each handover-noise SD.
run noise-sweep-grid --noise-sweep --guessing 0.2
for noise in 0 0.5 1 1.5 2 3; do
  run "noise-opchain-$noise" --gate-a --bank FLU-OPCHAIN-01 --guessing 0.2 --standing-noise "$noise"
done

# --- 7. What the UNCORRECTED estimator does on the purpose-built bank. --------------------------
#        Context for §2 of the findings: the bank is not what the correction was for, and this is
#        the row that shows it was already near the ideal grid before PR #22 touched anything.
run guessing-probe-opchain --guessing-probe --bank FLU-OPCHAIN-01

# --- 8. Is any between-pool difference bigger than Monte-Carlo noise? ---------------------------
#        Everything above is one cohort at one seed, and the between-pool gaps at 30 trials are
#        small enough that this has to be asked before any of them is reported as a difference.
#        It is also the check that catches the harness's own default seed being unrepresentative,
#        which it is: 20260730 returns the lowest 30-trial recovery and the highest 15-trial
#        recovery of the eight seeds below. Seven more seeds, everything else held, so every
#        headline cell is a mean over eight cohorts with a measured spread instead of one draw.
#
#        `--calibrate` supplies the ideal grid and FLU-MATRIX-01 across the whole ladder in one
#        run, plus the grid's own λ_true = 0 cohort at 30 trials on its unbiasedness line. Gate A
#        supplies FLU-OPCHAIN-01 (both arms) and FLU-MATRIX-01's null cohort at each length.
#        Every pool is built by the same `cohortOptionsFor` call at the same seed, so the seeds
#        are paired across pools and the differences can be read as paired.
for seed in 20260730 11 22 33 44 55 66 77; do
  run "seed-grid-matrix-$seed" --calibrate --guessing 0.2 --seed "$seed"
  for len in 8 15 30 45 60; do
    run "seed-opchain-$len-$seed" \
      --gate-a --bank FLU-OPCHAIN-01 --guessing 0.2 --seed "$seed" --length "$len"
    run "seed-matrix-$len-$seed" \
      --gate-a --bank FLU-MATRIX-01 --guessing 0.2 --seed "$seed" --length "$len"
  done
done

# --- 9. Why the scrambled control returns an exactly zero contrast. -----------------------------
#        The one measurement here that is not a harness invocation. It replays the same
#        administration path on both banks under identical responses and compares the served
#        difficulties, which is what turns "the arms came out identical" from an observation into
#        an explanation with a bound on it.
echo "--> arm-equivalence: pnpm exam:arm-equivalence"
pnpm exam:arm-equivalence >"$OUT/arm-equivalence.txt" 2>&1 || true

echo
echo "Raw output in $OUT"
