#!/usr/bin/env bash
#
# Every harness invocation behind docs/product/STAGE2_FLU_OPCHAIN_DENSITY_GATE_A.md, in order.
#
# This script ADDS NOTHING to the harness, the estimator or the readout. It is a record of
# invocations, so the findings document's tables can be regenerated by one command instead of
# reassembled from a transcript. The question it answers is narrow: does FLU-OPCHAIN-01 at TWELVE
# items per 0.5-point rung sit on the bank-free recovery bound at 30, 45 and 60 trials, where the
# SIX-per-rung version measurably did not?
#
# Three conventions hold across every run and they are what make the comparison a comparison.
#
#   * `--guessing 0.2` is the SIMULATED CHILD's floor. This bank is 468/468 five-option, so 0.2 is
#     exact for it. The estimator is left at the shipped DEFAULT_GUESSING = 0.2 in both roles,
#     because that is the configuration a real administration would run.
#   * EIGHT SEEDS everywhere it matters. STAGE2_BANK_RECOVERY_MEASUREMENT.md §9 found the harness's
#     default seed unrepresentative in both directions, with single-seed cells carrying roughly ±0.04
#     of noise on `r` — larger than the differences this work is measuring.
#   * The BEFORE bank is the 6/rung bank as it stands on `origin/dev`, read from a path rather than
#     regenerated, so the two sides of the before/after differ in the artifact and in nothing else.
#     Every pool at a given seed is built by the same `cohortOptionsFor` call, so the seeds are
#     PAIRED across pools and the differences can be read as paired.
#
# Usage:  bash research/exam-question-types/gate-a/opchain-density-runs.sh [output-dir]
# Runtime: ~3 minutes.
set -euo pipefail

OUT="${1:-/tmp/opchain-density}"
BEFORE_DIR="${BEFORE_DIR:-/tmp/opchain-before}"
mkdir -p "$OUT"
cd "$(dirname "$0")/../../.."

SEEDS=(20260730 11 22 33 44 55 66 77)
LENGTHS=(30 45 60)

# The 6/rung bank this work replaces. Extracted from git rather than regenerated, because
# regenerating it would need the old generator and the point is to compare shipped artifacts.
if [ ! -f "$BEFORE_DIR/FLU-OPCHAIN-01.dev.jsonl" ]; then
  mkdir -p "$BEFORE_DIR"
  git show origin/dev:research/exam-question-types/banks/FLU-OPCHAIN-01.jsonl \
    >"$BEFORE_DIR/FLU-OPCHAIN-01.dev.jsonl"
  git show origin/dev:research/exam-question-types/control-banks/FLU-OPCHAIN-01.perTrial.jsonl \
    >"$BEFORE_DIR/FLU-OPCHAIN-01.perTrial.dev.jsonl"
fi

run() {
  local name="$1"
  shift
  echo "--> $name"
  pnpm exam:block-harness -- "$@" --json >"$OUT/$name.json" 2>"$OUT/$name.err" || true
}

# --- 1. The bank-free bound, and FLU-MATRIX-01, across the whole ladder in one run per seed. -----
#        `--calibrate` walks 8/15/30/45/60 on the ideal 0.5-point grid — which carries TWELVE items
#        per rung, and is therefore exactly the density this work adopts — and on FLU-MATRIX-01.
for seed in "${SEEDS[@]}"; do
  run "grid-$seed" --calibrate --guessing 0.2 --seed "$seed"
done

# --- 2. Gate A on both arms of BOTH banks, at each block length. ---------------------------------
#        A bare type code makes the harness run `consistent` and `perTrial` in one invocation. A4 is
#        reported FAIL at every length except 30 because its pass condition is defined only against
#        E-095's 30-trial cell; read the observed figures, not the verdict, on the 45 and 60 rows.
for seed in "${SEEDS[@]}"; do
  for len in "${LENGTHS[@]}"; do
    run "after-$len-$seed" --gate-a --bank FLU-OPCHAIN-01 --guessing 0.2 --seed "$seed" --length "$len"
    run "before-$len-$seed" --gate-a --bank "$BEFORE_DIR/FLU-OPCHAIN-01.dev.jsonl" \
      --guessing 0.2 --seed "$seed" --length "$len"
  done
done

# --- 3. The 0.25-floor cell, for comparability with the sibling types' published A1 figures. -----
#        Those were measured on four-option banks, where 0.25 is exact and the contamination floor
#        reads ~0.017. It is NOT the right floor for this bank; it is here so the cells line up.
for seed in "${SEEDS[@]}"; do
  run "after-30-g25-$seed" --gate-a --bank FLU-OPCHAIN-01 --guessing 0.25 --seed "$seed" --length 30
  run "grid-g25-$seed" --calibrate --guessing 0.25 --seed "$seed"
done

# --- 4. The zero-floor cell, which is where A1 passes. -------------------------------------------
#        E-200 localised the A1 defect to the estimator's guessing-floor handling. At a floorless
#        responder the same estimator on the same bank returns ~0 and recovery exceeds the published
#        figure. A floorless responder is a claim that a child who knows nothing scores zero on a
#        five-option item, which is false, so this is diagnostic and not a configuration to ship.
for seed in "${SEEDS[@]}"; do
  run "after-30-g0-$seed" --gate-a --bank FLU-OPCHAIN-01 --guessing 0 --seed "$seed" --length 30
done

# --- 5. Headroom (A3), with the population spread collapsed so `standing` is the swept value. ----
for standing in 6 8 10 11 12 13 14 15 16 17; do
  run "headroom-after-$standing" --gate-a --bank FLU-OPCHAIN-01 --guessing 0.2 \
    --theta0-mean "$standing" --theta0-sd 0 --standing-noise 0
  run "headroom-before-$standing" --gate-a --bank "$BEFORE_DIR/FLU-OPCHAIN-01.dev.jsonl" \
    --guessing 0.2 --theta0-mean "$standing" --theta0-sd 0 --standing-noise 0
done

echo
echo "Raw output in $OUT — now run:"
echo "  node research/exam-question-types/gate-a/opchain-density-report.mjs $OUT"
