/**
 * Within-block learning rate, fitted as the slope of a climbing ability.
 *
 * `deriveLearningRate` in `derived-metrics.ts` answers "did the ceiling move between the halves of
 * this trace". This module answers the harder question the novel block was designed around: if the
 * child's ability is climbing while they work, `theta(t) = theta0 + lambda * t`, what are `theta0`
 * and `lambda`? Inverting the same curve through the response model uses each item's difficulty
 * and the ORDER of the responses, which a half-contrast discards.
 *
 * The response model is the one-parameter logistic already used by `ability.ts`, so both fits
 * describe the child on the same [1, 20] difficulty scale and a `theta0` from here is comparable
 * to a `deriveAbilityEstimate` from there:
 *
 *     P(correct | difficulty b, trial t) = 1 / (1 + exp(-slope * (theta0 + lambda * t - b)))
 *
 * `lambda` is therefore in SCALE POINTS PER TRIAL: 0.1 means the difficulty the child has an even
 * chance on rises by one scale point every ten trials.
 *
 * WHY MAP AND NOT A LEAST-SQUARES SLOPE: an OLS slope over 0/1 scores ignores difficulty, ignores
 * that a Bernoulli outcome's variance depends on its mean, and on a block whose difficulty is
 * being re-targeted upward it reads a FLAT score series as no learning when in fact the child is
 * holding accuracy against rising difficulty — exactly backwards. The prior is load-bearing rather
 * than cosmetic: on a short block the unpenalized likelihood is frequently monotone in `lambda`
 * and the maximum-likelihood estimate runs to the boundary.
 *
 * THE FIT AND THE DESIGN ARE SEPARATE, AND KEEPING THEM SEPARATE IS LOAD-BEARING.
 * `estimateLearningCurve` reads a finished block; `nextTargetTheta` decides what the next trial of a
 * live block should be. They used to be the same computation used twice, which meant the estimate of
 * `lambda` chose the evidence from which `lambda` would be estimated. D-206 opened that loop: the
 * targeting rule aims at {@link estimateBlockLevel}, a fit with no climb term at all, corrected by
 * recent OBSERVED accuracy rather than by any fitted quantity. See {@link nextTargetTheta} for what
 * the loop was doing, what opening it cost, and why the correction does not reinstate it.
 *
 * CLAIM BOUNDARY: this is an estimator, not a validated measure. `slope` and every item difficulty
 * are design assumptions on a born-synthetic bank (`syntheticOnly=true`, `validated=false`), and
 * recovering `lambda` from responses generated by this same curve would be circular — it shows the
 * estimator works under known truth, never that a within-session climb measures real learning,
 * learning potential, or program benefit. Callers must report through `learningRateReadout`, which
 * refuses to name a band when the posterior is too wide to support one. (D-030, E-095.)
 */
import { SCALE_MAX, SCALE_MIN } from './types';

/** One trial inside a novel block, indexed by its position in the block. */
export interface LearningTrial {
  /** Design-estimated difficulty of the item served, on the [1, 20] scale. */
  readonly difficulty: number;
  /** Observed score in [0, 1] (dichotomous 0/1 or polytomous partial credit). */
  readonly score: number;
  /** 0-based index inside the block; the climb is `theta0 + lambda * trialIndex`. */
  readonly trialIndex: number;
}

export interface LearningCurveOptions {
  /**
   * Logistic discrimination per scale point. Defaults to 1.0 to match
   * `DEFAULT_ABILITY_BRACKETING`, which is also the value the prior widths below were sized
   * against; at `slope: 1.0` one scale point is one logit, so a `priorLambdaSd` quoted in scale
   * points and one quoted in logits coincide. Change `slope` and those widths need rescaling by
   * `1 / slope` to keep meaning the same thing.
   */
  readonly slope?: number;
  readonly min?: number;
  readonly max?: number;
  /** Prior mean for the block's starting ability. Defaults to the scale midpoint. */
  readonly priorTheta0Mean?: number;
  /**
   * Prior SD for the starting ability, in scale points. Defaults to 6.0, the weak width
   * `DEFAULT_ABILITY_BRACKETING` uses. Pass the settled standing estimate as
   * `priorTheta0Mean` to anchor the block; leave this wide unless there is a real precision
   * figure to justify tightening it, because a tight `theta0` prior buys `lambda` apparent
   * precision it has not earned.
   */
  readonly priorTheta0Sd?: number;
  /** Prior mean for lambda. Defaults to 0 — a null climb is the honest prior. */
  readonly priorLambdaMean?: number;
  /**
   * Prior SD for lambda, in scale points per trial. Defaults to 0.15, several times wider than
   * the per-trial climb a synthetic sweep injected, so it regularizes a short block without
   * dictating the answer. A tighter prior would manufacture agreement with its own mean.
   */
  readonly priorLambdaSd?: number;
  /**
   * Lower asymptote (guessing floor). Defaults to {@link DEFAULT_GUESSING}.
   *
   * Pass the reciprocal of the option count when a block is administered from a bank whose items
   * are not the five-option format `DEFAULT_GUESSING` assumes. Passing 0 asserts that a child who
   * knows nothing scores nothing, which is true only for a constructed-response item; on multiple
   * choice it is the misspecification E-200 measures.
   */
  readonly guessing?: number;
  readonly maxIterations?: number;
  readonly tolerance?: number;
}

export interface LearningCurveEstimate {
  /** Posterior-mode starting ability, on the [1, 20] scale. */
  readonly theta0: number;
  /** Posterior-mode climb, in scale points per trial. */
  readonly lambda: number;
  /** Posterior SD of `theta0`, from the observed information at the mode. */
  readonly theta0Se: number;
  /**
   * Posterior SD of `lambda`. The figure that decides whether a rate may be reported at all:
   * a `lambda` whose SE is as wide as the spread being compared against carries no rank
   * information, however precise the point estimate looks.
   */
  readonly lambdaSe: number;
  readonly iterations: number;
  readonly converged: boolean;
}

/** Widest per-trial climb the fit will entertain, in scale points per trial. */
const LAMBDA_BOUND = 1;

/**
 * Lower asymptote the fit assumes by default: the chance floor of a five-option item.
 *
 * NOT a cosmetic default, and the reason it is a named constant rather than a literal. At 0 — which
 * is what this estimator shipped with — the fit has no way to explain a success on an item well
 * above the child's level except as ability, and inside an adaptive block that error compounds
 * rather than averaging out: the inflated fit raises the level, the targeting rule aims the next
 * item higher, and the fit then reads its own rising difficulty walk as a genuine climb. Measured
 * against a responder with a real five-option floor and no learning at all (λ_true = 0 for every
 * child, 400 children, idealised grid, 30 trials), the `guessing = 0` fit returns λ̄ = 0.0398 ±
 * 0.0043 and `learningRateReadout` calls 32.8% of those non-learners `above` average pace. At this
 * floor the same cohort returned λ̄ = 0.0011 ± 0.0033 and 5.3%. E-200 records the measurement.
 *
 * Those two figures were measured under the PROJECTING targeting rule D-206 replaced, so they date
 * the defect rather than describe the shipped pipeline; the floor is still load-bearing under the
 * level rule, and `learning-curve.test.ts` runs the 2 × 2 that shows each correction removes part
 * of the artifact and neither removes it alone.
 *
 * 0.2 rather than a per-item reciprocal because the fit takes one floor for the whole block, and a
 * block is administered from ONE type's pool — so the right floor is a property of the caller's
 * bank, not of this module. It is the DEFAULT and not an assertion: D-200 part 1 requires a caller
 * administering another format to pass the reciprocal of its own option count, and Phase 2 now
 * derives that per activity (`blockGuessingFloor` in `apps/web/src/lib/exam/phase2.ts`), because
 * the four wired Stage 2 banks are not all five-option — `VER-MORPHO-01` offers four. E-207
 * measures what leaving it at this default cost that one activity. A bank of MIXED option counts
 * is a further exposure that no single floor removes, and E-200 costs it.
 *
 * The standing fit in `ability.ts` has no such parameter and is therefore still a plain 1PL, so a
 * `theta0` from this fit and a `deriveAbilityEstimate` no longer make identical response-model
 * assumptions. That comparability was the stated reason the floor was 0, and giving it up is a
 * deliberate trade recorded in D-200: a `theta0` that is comparable to the standing estimate but
 * manufactures a learning rate is worse than one that is not.
 */
export const DEFAULT_GUESSING = 0.2;

function clamp(value: number, lo: number, hi: number): number {
  return Math.min(hi, Math.max(lo, value));
}

function isFiniteNumber(v: unknown): v is number {
  return typeof v === 'number' && Number.isFinite(v);
}

/**
 * Joint MAP estimate of `(theta0, lambda)` by Fisher scoring under a normal prior on both.
 *
 * Fisher scoring rather than a grid search because the profile likelihood over a short block is
 * flat, so a grid coarse enough to be cheap would quantize `lambda` at the scale of the very
 * effect being measured. Iteration count and tolerance are fixed rather than adaptive so a stored
 * trace re-scores bit-for-bit.
 */
export function estimateLearningCurve(
  trials: readonly LearningTrial[],
  options: LearningCurveOptions = {},
): LearningCurveEstimate {
  const {
    slope = 1.0,
    min = SCALE_MIN,
    max = SCALE_MAX,
    priorTheta0Mean = (min + max) / 2,
    priorTheta0Sd = 6.0,
    priorLambdaMean = 0,
    priorLambdaSd = 0.15,
    guessing = DEFAULT_GUESSING,
    maxIterations = 60,
    tolerance = 1e-7,
  } = options;

  const theta0Precision = priorTheta0Sd > 0 ? 1 / (priorTheta0Sd * priorTheta0Sd) : 0;
  const lambdaPrecision = priorLambdaSd > 0 ? 1 / (priorLambdaSd * priorLambdaSd) : 0;
  const c = clamp(guessing, 0, 0.99);

  let theta0 = clamp(priorTheta0Mean, min, max);
  let lambda = priorLambdaMean;
  let iterations = 0;
  let converged = false;

  let h00 = theta0Precision;
  let h01 = 0;
  let h11 = lambdaPrecision;

  for (let iter = 0; iter < maxIterations; iter += 1) {
    iterations = iter + 1;
    let g0 = (priorTheta0Mean - theta0) * theta0Precision;
    let g1 = (priorLambdaMean - lambda) * lambdaPrecision;
    h00 = theta0Precision;
    h01 = 0;
    h11 = lambdaPrecision;

    for (const trial of trials) {
      const t = trial.trialIndex;
      const theta = theta0 + lambda * t;
      const difficulty = clamp(trial.difficulty, min, max);
      const observed = isFiniteNumber(trial.score) ? clamp(trial.score, 0, 1) : 0;

      const star = 1 / (1 + Math.exp(-slope * (theta - difficulty)));
      const p = c + (1 - c) * star;
      if (p <= 0 || p >= 1) continue;

      // Score and information for the logistic with a lower asymptote. At `c = 0` these reduce to
      // `slope * (observed - p)` and `slope^2 * p * (1 - p)`, the plain 1PL pair.
      const s = (slope * (p - c) * (observed - p)) / (p * (1 - c));
      const info = (slope * slope * (p - c) * (p - c) * (1 - p)) / ((1 - c) * (1 - c) * p);

      g0 += s;
      g1 += t * s;
      h00 += info;
      h01 += t * info;
      h11 += t * t * info;
    }

    const det = h00 * h11 - h01 * h01;
    if (!Number.isFinite(det) || det <= 0) break;
    const step0 = (h11 * g0 - h01 * g1) / det;
    const step1 = (h00 * g1 - h01 * g0) / det;

    // Damp the early moves: an all-correct or all-incorrect block produces a gradient that
    // overshoots to the bound and then oscillates between the bounds without ever converging.
    const damp = Math.min(1, 2 / (1 + Math.max(Math.abs(step0), 10 * Math.abs(step1))));
    theta0 = clamp(theta0 + damp * step0, min, max);
    lambda = clamp(lambda + damp * step1, -LAMBDA_BOUND, LAMBDA_BOUND);

    if (Math.abs(damp * step0) < tolerance && Math.abs(damp * step1) < tolerance) {
      converged = true;
      break;
    }
  }

  const det = h00 * h11 - h01 * h01;
  const theta0Se = det > 0 ? Math.sqrt(h11 / det) : priorTheta0Sd;
  const lambdaSe = det > 0 ? Math.sqrt(h00 / det) : priorLambdaSd;

  return { theta0, lambda, theta0Se, lambdaSe, iterations, converged };
}

/** Bisection steps for {@link estimateBlockLevel}. Fixed so a stored trace re-scores exactly. */
const LEVEL_BISECTION_STEPS = 60;

/**
 * Posterior-mode ability for a block, fitted with NO climb term: `theta(t) = theta`.
 *
 * The same response model, floor, scale and `theta0` prior as {@link estimateLearningCurve}, with
 * `lambda` held at zero rather than estimated. It answers "where is this child working RIGHT NOW,
 * averaged over what they have done so far", which is what an administering caller needs in order
 * to aim the next item, and it is deliberately NOT the same question as "how fast are they
 * climbing".
 *
 * WHY THIS EXISTS SEPARATELY FROM `deriveAbilityEstimate` in `ability.ts`, which fits the same
 * no-climb model: that fit centres its prior on the scale midpoint and cannot be re-centred, and a
 * block has a settled standing estimate handed over to it that a midpoint prior would throw away.
 * The two are otherwise the same fit and should stay in step; if `ability.ts` ever gains a prior
 * mean, this should delegate to it.
 *
 * Bisection rather than Fisher scoring, and a fixed step count rather than a tolerance, for the
 * reason `ability.ts` gives: the result has to be bit-for-bit reproducible from a stored trace.
 * With one free parameter the score is monotone decreasing in `theta` at `c = 0`; with `c > 0` the
 * weakly-informative prior makes a second mode vanishingly unlikely and bisection is reproducible
 * either way.
 */
export function estimateBlockLevel(
  trials: readonly LearningTrial[],
  options: LearningCurveOptions = {},
): number {
  const {
    slope = 1.0,
    min = SCALE_MIN,
    max = SCALE_MAX,
    priorTheta0Mean = (min + max) / 2,
    priorTheta0Sd = 6.0,
    guessing = DEFAULT_GUESSING,
  } = options;

  const c = clamp(guessing, 0, 0.99);
  const priorMean = clamp(priorTheta0Mean, min, max);
  const precision = priorTheta0Sd > 0 ? 1 / (priorTheta0Sd * priorTheta0Sd) : 0;

  const gradient = (theta: number): number => {
    let g = (priorMean - theta) * precision;
    for (const trial of trials) {
      const difficulty = clamp(trial.difficulty, min, max);
      const observed = isFiniteNumber(trial.score) ? clamp(trial.score, 0, 1) : 0;
      const star = 1 / (1 + Math.exp(-slope * (theta - difficulty)));
      const p = c + (1 - c) * star;
      if (p <= 0 || p >= 1) continue;
      g += (slope * (p - c) * (observed - p)) / (p * (1 - c));
    }
    return g;
  };

  if (gradient(min) <= 0) return min;
  if (gradient(max) >= 0) return max;

  let lo = min;
  let hi = max;
  for (let i = 0; i < LEVEL_BISECTION_STEPS; i += 1) {
    const mid = (lo + hi) / 2;
    if (gradient(mid) > 0) lo = mid;
    else hi = mid;
  }
  return (lo + hi) / 2;
}

/** Trials needed before the fit carries enough information to project from. */
export const MIN_TRIALS_FOR_PROJECTION = 4;

/**
 * Trials of observed accuracy the aim is corrected against in {@link nextTargetTheta}.
 *
 * Short enough that a climbing child's recent accuracy reflects where they are NOW rather than
 * where they averaged over the block, long enough that the correction is not chasing single
 * responses. Eight and twelve were both measured (E-206) and behave the same on the null; eight
 * recovers more of the lag, so it is the one used.
 */
const RECENT_ACCURACY_WINDOW = 8;

export interface TargetingOptions extends LearningCurveOptions {
  /**
   * How far ABOVE the child the next item should sit, in scale points.
   *
   * This is the desirable-difficulty knob: a positive offset keeps the block harder than the
   * child's settled standing so there is headroom to climb into. It is exposed rather than fixed
   * because the right value is a question about what keeps a child working, not a statistical one
   * — synthetic work found the difficulty regime moves recovery by around 0.015 in correlation,
   * which is negligible next to the difference between a child who engages and one who gives up.
   *
   * It is a TARGET rather than a literal addend. {@link nextTargetTheta} corrects toward it using
   * observed accuracy, so it also sets the accuracy the block aims to hold: under a floor `c` the
   * intended accuracy is `c + (1 - c) * sigmoid(-slope * targetOffset)`, which at the shipped
   * `c = 0.2` and an offset of 1 is 41.5%.
   */
  readonly targetOffset?: number;
  /**
   * Standing estimate carried in from the bracketing phase, used to anchor the block before it has
   * enough trials to project from.
   */
  readonly standingEstimate?: number;
}

/**
 * Difficulty to aim the next trial at, given the trials so far.
 *
 * Re-fits on every call rather than walking a preset ladder. That is what makes the block adaptive
 * in the sense that matters here: the target follows the child UP as they learn, so a fast learner
 * does not spend the back half of the block on items they have outgrown, which is precisely where
 * the climb signal would otherwise be lost to a ceiling.
 *
 * IT AIMS AT THE FITTED LEVEL, AND DELIBERATELY DOES NOT EXTRAPOLATE THE FITTED CLIMB. This
 * function used to return `theta0 + lambda * t + offset` from {@link estimateLearningCurve} — the
 * projected ability at the next trial. That closed a loop from the estimate of `lambda` back onto
 * the design that identifies `lambda`, and D-206 measures what the loop does: on a cohort with
 * `lambda_true = 0` for every child and a CORRECTLY specified floor, the projecting rule fits
 * λ̄ = 0.0097 ± 0.0011 on `FLU-OPCHAIN-01` (8.6 Monte-Carlo SEs from zero) and 0.0085 on an
 * idealised grid with no bank at all; aiming at the level instead returns −0.0007 and −0.0033,
 * which is the same as freezing the difficulty outright and is the open-loop bound. Recovery of a
 * real climb goes UP rather than down (r 0.332 → 0.365 at 30 trials), because the excursions the
 * projection produced were noise rather than signal.
 *
 * WHY THE LOOP BIT, in one sentence, because it is not obvious and the sign surprises people: a
 * spuriously positive `lambda` aims the next items ABOVE the child, where a floored logistic
 * carries `~4d^2` of information against `~(1-c)d` on the equally mis-aimed easy side, so the
 * later trials that would CONTRADICT the spurious climb arrive down-weighted to nearly nothing
 * while the ones that would contradict a spurious fall arrive at full weight. The asymmetry is
 * proportional to the floor and vanishes at `c = 0`, which is why this was invisible against a
 * floorless simulated responder.
 *
 * A LEVEL FIT ALONE LAGS A CLIMBING CHILD, SO THE AIM IS THEN CORRECTED AGAINST OBSERVED ACCURACY.
 * The level fit averages over the whole block, so for a child climbing at `lambda` it sits roughly
 * `lambda * t / 2` behind them, and the level-only rule under-served the fastest learners badly: at
 * `lambda = 0.15` the mean served difficulty ran 0.57 scale points BELOW ability instead of the
 * intended `targetOffset` above it, and late accuracy rose to 69%. The correction below closes that
 * to 0.10 points and 61% (E-206).
 *
 * The correction is driven by OBSERVED ACCURACY over the last {@link RECENT_ACCURACY_WINDOW}
 * trials, not by the fitted `lambda`, and that distinction is the whole design. An offset that
 * widens when the fit is optimistic is the loop D-206 removed, wearing a different hat: it aims
 * higher exactly when `lambda` is overstated, and the asymmetry above then protects the error. An
 * offset driven by accuracy is the opposite sign of feedback — aiming too high LOWERS accuracy,
 * which retracts the correction on the next trial. It is a servo on the quantity `targetOffset`
 * exists to control, not a projection of the quantity being estimated.
 *
 * IT IS SYMMETRIC, AND THAT IS LOAD-BEARING RATHER THAN TIDY. A rectified version that only ever
 * pushes forward was measured too, and it costs: under the null the rectifier turns response noise
 * into a one-way ratchet, so a static child's mean served difficulty rises from 1.26 to 1.49 points
 * above them, the feedback term grows by half, and the indeterminate rate goes from 6.3% to 11.1%.
 * Correcting in both directions leaves the null cohort's served difficulty slightly CLOSER to them
 * (1.26 → 1.10) than the uncorrected level rule, so the fast learner's headroom is not bought by
 * pushing everyone else up.
 *
 * Verified by attribution rather than assumed: replaying each rule's served-difficulty sequence to
 * an untargeted twin isolates the feedback term, which is 0.0045 ± 0.0012 for the level rule alone
 * and 0.0046 ± 0.0012 with this correction — indistinguishable — against 0.0146 ± 0.0015 for the
 * projecting rule D-206 removed (E-206).
 *
 * WHAT IT DOES NOT FIX: the correction is a one-step servo, so it still trails a child climbing
 * much faster than the design anticipated. At `lambda = 0.30` the served difficulty is 1.6 points
 * below ability and late accuracy is 83%. Tracking that would need a projection, which is the thing
 * that cannot be afforded.
 *
 * Below `MIN_TRIALS_FOR_PROJECTION` the fit is dominated by its prior and carries no real
 * information, so the standing estimate is returned unchanged instead of pretending to project.
 */
export function nextTargetTheta(
  trials: readonly LearningTrial[],
  options: TargetingOptions = {},
): number {
  const {
    targetOffset = 0,
    standingEstimate = (SCALE_MIN + SCALE_MAX) / 2,
    min = SCALE_MIN,
    max = SCALE_MAX,
    slope = 1.0,
    guessing = DEFAULT_GUESSING,
  } = options;

  if (trials.length < MIN_TRIALS_FOR_PROJECTION) {
    return clamp(standingEstimate + targetOffset, min, max);
  }

  const level = estimateBlockLevel(trials, { ...options, priorTheta0Mean: standingEstimate });
  const correction = accuracyCorrection(trials, clamp(guessing, 0, 0.99), slope, targetOffset);
  return clamp(level + targetOffset + correction, min, max);
}

/**
 * Scale points to add to the aim so that recent observed accuracy moves toward the accuracy
 * `targetOffset` is designed to produce.
 *
 * Both accuracies are put through the SAME floored logistic the fit uses and differenced on the
 * logit scale, so the correction is in scale points by construction and there is no gain constant
 * to choose. Under the declared floor `c`, aiming `targetOffset` above a child yields
 * `c + (1 - c) * sigmoid(-slope * targetOffset)`; observing more than that means the aim is low by
 * the logit distance between the two, and observing less means it is high by the same measure.
 *
 * The proportion is pulled off the boundary by `1 / 2n` before inverting — the usual continuity
 * correction — because an all-correct or all-incorrect window inverts to an infinite correction.
 * That bound is what keeps a single extreme window from throwing the aim across the scale, and it
 * is the only constant here that is not read off the response model.
 */
function accuracyCorrection(
  trials: readonly LearningTrial[],
  c: number,
  slope: number,
  targetOffset: number,
): number {
  const recent = trials.slice(-RECENT_ACCURACY_WINDOW);
  if (recent.length === 0 || c >= 1 || !(slope > 0)) return 0;

  let total = 0;
  for (const trial of recent) {
    total += isFiniteNumber(trial.score) ? clamp(trial.score, 0, 1) : 0;
  }
  const observed = total / recent.length;

  const edge = 1 / (2 * recent.length);
  const above = clamp((observed - c) / (1 - c), edge, 1 - edge);
  const intended = 1 / (1 + Math.exp(slope * targetOffset));

  const logitGap = Math.log(above / (1 - above)) - Math.log(intended / (1 - intended));
  return logitGap / slope;
}
